import { describe,expect,it } from 'vitest';
import { DocumentStore,createDocument } from '../core/document';
import { DEFAULT_SETTINGS } from '../shared/settings';
import { SourceProjection } from './source-projection';
import { applyPlan,blockAt,clearInline,codeAt,codePlan,deletionPlan,formattedRange,lineEndingPlan,markdownBlocks,moveLinePlan,paragraphPlan,semanticRange,sourceLines,splitTableCells,tableAt,tablePlan,toggleInline,type EditPlan } from '../core/formatting';
const select=(anchor:number,head=anchor)=>({anchor,head});
function transact(store:DocumentStore,plan:EditPlan){const snapshot=store.getSnapshot();store.apply({transactionId:crypto.randomUUID(),documentId:snapshot.documentId,baseVersion:snapshot.version,origin:'command',...plan});}
describe('canonical source and view mapping',()=>{
  it('preserves untouched CRLF, LF, Unicode, whitespace and incomplete syntax across modes',()=>{const source='😀 标题\r\n  保留空格\n**未闭合\r\n';const projection=new SourceProjection(source);expect(projection.text).toBe('😀 标题\n  保留空格\n**未闭合\n');for(let offset=0;offset<=source.length;offset++)if(source[offset-1]!=='\r')expect(projection.toSource(projection.toView(offset))).toBe(offset);const store=new DocumentStore(createDocument(source));const before=store.getSnapshot();new SourceProjection(before.text);new SourceProjection(before.text);expect(store.getSnapshot()).toBe(before);});
  it('maps a typed line change to raw offsets without normalizing other lines',()=>{const source='😀\r\na\nb\r\n',projection=new SourceProjection(source);const changes=projection.changesToSource([{from:projection.text.indexOf('a'),to:projection.text.indexOf('a')+1,insert:'甲\n乙'}]);expect(applyPlan(source,{changes,selection:select(0)})).toBe('😀\r\n甲\r\n乙\nb\r\n');});
  it('distinguishes a terminal empty line from the end of a nonempty line',()=>{expect(sourceLines('a').map(line=>line.text)).toEqual(['a']);expect(sourceLines('a\r\n').map(line=>line.text)).toEqual(['a','']);const plan=paragraphPlan('a',select(1),'heading2',DEFAULT_SETTINGS)!;expect(applyPlan('a',plan)).toBe('## a');});
  it('converts line endings in one undoable command, preserving selection and text',()=>{const store=new DocumentStore(createDocument('😀\r\n甲\n乙'));store.setSelection(select(4,7));transact(store,lineEndingPlan(store.getSnapshot().text,store.getSnapshot().selection,'LF'));expect(store.getSnapshot().text).toBe('😀\n甲\n乙');store.undo();expect(store.getSnapshot().text).toBe('😀\r\n甲\n乙');expect(store.getSnapshot().selection).toEqual(select(4,7));});
});
describe('formatting and semantic ranges',()=>{
  it('wraps and unwraps Unicode without bisecting source or touching neighbors',()=>{const source='前😀中文后',plan=toggleInline(source,select(1,5),'bold')!,formatted=applyPlan(source,plan);expect(formatted).toBe('前**😀中文**后');expect(applyPlan(formatted,toggleInline(formatted,plan.selection,'bold')!)).toBe(source);});
  it('uses a longer code delimiter for literal backticks',()=>{const source='`literal`',plan=toggleInline(source,select(0,source.length),'code')!;expect(applyPlan(source,plan)).toBe('`` `literal` ``');});
  it('finds the innermost parsed format in nested emphasis rather than the nearest star',()=>{const text='**粗体 *里面* 外面**';expect(formattedRange(text,text.indexOf('里面')+1)?.name).toBe('Emphasis');const range=semanticRange(text,select(text.indexOf('里面')+1),'formatted');expect(text.slice(range.anchor,range.head)).toBe('*里面*');});
  it('clears visual style while retaining literal code and a link target',()=>{const text='**粗体** 与 `**literal**` [*链接*](https://example.com)';const result=applyPlan(text,clearInline(text,select(0,text.length)));expect(result).toBe('粗体 与 `**literal**` [链接](https://example.com)');});
  it('uses Unicode word segmentation and never deletes half an emoji',()=>{expect(applyPlan('a😀b',deletionPlan('a😀b',select(1)))).toBe('ab');const word=semanticRange('hello世界',select(2),'word');expect('hello世界'.slice(word.anchor,word.head)).toBe('hello');});
  it('converts only selected headings and retains other original structure',()=>{const text='旧标题\r\n=====\r\n\r\n未选 **原文**';const plan=paragraphPlan(text,select(1),'heading3',DEFAULT_SETTINGS)!;expect(applyPlan(text,plan)).toBe('### 旧标题\r\n\r\n未选 **原文**');});
  it('toggles lists and task states as single transactions',()=>{const text='😀一\r\n二',store=new DocumentStore(createDocument(text));transact(store,paragraphPlan(text,select(0,text.length),'task',DEFAULT_SETTINGS)!);expect(store.getSnapshot().text).toBe('- [ ] 😀一\r\n- [ ] 二');transact(store,paragraphPlan(store.getSnapshot().text,select(0,store.getSnapshot().text.length),'taskState',DEFAULT_SETTINGS)!);expect(store.getSnapshot().text).toBe('- [x] 😀一\r\n- [x] 二');store.undo();store.undo();expect(store.getSnapshot().text).toBe(text);});
  it('moves a final line without losing the separator or changing another CRLF',()=>{const text='a\r\n😀\r\nlast';const plan=moveLinePlan(text,select(text.indexOf('last')),-1)!;expect(applyPlan(text,plan)).toBe('a\r\nlast\r\n😀');expect(applyPlan(text,moveLinePlan(text,select(text.indexOf('😀')),1)!)).toBe('a\r\nlast\r\n😀');});
});
describe('tables and fenced source',()=>{
  const source='前文\r\n\r\n| 名称 | 内容 |\r\n| :--- | ---: |\r\n| 😀 | a\\|b |\r\n| 二 | `x|y` |\r\n\r\n后文';
  it('keeps escaped pipes and pipes inside code in their cells',()=>{expect(splitTableCells('| 😀 | a\\|b | `x|y` |')).toEqual(['😀','a\\|b','`x|y`']);expect(tableAt(source,source.indexOf('a\\|b'))?.rows[1]).toEqual(['😀','a\\|b']);});
  it('inserts columns and rows with stable Unicode cells and all history steps',()=>{const store=new DocumentStore(createDocument(source));store.setSelection(select(source.indexOf('a\\|b')));transact(store,tablePlan(source,store.getSnapshot().selection,'columnBefore')!);expect(tableAt(store.getSnapshot().text,store.getSnapshot().selection.head)?.rows[1]).toEqual(['😀','','a\\|b']);transact(store,tablePlan(store.getSnapshot().text,store.getSnapshot().selection,'rowAfter')!);expect(tableAt(store.getSnapshot().text,store.getSnapshot().selection.head)?.rows.length).toBe(4);store.undo();store.undo();expect(store.getSnapshot().text).toBe(source);});
  it('moves alignment with columns and retains surrounding raw text',()=>{const plan=tablePlan(source,select(source.indexOf('a\\|b')),'moveColumnLeft')!,next=applyPlan(source,plan),table=tableAt(next,plan.selection.head)!;expect(table.rows[1]).toEqual(['a\\|b','😀']);expect(table.alignments[0]).toMatch(/:$/);expect(next.startsWith('前文\r\n\r\n')).toBe(true);expect(next.endsWith('\r\n\r\n后文')).toBe(true);});
  it('navigates the last cell by adding an undoable empty row',()=>{const plan=tablePlan(source,select(source.indexOf('`x|y`')),'nextCell')!,next=applyPlan(source,plan);expect(tableAt(next,plan.selection.head)?.rows.at(-1)).toEqual(['','']);});
  it('removes the final column as the table and keeps surrounding blocks',()=>{const text='before\n\n| a |\n| --- |\n| b |\n\nafter',plan=tablePlan(text,select(text.indexOf('b |')),'deleteColumn')!;expect(applyPlan(text,plan)).toBe('before\n\n\n\nafter');});
  it('keeps unknown fenced language and literal syntax untouched',()=>{const text='````unknown\r\n**literal**\r\n```\r\n````\r\n\n# heading';const code=codeAt(text,15)!;expect(text.slice(code.contentFrom,code.contentTo)).toBe('**literal**\r\n```\r\n');const plan=codePlan(text,select(15),'language',DEFAULT_SETTINGS,'python')!;expect(applyPlan(text,plan)).toBe(text.replace('unknown','python'));expect(markdownBlocks(text).filter(block=>block.kind==='heading')).toHaveLength(1);});
  it('recognizes unclosed fences as source rather than dropping content',()=>{const text='```foo\n不完整\n# 仍在代码';expect(blockAt(text,10).kind).toBe('code');expect(markdownBlocks(text)[0].text).toBe(text);});
});
