import { describe,expect,it } from 'vitest';
import { applyPlan } from '../core/formatting';
import { DEFAULT_SETTINGS } from '../shared/settings';
import { assistInput,deleteMatchingPair,newlineBetweenFences } from './input-assistance';
describe('input assistance boundaries',()=>{
  it('wraps a Unicode selection and supports paired deletion independently of Markdown pairing',()=>{const text='😀中文',plan=assistInput(text,0,text.length,'(',DEFAULT_SETTINGS)!;expect(applyPlan(text,plan)).toBe('(😀中文)');expect(plan.selection).toEqual({anchor:1,head:5});expect(applyPlan('()',deleteMatchingPair('()',{anchor:1,head:1},DEFAULT_SETTINGS)!)).toBe('');expect(assistInput('',0,0,'*',DEFAULT_SETTINGS)).toBeNull();});
  it('does not interfere with composition, escaped input or apostrophes in words',()=>{expect(assistInput('',0,0,'(',DEFAULT_SETTINGS,true)).toBeNull();expect(deleteMatchingPair('()',{anchor:1,head:1},DEFAULT_SETTINGS,true)).toBeNull();expect(assistInput('\\',1,1,'(',DEFAULT_SETTINGS)).toBeNull();expect(assistInput('don',3,3,"'",DEFAULT_SETTINGS)).toBeNull();});
  it('grows matched Markdown markers for bold and fences instead of leaving the caret outside',()=>{const settings={...DEFAULT_SETTINGS,'editor.matchMarkdown':true};const first=assistInput('',0,0,'*',settings)!,one=applyPlan('',first),second=assistInput(one,1,1,'*',settings)!;expect(applyPlan(one,second)).toBe('****');expect(second.selection.head).toBe(2);const fence=assistInput('````',2,2,'`',settings)!;expect(applyPlan('````',fence)).toBe('``````');const newline=newlineBetweenFences('``````',{anchor:3,head:3})!;expect(applyPlan('``````',newline)).toBe('```\n\n```');});
  it('keeps quotes and dashes literal in code and render-only mode',()=>{const settings={...DEFAULT_SETTINGS,'markdown.smartQuotes':true,'markdown.smartDashes':true};expect(assistInput('```js\n-',7,7,'-',settings)).toBeNull();expect(assistInput('hello',5,5,'"',{...settings,'markdown.smartMode':'render','editor.matchBrackets':false})).toBeNull();expect(applyPlan('-',assistInput('-',1,1,'-',settings)!)).toBe('–');expect(applyPlan('–',assistInput('–',1,1,'-',settings)!)).toBe('—');});
  it('honors pair settings when only Markdown markers are enabled',()=>{const settings={...DEFAULT_SETTINGS,'editor.matchBrackets':false,'editor.matchMarkdown':true};expect(assistInput('',0,0,'(',settings)).toBeNull();expect(applyPlan('',assistInput('',0,0,'=',settings)!)).toBe('==');});
});
