import { forwardRef,useEffect,useImperativeHandle,useRef,useState } from 'react';
import { Annotation,Compartment,EditorSelection,EditorState,StateEffect,StateField,Transaction,type Range } from '@codemirror/state';
import { Decoration,EditorView,WidgetType,drawSelection,highlightActiveLine,keymap,lineNumbers,type DecorationSet } from '@codemirror/view';
import { defaultKeymap,indentWithTab } from '@codemirror/commands';
import { autocompletion,completionKeymap,type CompletionContext } from '@codemirror/autocomplete';
import { defaultHighlightStyle,indentUnit,syntaxHighlighting } from '@codemirror/language';
import { languages } from '@codemirror/language-data';
import { deleteMarkupBackward,insertNewlineContinueMarkup,markdown,markdownLanguage } from '@codemirror/lang-markdown';
import emojis from 'markdown-it-emoji/lib/data/full.mjs';
import type { EditorHandle,EditorProps } from '../shared/components';
import type { SettingsSnapshot } from '../shared/settings';
import type { SearchMatch,SelectionRange,TextChange } from '../shared/contracts';
import { COMMANDS,matchesShortcut } from '../shared/command-catalog';
import { applyPlan,blockAt,codeAt,formattedRange,lineAt,markdownBlocks,orderedSelection,preferredNewline,tableAt,tablePlan,type MarkdownBlock } from '../core/formatting';
import { hydrateDiagrams,renderMarkdown } from '../render/markdown';
import { SourceProjection } from './source-projection';
import { EDITOR_COMMAND_IDS,canExecuteEditorCommand,clipboardRange,commitPlan,executeTextCommand,selectedCodeOrTable,simpleMarkdownText } from './commands';
import { htmlToMarkdown } from './html-paste';
import './editor.css';
export { EDITOR_COMMAND_IDS,canExecuteEditorCommand } from './commands';

interface PreviewConfig { settings:SettingsSnapshot; sourceMode:boolean; focusMode:boolean; composing:boolean; path:string|null; rawText:string; documentId:string }
interface SearchState { matches:SearchMatch[];currentIndex:number }
const updatePreview=StateEffect.define<PreviewConfig>(),updateSearch=StateEffect.define<SearchState>(),externalChange=Annotation.define<boolean>();
const previewConfiguration=StateField.define<PreviewConfig>({create:()=>{throw new Error('Preview configuration must be initialized');},update:(value,transaction)=>{
  const effect=transaction.effects.find(effect=>effect.is(updatePreview));if(effect)return effect.value;
  if(transaction.docChanged){const changes:TextChange[]=[];transaction.changes.iterChanges((from,to,_newFrom,_newTo,insert)=>changes.push({from,to,insert:insert.toString()}));const rawChanges=new SourceProjection(value.rawText).changesToSource(changes,value.settings['editor.lineEnding']);return {...value,rawText:applyPlan(value.rawText,{changes:rawChanges,selection:{anchor:0,head:0}})};}
  return value;
}});
const searchState=StateField.define<SearchState>({create:()=>({matches:[],currentIndex:-1}),update:(value,transaction)=>transaction.effects.find(effect=>effect.is(updateSearch))?.value??value});
const htmlCache=new Map<string,string>();
function settingsKey(settings:SettingsSnapshot):string{return JSON.stringify(settings);}
function renderBlock(block:MarkdownBlock,configuration:PreviewConfig):string {
  const references=configuration.rawText.match(/^ {0,3}\[[^\]\n]+\]:[^\n]*(?:\n(?: {2,}|\t)[^\n]*)*/gm)?.join('\n')??'';
  const key=[block.kind,block.text,references,settingsKey(configuration.settings),configuration.path].join('\u0000');const cached=htmlCache.get(key);if(cached!==undefined)return cached;
  let html:string;
  if(block.kind==='toc'){const full=renderMarkdown(configuration.rawText,configuration.settings,{path:configuration.path}),document=new DOMParser().parseFromString(full,'text/html');html=document.querySelector('.markdown-toc')?.outerHTML??'<nav class="markdown-toc">暂无标题</nav>';}
  else html=renderMarkdown(block.text+(references?'\n\n'+references:''),configuration.settings,{path:configuration.path});
  if(htmlCache.size>=250)htmlCache.delete(htmlCache.keys().next().value!);htmlCache.set(key,html);return html;
}
class PreviewWidget extends WidgetType {
  constructor(readonly block:MarkdownBlock,readonly configuration:PreviewConfig){super();}
  eq(other:PreviewWidget){return this.block.from===other.block.from&&this.block.to===other.block.to&&this.block.text===other.block.text&&(this.block.kind!=='toc'&&!/\[[^\]]+\]/.test(this.block.text)||this.configuration.rawText===other.configuration.rawText)&&this.configuration.path===other.configuration.path&&this.configuration.settings===other.configuration.settings&&this.configuration.focusMode===other.configuration.focusMode;}
  toDOM(view:EditorView):HTMLElement {
    const element=document.createElement('article');element.className=`ot-preview-block ot-preview-${this.block.kind}${this.configuration.focusMode?' ot-dimmed':''}${this.configuration.settings['text.preserveSpaces']?' ot-preserve-spaces':''}${this.configuration.settings['text.firstIndent']?' ot-first-indent':''}${!this.configuration.settings['text.showBr']?' ot-hide-br':''}`;element.dataset.sourceFrom=String(this.block.from);element.dataset.sourceTo=String(this.block.to);element.setAttribute('aria-label',`${this.block.kind} Markdown 块，点击编辑`);
    try{element.innerHTML=renderBlock(this.block,this.configuration);}catch(error){element.textContent=this.block.text;const status=document.createElement('small');status.className='ot-render-error';status.textContent=`渲染失败：${String(error)}`;element.append(status);}
    element.querySelectorAll<HTMLInputElement>('input[type="checkbox"]').forEach((checkbox,index)=>{checkbox.disabled=view.state.readOnly;checkbox.addEventListener('mousedown',event=>event.stopPropagation());checkbox.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(view.state.readOnly)return;const config=view.state.field(previewConfiguration),blockSource=config.rawText.slice(this.block.from,this.block.to),tasks=[...blockSource.matchAll(/^(\s*(?:[-+*]|\d+[.)])\s+)\[([ xX])\]/gm)],task=tasks[index];if(!task)return;const projection=new SourceProjection(config.rawText),from=this.block.from+task.index!+task[1].length+1;view.dispatch({changes:{from:projection.toView(from),to:projection.toView(from+1),insert:task[2]===' '?'x':' '},annotations:TransactionUserEvent('input.task')});});});
    element.addEventListener('mousedown',event=>{
      if(event.button!==0||(event.target as Element).closest('input'))return;
      const link=(event.target as Element).closest<HTMLAnchorElement>('a[href]');if(link&&(event.ctrlKey||event.metaKey)){event.preventDefault();view.dom.dispatchEvent(new CustomEvent('opentypora:open-link',{bubbles:true,detail:{url:link.getAttribute('href')}}));return;}
      if(link&&link.getAttribute('href')?.startsWith('#')&&this.block.kind==='toc'){event.preventDefault();view.dom.dispatchEvent(new CustomEvent('opentypora:open-link',{bubbles:true,detail:{url:link.getAttribute('href')}}));return;}
      event.preventDefault();const config=view.state.field(previewConfiguration),projection=new SourceProjection(config.rawText),rectangle=element.getBoundingClientRect(),ratio=Math.max(0,Math.min(1,(event.clientY-rectangle.top)/Math.max(1,rectangle.height))),lines=this.block.text.split(/\r\n|\n|\r/);let raw=this.block.from;
      if(this.block.kind==='table'){const cell=(event.target as Element).closest('td,th');if(cell){const table=cell.closest('table'),rows=table?[...table.rows]:[],row=cell.parentElement?rows.indexOf(cell.parentElement as HTMLTableRowElement):0,column=[...(cell.parentElement?.children??[])].indexOf(cell);const model=tableAt(config.rawText,this.block.from);if(model){const sourceLine=model.lines[row===0?0:row+1];if(sourceLine){let pipes=0;raw=sourceLine.from;const value=sourceLine.text;for(let i=value.trimStart().startsWith('|')?value.indexOf('|')+1:0;i<value.length;i++){if(value[i]==='\\'){i++;continue;}if(value[i]==='|'&&pipes++===column){break;}if(pipes===column)raw=sourceLine.from+i;}raw=Math.max(sourceLine.from,Math.min(sourceLine.to,raw));}}}}
      else {const index=Math.min(lines.length-1,Math.floor(ratio*lines.length));raw+=lines.slice(0,index).reduce((offset,line)=>offset+line.length+preferredNewline(this.block.text).length,0);const x=Math.max(0,Math.min(1,(event.clientX-rectangle.left)/Math.max(1,rectangle.width)));raw+=Math.min(lines[index].length,Math.floor(x*lines[index].length));}
      // Avoid placing a caret between the two UTF-16 halves of an emoji.
      if(raw>0&&/[\uDC00-\uDFFF]/.test(config.rawText[raw]??''))raw--;
      const position=projection.toView(raw),anchor=event.shiftKey?view.state.selection.main.anchor:position;view.dispatch({selection:{anchor,head:position},scrollIntoView:true});view.focus();
    });
    queueMicrotask(()=>{if(element.isConnected)void hydrateDiagrams(element,this.configuration.settings).then(()=>{if(element.isConnected)view.requestMeasure();}).catch(error=>{if(element.isConnected){const message=document.createElement('small');message.className='ot-render-error';message.textContent=String(error);element.append(message);}});});
    return element;
  }
  ignoreEvent(){return true;}
}
function TransactionUserEvent(value:string){return Transaction.userEvent.of(value);}
function intersects(from:number,to:number,selection:SelectionRange):boolean {const range=orderedSelection(selection);return range.from===range.to?range.from>=from&&range.from<=to:range.from<=to&&range.to>=from;}
function buildDecorations(state:EditorState):DecorationSet {
  const config=state.field(previewConfiguration),projection=new SourceProjection(config.rawText),selection=projection.selectionToSource(state.selection.main),decorations:Range<Decoration>[]=[],blocks=markdownBlocks(config.rawText);
  if(!config.sourceMode)for(const block of blocks){const from=projection.toView(block.from),to=projection.toView(block.to);if(from>=to)continue;
    if(!intersects(block.from,block.to,selection)&&!config.composing)decorations.push(Decoration.replace({widget:new PreviewWidget(block,config),block:true}).range(from,to));
    else {
      if(block.kind==='heading'){const line=state.doc.lineAt(from),heading=/^ {0,3}(#{1,6})(?:\s|$)/.exec(line.text);if(heading){decorations.push(Decoration.line({class:`ot-edit-heading ot-h${heading[1].length}`}).range(line.from));if(!config.settings['editor.showActiveSource']&&selection.anchor===selection.head&&selection.head>block.from+heading[0].length&&!config.composing)decorations.push(Decoration.replace({}).range(from,from+heading[0].length));}}
      if(block.kind==='code'){const code=codeAt(config.rawText,block.from);if(code){let number=1;for(let line=state.doc.lineAt(from);line.from<=to;line=state.doc.line(Math.min(state.doc.lines,line.number+1))){decorations.push(Decoration.line({class:`ot-code-line${config.settings['code.wrap']?' ot-code-wrap':''}`,attributes:config.settings['code.lineNumbers']&&line.from>from&&line.to<to?{'data-code-line':String(number++)}:{}}).range(line.from));if(line.number===state.doc.lines||line.to>=to)break;}}}
      const tree=markdownLanguage.parser.parse(block.text),hide=!config.settings['editor.showActiveSource']&&selection.anchor===selection.head&&!config.composing;
      tree.iterate({enter(node){const rawFrom=block.from+node.from,rawTo=block.from+node.to,vFrom=projection.toView(rawFrom),vTo=projection.toView(rawTo);if(vTo<=vFrom)return;
        const styles:Record<string,string>={StrongEmphasis:'ot-bold',Emphasis:'ot-italic',Strikethrough:'ot-strike',InlineCode:'ot-inline-code',Link:'ot-link',Subscript:'ot-sub',Superscript:'ot-sup'};if(styles[node.name])decorations.push(Decoration.mark({class:styles[node.name]}).range(vFrom,vTo));
        if(['EmphasisMark','StrikethroughMark','SubscriptMark','SuperscriptMark'].includes(node.name)&&hide&&(selection.head<rawFrom-1||selection.head>rawTo+1))decorations.push(Decoration.replace({}).range(vFrom,vTo));
        if(node.name==='FencedCode'||node.name==='CodeBlock')return false;
      }});
    }
  }
  for(const [index,match] of state.field(searchState).matches.entries()){const from=projection.toView(match.from),to=projection.toView(match.to);if(from<to&&to<=state.doc.length)decorations.push(Decoration.mark({class:index===state.field(searchState).currentIndex?'ot-search-current':'ot-search-match'}).range(from,to));}
  return Decoration.set(decorations,true);
}
const livePreview=StateField.define<DecorationSet>({create:buildDecorations,update:(value,transaction)=>transaction.docChanged||transaction.selection||transaction.effects.some(effect=>effect.is(updatePreview)||effect.is(updateSearch))?buildDecorations(transaction.state):value,provide:field=>EditorView.decorations.from(field)});

interface DialogState {command:string;title:string;fields:{name:string;label:string;value:string;type?:string}[]}
interface ClipboardData {text:string;html?:string;image?:string;files?:string[]}
function dialogFor(command:string,store:EditorProps['store']):DialogState|null {
  const snapshot=store.getSnapshot(),{from,to}=orderedSelection(snapshot.selection),label=snapshot.text.slice(from,to);
  if(command==='format.link'||command==='format.linkActions'){const range=formattedRange(snapshot.text,snapshot.selection.head),source=range?.name==='Link'?snapshot.text.slice(range.from,range.to):'',match=/^\[([^\]]*)\]\(([^)]*)\)$/.exec(source);return {command,title:'编辑超链接',fields:[{name:'label',label:'文字',value:match?.[1]??label},{name:'url',label:'地址',value:match?.[2]??'https://'},{name:'title',label:'提示标题（可选）',value:''}]};}
  if(command==='image.insert')return {command,title:'插入图片',fields:[{name:'url',label:'图片地址或路径',value:''},{name:'alt',label:'替代文本',value:''}]};
  if(command==='image.scale')return {command,title:'图片尺寸',fields:[{name:'width',label:'宽度（像素）',value:'320',type:'number'},{name:'height',label:'高度（可选，像素）',value:'',type:'number'}]};
  if(command==='table.create')return {command,title:'插入表格',fields:[{name:'rows',label:'行数（含表头）',value:'3',type:'number'},{name:'columns',label:'列数',value:'3',type:'number'}]};
  if(command==='table.alignment')return {command,title:'列对齐',fields:[{name:'alignment',label:'left / center / right / default',value:'left'}]};
  if(command==='code.language')return {command,title:'代码语言',fields:[{name:'language',label:'语言名称（留空为纯文本）',value:codeAt(snapshot.text,snapshot.selection.head)?.language??''}]};
  return null;
}
export const MarkdownEditor=forwardRef<EditorHandle,EditorProps>(function MarkdownEditor(props,ref){
  const mount=useRef<HTMLDivElement>(null),viewRef=useRef<EditorView|null>(null),propsRef=useRef(props),projectionRef=useRef(new SourceProjection(props.store.getSnapshot().text)),synchronizing=useRef(false),configurationCompartment=useRef(new Compartment());propsRef.current=props;
  const [dialog,setDialog]=useState<DialogState|null>(null),[error,setError]=useState(''),dialogRef=useRef<HTMLDialogElement>(null);
  const report=(message:string)=>{setError(message);};
  const writeClipboard=async(data:{text:string;html?:string})=>{const bridge=propsRef.current.bridge;if(bridge){const result=await bridge.systemAction('clipboard.write',data);if(!result.ok)throw new Error(result.error.message);return;}if(!navigator.clipboard)throw new Error('当前环境无法访问剪贴板，请使用桌面版或授予剪贴板权限');if(data.html&&typeof ClipboardItem!=='undefined')await navigator.clipboard.write([new ClipboardItem({'text/plain':new Blob([data.text],{type:'text/plain'}),'text/html':new Blob([data.html],{type:'text/html'})})]);else await navigator.clipboard.writeText(data.text);};
  const readClipboard=async():Promise<ClipboardData>=>{const bridge=propsRef.current.bridge;if(bridge){const result=await bridge.systemAction('clipboard.read');if(!result.ok)throw new Error(result.error.message);return result.value as ClipboardData;}if(!navigator.clipboard)throw new Error('当前环境无法读取剪贴板，请使用桌面版');return {text:await navigator.clipboard.readText()};};
  const paste=async(data:ClipboardData,plain=false)=>{
    const current=propsRef.current,{store,settings,bridge}=current,snapshot=store.getSnapshot();if(snapshot.readonly||snapshot.composing)return false;
    if(data.image&&!plain){if(!bridge)throw new Error('粘贴图片需要桌面资源服务');const result=await bridge.insertImage(snapshot.path,'clipboard');if(!result.ok)throw new Error(result.error.message);if(!result.value)return false;if(store.getSnapshot().documentId!==snapshot.documentId||store.getSnapshot().version!==snapshot.version)throw new Error('图片暂存期间正文已变化，请重新粘贴');return executeTextCommand(store,'image.insert',settings,{url:result.value.url,alt:''});}
    let insert=!plain&&data.html&&!data.text.match(/^\s*(?:#{1,6}\s|```|\|.+\|)/)?htmlToMarkdown(data.html):data.text;if(plain)insert=data.text||simpleMarkdownText(htmlToMarkdown(data.html??''));
    const {from,to}=orderedSelection(snapshot.selection);if(!insert)return true;const newline=preferredNewline(snapshot.text,settings['editor.lineEnding']);insert=insert.replace(/\r\n|\r|\n/g,newline);return commitPlan(store,{changes:[{from,to,insert}],selection:{anchor:from+insert.length,head:from+insert.length}},'input','paste');
  };
  const execute=async(id:string,argument?:unknown):Promise<boolean>=>{
    const current=propsRef.current,{store,settings}=current;if(!canExecuteEditorCommand(store,id))return false;setError('');
    try {
      if(id==='edit.copy'||id.startsWith('edit.copy')||id==='edit.cut'||id==='table.copy'||id==='code.copy'){
        const snapshot=store.getSnapshot(),range=clipboardRange(store,settings),source=id==='table.copy'?selectedCodeOrTable(store,'table'):id==='code.copy'?selectedCodeOrTable(store,'code'):range?.text;
        if(source==null)return false;
        const html=renderMarkdown(source,settings,{path:snapshot.path}),text=id==='edit.copyHTML'?html:id==='edit.copyPlain'||id==='edit.copySimplified'||id==='edit.copy'&&!settings['editor.copyMarkdown']?simpleMarkdownText(source):source;
        await writeClipboard({text,...(id==='edit.copy'||id==='edit.copySimplified'?{html}: {})});
        if(id==='edit.cut'&&range){if(store.getSnapshot().documentId!==snapshot.documentId||store.getSnapshot().version!==snapshot.version)throw new Error('剪贴板写入期间正文已变化，已复制但未删除正文');commitPlan(store,{changes:[{from:range.from,to:range.to,insert:''}],selection:{anchor:range.from,head:range.from}});}
        return true;
      }
      if(id==='edit.paste'||id==='edit.pastePlain')return await paste(await readClipboard(),id==='edit.pastePlain');
      if(argument===undefined){const next=dialogFor(id,store);if(next){setDialog(next);return true;}}
      const handled=executeTextCommand(store,id,settings,argument);if(handled)viewRef.current?.focus();return handled;
    }catch(caught){report(caught instanceof Error?caught.message:String(caught));return false;}
  };
  const executeRef=useRef(execute);executeRef.current=execute;
  useImperativeHandle(ref,()=>({execute:(id,argument)=>executeRef.current(id,argument),focus:()=>viewRef.current?.focus(),scrollTo:(rawPosition)=>{const view=viewRef.current;if(!view)return;const position=projectionRef.current.toView(rawPosition);view.dispatch({selection:{anchor:position,head:position},effects:EditorView.scrollIntoView(position,{y:'center'})});view.focus();}}),[]);
  const configuration=():PreviewConfig=>{const current=propsRef.current,snapshot=current.store.getSnapshot();return {settings:current.settings,sourceMode:current.sourceMode,focusMode:current.focusMode,composing:snapshot.composing,path:snapshot.path,rawText:snapshot.text,documentId:snapshot.documentId};};
  const extensions=()=>{const current=propsRef.current,snapshot=current.store.getSnapshot();return [indentUnit.of(' '.repeat(current.settings['editor.indent'])),EditorState.readOnly.of(snapshot.readonly),EditorView.editable.of(!snapshot.readonly),EditorView.contentAttributes.of({'aria-label':current.sourceMode?'Markdown 源码编辑器':'Markdown 即时编辑器',spellcheck:current.settings['editor.spellLanguage']==='off'?'false':'true',...(current.settings['editor.spellLanguage']!=='auto'?{lang:current.settings['editor.spellLanguage']}:{})}),...(current.sourceMode?[lineNumbers(),highlightActiveLine()]:[]),EditorView.lineWrapping,EditorView.theme({'.cm-content':{fontSize:`${current.settings['appearance.fontSize']}px`},'.cm-scroller':{paddingTop:current.typewriterMode?'45vh':'24px',paddingBottom:current.typewriterMode?'45vh':'80px'}})];};
  useEffect(()=>{
    if(!mount.current)return;const current=propsRef.current,projection=new SourceProjection(current.store.getSnapshot().text);projectionRef.current=projection;
    const synchronize=()=>{if(synchronizing.current)return;const view=viewRef.current;if(!view)return;const snapshot=propsRef.current.store.getSnapshot(),nextProjection=new SourceProjection(snapshot.text),selection=nextProjection.selectionToView(snapshot.selection),docChanged=view.state.doc.toString()!==nextProjection.text;projectionRef.current=nextProjection;synchronizing.current=true;
      try{view.dispatch({...(docChanged?{changes:{from:0,to:view.state.doc.length,insert:nextProjection.text}}:{}),selection:EditorSelection.single(selection.anchor,selection.head),effects:[updatePreview.of(configuration()),configurationCompartment.current.reconfigure(extensions())],annotations:externalChange.of(true)});}finally{synchronizing.current=false;}
    };
    const emojiCompletion=(context:CompletionContext)=>{if(!propsRef.current.settings['editor.emoji']||propsRef.current.store.getSnapshot().composing)return null;const config=context.state.field(previewConfiguration),raw=new SourceProjection(config.rawText).toSource(context.pos);if(blockAt(config.rawText,raw).kind==='code')return null;const token=context.matchBefore(/:[a-zA-Z0-9_+-]*:?/);if(!token||token.from===token.to&&!context.explicit)return null;return {from:token.from,options:Object.entries(emojis).map(([name,value])=>({label:`:${name}:`,detail:value,type:'text',apply:`:${name}:`})),validFor:/^:[a-zA-Z0-9_+-]*:?$/};};
    const view=new EditorView({parent:mount.current,state:EditorState.create({doc:projection.text,selection:projection.selectionToView(current.store.getSnapshot().selection),extensions:[previewConfiguration.init(configuration),searchState,livePreview,configurationCompartment.current.of(extensions()),markdown({base:markdownLanguage,codeLanguages:languages,pasteURLAsLink:true}),syntaxHighlighting(defaultHighlightStyle),drawSelection(),autocompletion({override:[emojiCompletion],activateOnTyping:true}),keymap.of([...completionKeymap,{key:'Enter',run:view=>view.compositionStarted?false:insertNewlineContinueMarkup(view),shift:view=>{view.dispatch(view.state.replaceSelection('  \n'));return true;}},{key:'Backspace',run:deleteMarkupBackward},{key:'Tab',run:view=>{const config=view.state.field(previewConfiguration),projection=new SourceProjection(config.rawText),selection=projection.selectionToSource(view.state.selection.main),table=tablePlan(config.rawText,selection,'nextCell');if(table)return commitPlan(propsRef.current.store,table);if(codeAt(config.rawText,selection.head))return executeTextCommand(propsRef.current.store,'code.indentSelection',propsRef.current.settings);if(blockAt(config.rawText,selection.head).kind==='list')return executeTextCommand(propsRef.current.store,'paragraph.indent',propsRef.current.settings);return indentWithTab.run!(view);},shift:view=>{const config=view.state.field(previewConfiguration),projection=new SourceProjection(config.rawText),selection=projection.selectionToSource(view.state.selection.main),table=tablePlan(config.rawText,selection,'previousCell');if(table)return commitPlan(propsRef.current.store,table);if(codeAt(config.rawText,selection.head)&&!propsRef.current.settings['code.shiftTab'])return false;return executeTextCommand(propsRef.current.store,'paragraph.outdent',propsRef.current.settings);}},...defaultKeymap]),EditorView.inputHandler.of((view,from,to,text)=>{
      const current=propsRef.current;if(view.compositionStarted||current.store.getSnapshot().composing)return false;const settings=current.settings,config=view.state.field(previewConfiguration),projection=new SourceProjection(config.rawText),raw=projection.toSource(from),code=codeAt(config.rawText,raw);let insert=text;
      if(settings['markdown.smartMode']==='input'&&!code){if(settings['markdown.smartQuotes']&&(text==='"'||text==="'")){const previous=config.rawText[raw-1]??'',opening=raw===0||/[\s([{—]/.test(previous);insert=text==='"'?(opening?'“':'”'):(opening?'‘':'’');}if(settings['markdown.smartDashes']&&text==='-'&&view.state.doc.sliceString(Math.max(0,from-1),from)==='-'){view.dispatch({changes:{from:from-1,to,insert:'—'},selection:{anchor:from},annotations:TransactionUserEvent('input.type')});return true;}}
      const pairs:Record<string,string>={'(':')','[':']','{':'}','"':'"',"'":"'",...(settings['editor.matchMarkdown']&&!code?{'*':'*','_':'_','`':'`','~':'~','=':'='}:{})};
      if((settings['editor.matchBrackets']||settings['editor.matchMarkdown'])&&text.length===1&&pairs[text]&&(settings['editor.matchBrackets']||'*_`~='.includes(text))){if(config.rawText[raw-1]==='\\')return false;const selected=view.state.doc.sliceString(from,to);if(!selected&&view.state.doc.sliceString(from,from+1)===text&&['"',"'",'*','_','`','~','='].includes(text)){view.dispatch({selection:{anchor:from+1}});return true;}if(insert!==text){view.dispatch({changes:{from,to,insert},selection:{anchor:from+insert.length},annotations:TransactionUserEvent('input.type')});return true;}const close=pairs[text];view.dispatch({changes:{from,to,insert:text+selected+close},selection:{anchor:from+text.length,head:from+text.length+selected.length},annotations:TransactionUserEvent('input.type')});return true;}
      if(settings['editor.matchBrackets']&&text.length===1&&')]}'.includes(text)&&view.state.doc.sliceString(from,from+1)===text){view.dispatch({selection:{anchor:from+1}});return true;}
      if(insert!==text){view.dispatch({changes:{from,to,insert},selection:{anchor:from+insert.length},annotations:TransactionUserEvent('input.type')});return true;}return false;
    }),EditorView.domEventHandlers({keydown(event){if(event.isComposing||propsRef.current.store.getSnapshot().composing)return false;let shortcuts:Record<string,string>={};try{shortcuts=JSON.parse(propsRef.current.settings['general.shortcuts']);}catch{}
      const command=COMMANDS.find(command=>EDITOR_COMMAND_IDS.includes(command.id)&&matchesShortcut(event,shortcuts[command.id]??command.shortcut??''));if(command&&canExecuteEditorCommand(propsRef.current.store,command.id)){event.preventDefault();void executeRef.current(command.id);return true;}return false;},compositionstart(){propsRef.current.store.setComposing(true);return false;},compositionend(){queueMicrotask(()=>propsRef.current.store.setComposing(false));return false;},copy(event){const range=clipboardRange(propsRef.current.store,propsRef.current.settings);if(!range||!event.clipboardData)return false;event.preventDefault();event.clipboardData.setData('text/plain',propsRef.current.settings['editor.copyMarkdown']?range.text:simpleMarkdownText(range.text));event.clipboardData.setData('text/html',renderMarkdown(range.text,propsRef.current.settings,{path:propsRef.current.store.getSnapshot().path}));return true;},cut(event){const store=propsRef.current.store,range=clipboardRange(store,propsRef.current.settings);if(!range||!event.clipboardData||store.getSnapshot().readonly)return false;event.preventDefault();event.clipboardData.setData('text/plain',range.text);event.clipboardData.setData('text/html',renderMarkdown(range.text,propsRef.current.settings));commitPlan(store,{changes:[{from:range.from,to:range.to,insert:''}],selection:{anchor:range.from,head:range.from}});return true;},paste(event){const data=event.clipboardData;if(!data)return false;if(data.files.length){event.preventDefault();void executeRef.current('edit.paste');return true;}event.preventDefault();void paste({text:data.getData('text/plain'),html:data.getData('text/html')},false).catch(caught=>report(String(caught)));return true;}})]}),dispatchTransactions(transactions,editor){
      synchronizing.current=true;
      try{for(const transaction of transactions){if(!transaction.annotation(externalChange)){const store=propsRef.current.store,snapshot=store.getSnapshot(),projection=projectionRef.current;if(transaction.docChanged){const changes:TextChange[]=[];transaction.changes.iterChanges((from,to,_newFrom,_newTo,insert)=>changes.push({from,to,insert:insert.toString()}));const sourceChanges=projection.changesToSource(changes,propsRef.current.settings['editor.lineEnding']),newSource=applyPlan(snapshot.text,{changes:sourceChanges,selection:snapshot.selection}),nextProjection=new SourceProjection(newSource),selection=nextProjection.selectionToSource(transaction.state.selection.main);store.apply({transactionId:crypto.randomUUID(),documentId:snapshot.documentId,baseVersion:snapshot.version,changes:sourceChanges,selection,origin:propsRef.current.sourceMode?'source':'input',historyGroup:transaction.isUserEvent('input.type')?'typing':transaction.isUserEvent('input.compose')?'composition':undefined});projectionRef.current=nextProjection;}else if(transaction.selection)store.setSelection(projection.selectionToSource(transaction.state.selection.main));}editor.update([transaction]);}}
      catch(caught){report(caught instanceof Error?caught.message:String(caught));}
      finally{synchronizing.current=false;}
      const config=configuration();if(editor.state.field(previewConfiguration).rawText!==config.rawText)editor.dispatch({effects:updatePreview.of(config),annotations:externalChange.of(true)});
      if(transactions.some(transaction=>(transaction.docChanged||transaction.selection)&&!transaction.annotation(externalChange))&&propsRef.current.typewriterMode&&propsRef.current.settings['editor.typewriterCenter']&&!editor.compositionStarted)editor.dispatch({effects:EditorView.scrollIntoView(editor.state.selection.main.head,{y:'center'}),annotations:externalChange.of(true)});
    }});
    viewRef.current=view;const unsubscribe=current.store.subscribe(synchronize);
    const searchListener=(event:Event)=>{const detail=(event as CustomEvent<{documentId:string;matches:SearchMatch[];currentIndex:number}>).detail;if(detail.documentId!==propsRef.current.store.getSnapshot().documentId)return;view.dispatch({effects:updateSearch.of({matches:detail.matches,currentIndex:detail.currentIndex}),annotations:externalChange.of(true)});};
    const linkListener=(event:Event)=>{const url=(event as CustomEvent<{url:string}>).detail.url;if(url.startsWith('#')){const text=propsRef.current.store.getSnapshot().text,blocks=markdownBlocks(text),slugs=new Map<string,number>();for(const block of blocks.filter(block=>block.kind==='heading')){const title=block.text.replace(/^\s*#{1,6}\s*/,'').split(/\r\n|\n/)[0],slug=title.toLowerCase().replace(/[^\p{L}\p{N}_-]+/gu,'-').replace(/^-|-$/g,'')||'heading',count=slugs.get(slug)??0;slugs.set(slug,count+1);if('#'+(count?`${slug}-${count}`:slug)===url){propsRef.current.store.setSelection({anchor:block.from,head:block.from});view.dispatch({effects:EditorView.scrollIntoView(projectionRef.current.toView(block.from),{y:'center'})});break;}}}else if(propsRef.current.bridge)void propsRef.current.bridge.openExternal(url).then(result=>{if(!result.ok)report(result.error.message);});else if(/^https?:|^mailto:/i.test(url))window.open(url,'_blank','noopener,noreferrer');else report('本地链接需要桌面服务');};
    window.addEventListener('opentypora:search',searchListener);view.dom.addEventListener('opentypora:open-link',linkListener);
    return()=>{unsubscribe();window.removeEventListener('opentypora:search',searchListener);view.dom.removeEventListener('opentypora:open-link',linkListener);view.destroy();viewRef.current=null;};
  },[props.store]);
  useEffect(()=>{const view=viewRef.current;if(!view)return;view.dispatch({effects:[updatePreview.of(configuration()),configurationCompartment.current.reconfigure(extensions())],annotations:externalChange.of(true)});},[props.settings,props.sourceMode,props.focusMode,props.typewriterMode]);
  useEffect(()=>{if(dialog){dialogRef.current?.showModal();dialogRef.current?.querySelector('input')?.focus();}},[dialog]);
  const closeDialog=()=>{dialogRef.current?.close();setDialog(null);viewRef.current?.focus();};
  return <div className={`ot-editor${props.sourceMode?' ot-source-mode':' ot-live-mode'}${props.focusMode?' ot-focus-mode':''}${props.typewriterMode?' ot-typewriter-mode':''}`}><div ref={mount} className="ot-editor-mount"/>{error&&<div className="ot-editor-error" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}>×</button></div>}{dialog&&<dialog ref={dialogRef} className="ot-editor-dialog" aria-labelledby="ot-dialog-title" onCancel={event=>{event.preventDefault();closeDialog();}}><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget),argument:Record<string,string|number>={};for(const field of dialog.fields){const value=String(data.get(field.name)??'');if(field.type==='number'&&value)argument[field.name]=Number(value);else if(field.type!=='number')argument[field.name]=value;}if(dialog.command==='table.alignment'&&!['left','center','right','default'].includes(String(argument.alignment))){report('对齐必须为 left、center、right 或 default');return;}if(dialog.fields.some(field=>field.type==='number'&&data.get(field.name)&&Number(data.get(field.name))<1)){report('尺寸与行列数量须大于零');return;}void executeRef.current(dialog.command,argument);closeDialog();}}><h2 id="ot-dialog-title">{dialog.title}</h2>{dialog.fields.map(field=><label key={field.name}>{field.label}<input name={field.name} defaultValue={field.value} type={field.type??'text'} min={field.type==='number'?1:undefined}/></label>)}<div className="ot-dialog-actions">{dialog.command==='format.linkActions'&&<button type="button" onClick={()=>{void executeRef.current('format.link',{remove:true});closeDialog();}}>移除链接</button>}<button type="button" onClick={closeDialog}>取消</button><button type="submit">确定</button></div></form></dialog>}</div>;
});
