import {expect,it,vi} from 'vitest';
import {DocumentStore,createDocument} from '../src/core/document';
import {refreshExternalFile} from '../src/platform/file-refresh';
import type {OpenedFile,Result} from '../src/shared/contracts';
const opened=(text:string,hash=text):OpenedFile=>({path:'E:/notes/a.md',text,encoding:'utf-8',bom:false,readonly:false,fingerprint:{hash,size:text.length,modifiedAt:1}});
function pending(){let resolve!:(value:Result<OpenedFile>)=>void;const promise=new Promise<Result<OpenedFile>>(r=>resolve=r);return {resolve,bridge:{readFile:vi.fn(()=>promise)}};}
it('rejects a late disk result after a user edit',async()=>{const store=new DocumentStore(createDocument('saved',opened('saved'))),read=pending();const operation=refreshExternalFile(store,read.bridge,'E:/notes/a.md',vi.fn());store.replaceText('later');read.resolve({ok:true,value:opened('external')});await operation;expect(store.getSnapshot().text).toBe('later');expect(store.getSnapshot().dirty).toBe(true);});
it('rejects a late result after a newer save changes the fingerprint',async()=>{const store=new DocumentStore(createDocument('saved',opened('saved'))),read=pending();const operation=refreshExternalFile(store,read.bridge,'E:/notes/a.md',vi.fn());store.markSaved({path:'E:/notes/a.md',version:0,fingerprint:opened('saved','new-save').fingerprint},'saved');read.resolve({ok:true,value:opened('old-read')});await operation;expect(store.getSnapshot().text).toBe('saved');expect(store.getSnapshot().diskFingerprint?.hash).toBe('new-save');});
it('marks a dirty document as conflict and never replaces it',async()=>{const store=new DocumentStore(createDocument('saved',opened('saved')));store.replaceText('dirty');await refreshExternalFile(store,{readFile:async()=>({ok:true,value:opened('external')})},'E:/notes/a.md',vi.fn());expect(store.getSnapshot().text).toBe('dirty');expect(store.getSnapshot().saveState).toBe('conflict');});
it('refreshes clean content while retaining navigation state',async()=>{const store=new DocumentStore(createDocument('saved',opened('saved')));store.patchMetadata({rootDirectory:'E:/notes'});store.setSelection({anchor:2,head:3});await refreshExternalFile(store,{readFile:async()=>({ok:true,value:opened('external')})},'E:/notes/a.md',vi.fn());expect(store.getSnapshot().text).toBe('external');expect(store.getSnapshot().rootDirectory).toBe('E:/notes');expect(store.getSnapshot().selection).toEqual({anchor:2,head:3});});
