// @vitest-environment jsdom
import {describe,expect,it} from 'vitest';
import {renderMarkdown,assetUrl,flowToMermaid,sequenceToMermaid} from '../src/render/markdown';
import {DEFAULT_SETTINGS} from '../src/shared/settings';
describe('Markdown projection',()=>{
  it('preserves plain relative HTML image paths while stripping executable URL schemes',()=>{
    const host=document.createElement('div');host.innerHTML=renderMarkdown('<img alt="logo" src="public/app-icon.png">\n<img alt="bad" src="javascript:alert(1)">\n<a href="javascript:alert(1)">bad</a>',DEFAULT_SETTINGS,{path:'E:/docs/README.md'});
    expect(host.querySelector('img[alt="logo"]')?.getAttribute('src')).toBe('opentypora-asset://local/E%3A%2Fdocs%2Fpublic%2Fapp-icon.png');
    expect(host.querySelector('img[alt="bad"]')?.hasAttribute('src')).toBe(false);expect(host.querySelector('a')?.hasAttribute('href')).toBe(false);
  });
  it('honors smart quotes and dashes independently and leaves literals untouched',()=>{const source='"hello" -- world... (c) `"literal" --`';const quotes=renderMarkdown(source,{...DEFAULT_SETTINGS,'markdown.smartMode':'render','markdown.smartQuotes':true,'markdown.smartDashes':false}),dashes=renderMarkdown(source,{...DEFAULT_SETTINGS,'markdown.smartMode':'render','markdown.smartQuotes':false,'markdown.smartDashes':true});expect(quotes).toContain('“hello” -- world... (c)');expect(dashes).toContain('"hello" – world… (c)');expect(dashes).toContain('<code>"literal" --</code>');});
  it('keeps literal table-code escapes and emits no formatting-only blank list rows',()=>{const host=document.createElement('div');host.innerHTML=renderMarkdown('| A | B |\n| --- | --- |\n| `a\\|b` | x |\n\n1. First\n   - Child\n     - [ ] Task\n\n   Continuation',DEFAULT_SETTINGS);expect(host.querySelector('td code')?.textContent).toBe('a\\|b');for(const list of host.querySelectorAll('ul,ol,li'))expect([...list.childNodes].some(node=>node.nodeType===Node.TEXT_NODE&&/^\s*\n\s*$/.test(node.textContent??''))).toBe(false);});
  it('retains safe SVG alert icons instead of parsing their path as Markdown',()=>{const host=document.createElement('div');host.innerHTML=renderMarkdown('> [!WARNING]\n> Be careful',DEFAULT_SETTINGS);expect(host.querySelector('.markdown-alert-title svg path')).not.toBeNull();expect(host.querySelector('.markdown-alert-title')?.textContent).toBe('Warning');expect(host.querySelector('.markdown-alert-title+br')).toBeNull();});
  it('uses strict and Unicode syntax switches in the rendered projection',()=>{const text='###Header\r\n\r\n》 quoted\r\n\r\n—\r\n\r\n[link](https://example.com «title»)';const strict=renderMarkdown(text,{...DEFAULT_SETTINGS,'markdown.strict':true,'markdown.unicodePunctuation':false}),loose=renderMarkdown(text,{...DEFAULT_SETTINGS,'markdown.strict':false,'markdown.unicodePunctuation':true});expect(strict).not.toContain('<h3');expect(loose).toContain('<h3');expect(loose).toContain('<blockquote>');expect(loose).toContain('<hr>');expect(loose).toContain('title="title"');expect(text).toContain('\r\n');});
  it('renders headings, navigation, GFM tables and footnotes without mutating source',()=>{const source='# A\r\n\r\n[toc]\r\n\r\n| A | B |\r\n| - | - |\r\n| 1 | 2 |\r\n\r\nNote[^x]\r\n\r\n[^x]: Footnote';const html=renderMarkdown(source,DEFAULT_SETTINGS);expect(html).toContain('id="a"');expect(html).toContain('markdown-toc');expect(html).toContain('<table>');expect(html).toContain('Footnote');expect(source).toContain('\r\n');});
  it('filters scripts, event handlers and dangerous URLs',()=>{const html=renderMarkdown('<img src=x onerror="alert(1)"><script>alert(1)</script>\n<a href="javascript:alert(1)">x</a>',DEFAULT_SETTINGS);expect(html).not.toContain('<script');expect(html).not.toContain('onerror');expect(html).not.toContain('javascript:');});
  it('applies extension switches and math delimiters',()=>{const html=renderMarkdown('==mark== H~2~O x^2^ $x^2$\n\n$$\nx^2\n$$',{...DEFAULT_SETTINGS,'markdown.highlight':true,'markdown.sub':true,'markdown.sup':true,'markdown.inlineMath':true});expect(html).toContain('<mark>');expect(html).toContain('<sub>');expect(html).toContain('<sup>');expect(html).toContain('katex');});
  it('projects diagrams and alerts as safe view-only widgets',()=>{const html=renderMarkdown('> [!WARNING]\n> Alert\n\n```mermaid\nflowchart TD\nA-->B\n```',DEFAULT_SETTINGS);expect(html).toContain('markdown-alert-warning');expect(html).toContain('data-diagram="mermaid"');expect(html).toContain('data-source=');});
  it('resolves relative assets and converts classic diagram dialects',()=>{expect(assetUrl('../assets/a.png','E:\\docs\\notes\\a.md')).toBe('opentypora-asset://local/E%3A%2Fdocs%2Fassets%2Fa.png');expect(sequenceToMermaid('A->B: Hi')).toContain('A->>B: Hi');expect(flowToMermaid('a=>start: Start\nb=>end: End\na->b')).toContain('a --> b');});
  it('loads file URLs, encoded paths, HTML images and document image roots consistently',()=>{expect(assetUrl('file:///E:/images/a%20b.png')).toBe('opentypora-asset://local/E%3A%2Fimages%2Fa%20b.png');const html=renderMarkdown('---\ntypora-root-url: E:/images\n---\n\n<img src="a%20b.png">\n\n![test](<file:///E:/images/a%20b.png>)',DEFAULT_SETTINGS,{path:'E:/docs/a.md'});expect(html).toContain('opentypora-asset://local/E%3A%2Fimages%2Fa%20b.png');expect((html.match(/<img/g)||[]).length).toBe(2);});
  it('recognizes both LaTeX delimiters inline and preserves a single numbered sequence across fence kinds',()=>{const html=renderMarkdown('\\(x+y\\) 与 \\[x-y\\]。\n\n$$\nx\n$$\n\n```math\ny\n```',DEFAULT_SETTINGS);const host=document.createElement('div');host.innerHTML=html;expect(host.querySelectorAll('[data-display=\"false\"]')).toHaveLength(2);expect([...host.querySelectorAll('[data-display=\"true\"]')].map(node=>node.getAttribute('data-equation-index'))).toEqual(['1','2']);});

});
