import {useEffect,useRef,useState} from 'react';
import type {DesktopBridge,DirectoryEntry} from '../shared/contracts';
import {relativePath} from './model';
import {useUiLanguage} from './i18n';
export function FileSummary({file,root,bridge,selected,onOpen,tabIndex}:{file:DirectoryEntry;root:string;bridge?:DesktopBridge;selected:boolean;onOpen:()=>void;tabIndex?:number}){
 const location=relativePath(file.path,root),showLocation=location!==file.name;
 const language=useUiLanguage(),ref=useRef<HTMLButtonElement>(null),[excerpt,setExcerpt]=useState(file.excerpt??''),[error,setError]=useState(''),[loaded,setLoaded]=useState(file.excerpt!==undefined);
 useEffect(()=>{setError('');setLoaded(file.excerpt!==undefined);setExcerpt(file.excerpt??'');if(file.excerpt!==undefined)return;if(!bridge)return;let active=true,started=false;const fail=(message:string)=>{if(active)setError(message);};const read=()=>{if(started)return;started=true;void bridge.readFile(file.path).then(result=>{if(!active)return;if(result.ok){setExcerpt(result.value.text.replace(/^---[\s\S]*?---\s*/,'').replace(/[#*_`>]/g,'').trim().slice(0,180));setLoaded(true);}else fail(result.error.message);}).catch(error=>fail(error instanceof Error?error.message:'读取失败'));};if(typeof IntersectionObserver==='undefined'){read();return()=>{active=false;};}const observer=new IntersectionObserver(values=>{if(values.some(value=>value.isIntersecting)){read();observer.disconnect();}},{rootMargin:'100px'});if(ref.current)observer.observe(ref.current);return()=>{active=false;observer.disconnect();};},[bridge,file.path,file.excerpt,file.modifiedAt]);
 return <button ref={ref} tabIndex={tabIndex} title={file.path} className={`file-summary ${showLocation?'has-path':''} ${selected?'selected':''}`} onClick={onOpen}><strong title={file.name} data-user-content>{file.name}</strong>{showLocation&&<small title={location} data-user-content>{location}</small>}<span title={error} data-user-content>{error?`${language==='en'?'Summary unavailable':'摘要读取失败'}：${error}`:excerpt|| (loaded?(language==='en'?'Empty document':'空文档'):(language==='en'?'Summary loads when visible':'滚动到此处时加载摘要'))}</span><time>{new Date(file.modifiedAt).toLocaleString(language==='en'?'en':'zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></button>;
}
