import {localizeUi,useUiLanguage} from './i18n';
import {HELP_EN} from './help-en';
import {useEffect,useState} from 'react';
import type {DesktopBridge,RecoveryDraft,ApplicationInfo} from '../shared/contracts';
import type {DocumentStore} from '../core/document';
import {Dialog} from './Dialog';
import {displayName} from './model';
const HELP:Record<string,{title:string;paragraphs:string[];code?:string}>= {
 'app.quickStart':{title:'开始使用 OpenTypora',paragraphs:['在单栏正文中输入 Markdown。进入段落时编辑原文，离开后显示排版。Ctrl+/ 在即时编辑与源码之间切换，两种模式共享同一份文本和撤销历史。','Ctrl+O 打开文件，Ctrl+S 保存；打开文件夹后可使用文件树、摘要列表和 Ctrl+P 快速打开。Ctrl+F 查找，Ctrl+H 替换，Ctrl+Shift+F 在当前文件夹中搜索。','F8 开关专注模式，F9 开关打字机模式。正文内容不会因切换主题或模式而改写。首次保存之前，请留意标题栏的未保存标记。']},
 'app.markdownHelp':{title:'Markdown 参考',paragraphs:['支持标题、引用、有序/无序/任务列表、链接、图片、表格、代码围栏、脚注、内容目录和 YAML 元数据。未知或不完整语法保留在原文中。','行内公式、高亮、上下标等扩展有独立开关，位于 Markdown 偏好设置。代码和公式内容按字面保留。','文内查找覆盖完整 Markdown 原文，包括标记、代码、脚注和链接地址。统计采用原文口径：每个汉字计一个词，其他语言按连续字母/数字词计数；字符使用 Unicode 字素簇，包含空白；行数是源码逻辑行。'],code:'# 标题\n\n**粗体** *斜体* `代码`\n\n- [ ] 待办事项\n\n| 列一 | 列二 |\n| --- | --- |\n| 内容 | 内容 |\n\n```mermaid\nflowchart LR\n A --> B\n```\n\n$$\nE=mc^2\n$$'},
 'app.pandocHelp':{title:'转换器与导出',paragraphs:['HTML、渲染 PDF 和图片使用桌面文档渲染；Word、Epub、LaTeX 等转换格式使用 Pandoc。LaTeX PDF 还需要兼容的 TeX 环境。依赖不就绪时导出会给出可操作的错误。','在“导出”偏好设置中指定 Pandoc 路径、管理模板、样式参考文档和参数。每个配置独立保存，可排序或删除。删除配置不会删除已生成文件。','自定义转换与后置程序通过独立可执行文件和参数数组配置。只有成功生成后才执行后置动作；正文不能通过 YAML 指定任意程序。']},
 'app.themeHelp':{title:'自定义主题',paragraphs:['内置 Github、Newsprint、Night、Pixyll 和 Whitey 五种排版体验。外观设置可指定字号、缩放和独立深色主题。','在外观设置编辑或加载 CSS。自定义样式作用于正文，界面导航和设置保持可用。#write 对应正文范围；使用主题菜单可以随时回到内置主题。','主题加载失败时保留正文并显示错误。窗口样式和界面语言需要重新启动，重启前请保存内容。'],code:'#write { line-height: 1.9; }\n#write h1 { color: #32725c; }\n#write blockquote { border-left: 3px solid #32725c; }'},
 'app.imageHelp':{title:'图片与上传',paragraphs:['插入策略包括不处理、复制到资源目录和上传。相对路径以文档位置或文档指定的图片根目录解析。未保存文档的临时资源在保存时处理。','上传适配器包括 PicGo-Core、PicGo、PicList 和自定义命令；请先配置可执行文件或服务地址。失败或旧版本返回不会覆盖新的正文。','仅打开含 YAML 上传规则的文档不会执行上传。删除磁盘图片和删除正文引用是不同操作，删除前应检查重复引用。']},
 'app.recoveryHelp':{title:'恢复与版本控制',paragraphs:['恢复草稿是本地副本，与自动保存原文件分别控制。异常退出后可以选择草稿恢复为可检查的会话，不自动覆盖磁盘文件。','外部文件修改会触发冲突保护。保存失败时应保留内存正文、撤销历史与草稿，选择重试或另存副本。','需要长期版本历史时，可将文档目录交给 Git 管理。OpenTypora 不会把未确认的外部变更静默写回。']},
 'app.changelog':{title:'版本说明',paragraphs:['本构建实现 OpenTypora 的完整工程基线和桌面模块。具体构建版本见“关于”；检查更新使用配置的本应用发行源。','发布记录以仓库 Releases 为准；这里不将未验证的能力宣称为完成。外部依赖状态会在相关操作中检查。']},
 'app.credits':{title:'鸣谢',paragraphs:['OpenTypora 使用 Electron、React、CodeMirror、Markdown-it、KaTeX、Mermaid、DOMPurify、Highlight.js 等开源组件。组件许可由其各自项目提供。','功能与交互参考 Typora；本应用使用独立实现、自有主题样式和 OpenTypora 名称。']},
 'app.privacy':{title:'隐私说明',paragraphs:['正文、资源和草稿默认存储在本机。文件内容不会因打开、阅读、主题切换或统计而上传。','图片上传、外部帮助、反馈和更新需要用户配置或执行相关动作；相应地址可能接收网络请求。匿名使用数据默认关闭，正文和凭据不属于匿名统计内容。','自定义上传或转换工具由用户配置，可能具有其自身的数据处理规则。']},
 'app.license':{title:'发行许可',paragraphs:['本仓库当前为私有项目。未声明公开授权前，使用与分发由仓库所有者决定；不借用 Typora 的购买、序列号或激活服务。','第三方组件仍遵循各自许可。发布前请检查分发物中的组件许可与资源授权。']},
 'app.about':{title:'关于 OpenTypora',paragraphs:['本地 Markdown 查看与编辑器。即时编辑、源码模式、导航和导出围绕同一份原文工作。','项目：Cjy-CN / OpenTypora。功能基线参考 Windows Typora 1.12.4 的调查记录；OpenTypora 是独立项目。']}
};
export function HelpDialog({id,bridge,store,onClose,notify}:{id:string;bridge?:DesktopBridge;store:DocumentStore;onClose:()=>void;notify:(message:string)=>void}){
 const language=useUiLanguage();const base=HELP[id]??HELP['app.quickStart'];const content=language==='en'?{...base,...(HELP_EN[id]??HELP_EN['app.quickStart'])}:base;const [info,setInfo]=useState<ApplicationInfo|null>(null),[drafts,setDrafts]=useState<RecoveryDraft[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let current=true;if(id==='app.about')void bridge?.info().then(result=>{if(current){if(result.ok)setInfo(result.value);else setError(result.error.message);}});if(id==='app.recoveryHelp'){if(!bridge){setError('草稿恢复需要桌面版。');return;}setLoading(true);void bridge.listRecovery().then(result=>{if(current){setLoading(false);if(result.ok)setDrafts(result.value);else setError(result.error.message);}});}return()=>{current=false;};},[id,bridge]);
 return localizeUi(<Dialog title={content.title} onClose={onClose}><section className="help-content">{id==='app.about'&&<div className="about-brand"><div>O</div><strong>OpenTypora</strong><span>{info?`${info.version} · ${info.platform}`:bridge?'正在读取版本信息…':'网页模式 · 未连接桌面服务'}</span></div>}{content.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{content.code&&<pre><code>{content.code}</code></pre>}{error&&<p className="workspace-error" role="alert">{error}</p>}{id==='app.recoveryHelp'&&<><h3>本地恢复草稿</h3>{loading?<p>正在读取…</p>:!drafts.length?<p className="workspace-empty">没有可恢复的草稿。</p>:drafts.map(draft=><div className="recovery-item" key={draft.id}><div><strong data-user-content>{displayName(draft.session.path)}</strong><small>{new Date(draft.savedAt).toLocaleString('zh-CN')} · {draft.session.text.length} 个 UTF-16 单元</small><p data-user-content>{draft.session.text.slice(0,100)}</p></div><button onClick={()=>{if(store.getSnapshot().dirty&&!window.confirm('当前有未保存内容。恢复前请先保存；确定放弃当前内容并查看此草稿？'))return;store.replaceSession({...draft.session,documentId:crypto.randomUUID(),path:null,dirty:true,savedVersion:-1,saveState:'idle'});notify('草稿已恢复为未命名文档。确认内容后另存，不会覆盖原文件。');onClose();}}>恢复副本</button><button onClick={()=>{if(!window.confirm('删除此恢复草稿？不会删除原文档。'))return;void bridge!.deleteRecovery(draft.id).then(result=>{if(result.ok)setDrafts(values=>values.filter(value=>value.id!==draft.id));else setError(result.error.message);});}}>删除草稿</button></div>)}</>}</section></Dialog>,language);
}
export const HELP_COMMAND_IDS=Object.keys(HELP);
