export const HELP_EN:Record<string,{title:string;paragraphs:string[]}>={
 'app.quickStart':{title:'Getting started with OpenTypora',paragraphs:['Write Markdown directly in a single document column. Edit the source of the active block and see formatted content elsewhere. Ctrl+/ switches live and source modes; both share the same text and undo history.','Ctrl+O opens a file and Ctrl+S saves it. Open a folder to browse the file tree, document summaries and Ctrl+P quick-open. Use Ctrl+F to find, Ctrl+H to replace and Ctrl+Shift+F to search the current folder.','F8 toggles focus mode and F9 toggles typewriter mode. Theme and mode changes never rewrite the document. Watch the unsaved marker until the first successful save.']},
 'app.markdownHelp':{title:'Markdown reference',paragraphs:['Use headings, quotes, ordered/unordered/task lists, links, images, tables, fenced code, footnotes, a table of contents and YAML metadata. Unknown or incomplete syntax remains in the source.','Inline math, highlighting and sub/superscript have independent switches in Markdown preferences. Code and formula contents are preserved literally.','Find searches the complete Markdown source, including markers, code, footnotes and link addresses. Each Han character counts as one word; other scripts use letter/number words. Character counts use Unicode grapheme clusters and include whitespace; lines are source lines.']},
 'app.pandocHelp':{title:'Converters and export',paragraphs:['HTML, rendered PDF and image output use the desktop renderer. Word, Epub, LaTeX and other conversion formats use Pandoc. LaTeX PDF also requires a compatible TeX environment. Missing dependencies produce actionable diagnostics.','Specify a Pandoc executable and manage profiles, reference documents and arguments in Export preferences. Profiles are independent and can be reordered or deleted. Deleting a profile never deletes generated files.','Custom converters and post-actions use separate executables and argument arrays. Post-actions run only after successful output. Document YAML cannot select arbitrary programs.']},
 'app.themeHelp':{title:'Custom themes',paragraphs:['Github, Newsprint, Night, Pixyll and Whitey offer five built-in typography styles. Appearance settings control font size, zoom and an independent dark theme.','Edit CSS in Appearance or load a CSS file. Styles are scoped to the document; navigation and preferences stay usable. #write refers to the document area. Switch back to a built-in theme at any time.','Theme errors preserve the source and report a problem. Window-style changes require restarting; save unsaved work first.']},
 'app.imageHelp':{title:'Images and upload',paragraphs:['Image strategies include no processing, copying into an assets folder and uploading. Relative paths resolve against the document or its configured image root. Temporary assets for untitled documents are handled on save.','Upload adapters include PicGo-Core, PicGo, PicList and custom commands. Configure the executable or service endpoint first. Failed or stale upload responses never replace newer source edits.','Opening a document with YAML upload rules never uploads anything. Deleting an image file differs from deleting its source reference; check repeated references before deleting files.']},
 'app.recoveryHelp':{title:'Recovery and version control',paragraphs:['Recovery drafts are local copies controlled separately from automatic saving. After a crash, review a draft before saving it; recovery never silently overwrites the disk file.','External file changes trigger conflict protection. Save failures should preserve memory text, undo history and drafts. Retry or save a separate copy.','For longer version history, manage your document folder with Git. OpenTypora does not silently write unconfirmed external changes.']},
 'app.changelog':{title:'Release notes',paragraphs:['This build contains the OpenTypora engineering baseline and desktop modules. The actual build version is shown in About. Update checks use the configured OpenTypora release source.','Repository Releases are the authoritative release record. Dependency status is checked by the related operation; unverified capabilities are not claimed as completed here.']},
 'app.credits':{title:'Credits',paragraphs:['OpenTypora uses Electron, React, CodeMirror, Markdown-it, KaTeX, Mermaid, DOMPurify, Highlight.js and other open-source components. Each component retains its own license.','OpenTypora uses an independent implementation and original theme styles.']},
 'app.privacy':{title:'Privacy',paragraphs:['Documents, assets and drafts remain local by default. Opening, reading, theme changes and statistics do not upload document text.','Image uploads, external help, feedback and update checks require configured services or related user actions. Anonymous usage data is off by default and excludes document text and credentials.','Custom upload and conversion tools are configured by the user and may have their own data handling policies.']},
 'app.license':{title:'Distribution license',paragraphs:['This repository is currently a private project. Until public licensing is declared, usage and distribution are controlled by the repository owner.','Third-party components remain subject to their respective licenses. Review component and asset licenses before distribution.']},
 'app.about':{title:'About OpenTypora',paragraphs:['A local Markdown reader and editor. Live editing, source mode, navigation and export share one source document.','Project: Cjy-CN / OpenTypora.']}
};
