import {Children,cloneElement,createContext,isValidElement,useContext,useEffect,useState,type ReactNode,type ReactElement} from 'react';
import type {DesktopBridge} from '../shared/contracts';
import {resolveUiLanguage} from '../shared/ui-language';
import {COMMANDS} from '../shared/command-catalog';
import {SETTING_LABELS} from './settings-labels';
export const UiLanguageContext=createContext('zh-CN');
export const useUiLanguage=()=>useContext(UiLanguageContext);
const browserLanguages=()=>navigator.languages?.length?[...navigator.languages]:[navigator.language];
export function useResolvedUiLanguage(preference:string,bridge?:DesktopBridge){
 const [languages,setLanguages]=useState(browserLanguages);
 useEffect(()=>{
  let active=true,revision=0;
  const refresh=async()=>{
   const request=++revision;let next=browserLanguages();
   try{const result=await bridge?.info?.();if(result?.ok&&result.value.systemLanguages?.length)next=result.value.systemLanguages;}catch{/* Browser preferences remain available when desktop information cannot be read. */}
   if(active&&request===revision)setLanguages(next);
  };
  void refresh();window.addEventListener('languagechange',refresh);window.addEventListener('focus',refresh);
  return()=>{active=false;window.removeEventListener('languagechange',refresh);window.removeEventListener('focus',refresh);};
 },[bridge]);
 return resolveUiLanguage(preference,languages);
}
const humanize=(id:string)=>id.split('.').at(-1)!.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/^./,value=>value.toUpperCase());
const COMMAND_EN:Record<string,string>={'selection.all':'Select all','selection.block':'Select block','selection.lineOrSentence':'Select line or sentence','selection.formatted':'Select formatted text','selection.word':'Select word','selection.documentStart':'Go to document start','selection.selection':'Go to selection','selection.documentEnd':'Go to document end','selection.lineStart':'Go to line start','selection.lineEnd':'Go to line end','table.create':'Insert table','code.create':'Code block','math.create':'Math block','image.insert':'Insert image','image.root':'Image root folder','image.settings':'Image settings','math.settings':'Math settings','view.source':'Source mode','view.focus':'Focus mode','view.typewriter':'Typewriter mode','view.actualSize':'Actual size','app.about':'About OpenTypora','file.reveal':'Show in Explorer','file.revealInSidebar':'Reveal in sidebar','file.properties':'File properties','file.recent':'Recent files','file.preferences':'Preferences','search.find':'Find','search.next':'Next match','search.previous':'Previous match','search.replace':'Replace','search.replaceAll':'Replace all'};
const SETTINGS_EN:Record<string,string>={
 'file.startup':'On startup','file.outlineFold':'Allow outline folding','file.extension':'Default file extension','file.autoSave':'Automatically save original files','file.saveOnSwitch':'Save previous document when switching','file.recovery':'Save recovery drafts','file.history':'Remember files and folders','file.dropFolder':'Dropped folders','file.dropMarkdown':'Dropped Markdown files','file.dropImport':'Dropped importable files',
 'editor.indent':'Default indentation spaces','editor.alignIndent':'Align indentation','editor.matchBrackets':'Auto-pair brackets and quotes','editor.matchMarkdown':'Auto-pair Markdown markers','editor.emoji':'Complete emoji names','editor.showActiveSource':'Show Markdown source of active block','editor.copyMarkdown':'Use Markdown source when copying plain text','editor.copyWholeLine':'Copy or cut whole line without a selection','editor.lineEnding':'Default new-file line endings','editor.finalNewline':'Add a final newline when saving','editor.spellLanguage':'Spell-check language','editor.typewriterCenter':'Always center the typewriter cursor',
 'image.strategy':'Action when inserting images','image.folder':'Image assets folder','image.applyLocal':'Apply strategy to local images','image.applyRemote':'Apply strategy to remote images','image.yamlUpload':'Allow YAML upload rules','image.relative':'Prefer relative image paths','image.prefixDot':'Prefix relative paths with ./','image.escapeUrl':'Escape image URLs','image.uploader':'Image upload service','image.uploadExecutable':'Upload executable','image.uploadArgs':'Upload command arguments','image.uploadEndpoint':'Upload service endpoint',
 'markdown.strict':'Strict Markdown syntax','markdown.headingStyle':'Heading style','markdown.unorderedMarker':'Unordered list marker','markdown.orderedMarker':'Ordered list numbering','markdown.autoLink':'Recognize automatic links','markdown.inlineMath':'Enable inline math','markdown.sub':'Enable subscript','markdown.sup':'Enable superscript','markdown.highlight':'Enable highlighting','markdown.alerts':'Enable GFM alerts','markdown.diagrams':'Enable flowcharts, sequence diagrams and Mermaid','markdown.smartMode':'Smart punctuation timing','markdown.smartQuotes':'Smart quotes','markdown.smartDashes':'Smart dashes','markdown.unicodePunctuation':'Recognize Unicode punctuation',
 'code.lineNumbers':'Code block line numbers','code.wrap':'Wrap code blocks','code.shiftTab':'Auto-indent with Shift+Tab','code.indent':'Code indentation spaces','code.defaultLanguage':'Default code language','math.latexDelimiters':'Recognize LaTeX delimiters','math.fenced':'Recognize math fences','math.newline':'Allow math newline commands','math.physics':'Enable Physics macros','math.numbering':'Automatically number equations','math.htmlRepresentation':'Math format in unstyled HTML',
 'text.firstIndent':'Indent first paragraph line','text.showBr':'Show HTML br line breaks','text.preserveSpaces':'Preserve consecutive spaces while editing','text.preserveBreaks':'Preserve single line breaks while editing','export.preserveSpaces':'Preserve consecutive spaces in exports','export.preserveBreaks':'Preserve single line breaks in exports','export.directory':'Default export folder','export.pandocPath':'Pandoc executable path','export.openFolder':'Open export folder by default','export.profiles':'Export profiles','export.selectedProfile':'Selected export profile',
 'appearance.windowStyle':'Window style','appearance.fontSize':'Custom body font size','appearance.autoFont':'Use the theme font size','appearance.zoom':'Zoom percentage','appearance.ctrlWheel':'Zoom with Ctrl+wheel','appearance.statusBar':'Show status bar','appearance.readingSpeed':'Reading speed (words/minute)','appearance.theme':'Document theme','appearance.darkTheme':'Dark-mode theme','appearance.independentDark':'Use an independent dark theme','appearance.customCss':'Custom theme CSS',
 'general.language':'Interface language','general.autoUpdate':'Automatically check for updates','general.developmentUpdates':'Include development releases','general.debug':'Enable diagnostics','general.telemetry':'Send anonymous usage data','general.telemetryEndpoint':'Usage data receiver endpoint','general.serviceSource':'Release update source','general.shortcuts':'Custom keyboard shortcuts'
};
const EN:Record<string,string>={
 '新建文档':'New document','即时编辑':'Live editing','源码模式':'Source mode','切换即时编辑与源码模式':'Toggle live editing and source mode',
 ...Object.fromEntries(COMMANDS.map(command=>[command.label,COMMAND_EN[command.id]??humanize(command.id)])),...Object.fromEntries(Object.entries(SETTING_LABELS).map(([key,label])=>[label,SETTINGS_EN[key]??humanize(key)])),
 '文件':'File','编辑':'Edit','段落':'Paragraph','格式':'Format','视图':'View','主题':'Themes','帮助':'Help','编辑器':'Editor','图像':'Images','导出':'Export','外观':'Appearance','通用':'General','大纲':'Outline','搜索':'Search','高级配置':'Advanced configuration','选择':'Selection','范围':'Ranges','文本':'Text','代码':'Code','公式':'Math','警告框':'Alerts','表格':'Table','源码':'Source','退出源码':'Exit source mode','〈/〉 源码':'〈/〉 Source','专注':'Focus','打字机':'Typewriter',
 '导出格式':'Export formats','没有导出配置，请在偏好设置中添加。':'No export profiles. Add one in Preferences.',
 '过滤文件名':'Filter filenames','过滤文件名…':'Filter filenames…','清除文件名过滤':'Clear filename filter','搜索文件内容':'Search file contents',
 '主菜单':'Main menu','导航侧边栏':'Navigation sidebar','偏好设置':'Preferences','关闭对话框':'Close dialog','隐藏侧边栏':'Hide sidebar','显示侧边栏':'Show sidebar','调整侧边栏宽度':'Resize sidebar','文档结构':'Document structure','还没有标题':'No headings yet','正在更新结构…':'Updating outline…','输入 # 标题开始组织文档':'Start organizing your document with # headings','大纲导航不会改变文档内容':'Outline navigation never changes your source',
 '未命名':'Untitled','未保存文档':'Unsaved document','未保存':'Unsaved','已保存':'Saved','只读':'Read-only','正在保存…':'Saving…','保存失败':'Save failed','外部冲突':'External changes','打开文件夹':'Open folder','树形视图':'File tree','摘要列表':'Document list','刷新目录':'Refresh folder','＋ 新建文档':'+ New document','正在读取文件夹…':'Reading folder…','文件夹为空':'The folder is empty','正在读取…':'Reading…','正在索引文件…':'Indexing files…','没有最近记录':'No recent files','没有匹配文件':'No matching files','先打开文件夹以检索文档':'Open a folder to find documents',
 '跨文件搜索':'Search across files','文内查找':'Find in document','搜索文件名或路径':'Find a filename or path','在当前文件夹搜索…':'Search the current folder…','查找完整 Markdown 原文…':'Search the complete Markdown source…','输入文件名或路径…':'Enter a filename or path…','上一个匹配':'Previous match','下一个匹配':'Next match','关闭查找':'Close search','替换':'Replace','替换为':'Replace with','替换为…（正则支持 $1）':'Replace with… (regex supports $1)','替换当前':'Replace current','全部替换':'Replace all','区分大小写':'Match case','全词匹配':'Whole word','正则表达式':'Regular expression','表达式错误':'Expression error','正在搜索…':'Searching…','取消':'Cancel',
 '字数统计':'Document statistics','分钟预计阅读时间':'minutes estimated reading time','全文词数':'Total words','字符（含空白）':'Characters including whitespace','字符（不含空白）':'Characters without whitespace','源码逻辑行':'Source lines','选区词数':'Selected words','选区字符':'Selected characters','阅读速度':'Reading speed','词/分钟':'words/minute','个标题':'headings','恢复默认':'Restore defaults','正在后台统计当前文档…':'Counting the current document in the background…','正在统计…':'Counting…','统计不可用':'Statistics unavailable',
 '每个汉字计一词，其他语言按字母/数字词计数；字符按 Unicode 字素簇统计。正文标记与代码按原文计入。':'Each Han character counts as one word; other scripts use letter/number words. Characters are Unicode grapheme clusters. Markdown markers and code are included.',
 '打开文档文件夹':'Open a document folder','在侧边栏浏览和搜索':'Browse and search local','你的本地 Markdown 文档':'Markdown documents in the sidebar','选择文件夹':'Choose folder','搜索设置':'Search settings','搜索设置…':'Search settings…','设置与正文独立。':'Settings are separate from document text.','标有“重启”的选项在下次启动生效。':'Items marked Restart take effect on the next launch.','重启':'Restart','文件设置':'File settings','编辑器设置':'Editor settings','图像设置':'Image settings','Markdown设置':'Markdown settings','导出设置':'Export settings','外观设置':'Appearance settings','通用设置':'General settings',
 '全局设置 · 即时生效':'Global · Immediate','全局设置 · 重新启动后生效':'Global · After restart','导出设置 · 即时生效':'Export · Immediate','恢复默认值':'Restore default value','查看并恢复草稿':'View and restore drafts','清除历史':'Clear history','加载 CSS 文件':'Load CSS file','加载自定义主题文件':'Load custom theme file','打开主题目录':'Open themes folder','获取主题':'Get themes','检查更新':'Check for updates','资源管理器集成':'Windows Explorer integration','发行许可':'Distribution license','开发者工具':'Developer tools','重置警告提示':'Reset warning prompts','自定义快捷键':'Custom shortcuts','查找快捷键命令':'Find shortcut command','查找命令…':'Find a command…','按下组合键或输入':'Press a shortcut or type',
 '校验并应用':'Validate and apply','备份并恢复默认':'Back up and restore defaults','打开配置文件':'Open configuration file','高级配置 JSON':'Advanced configuration JSON','配置与界面使用相同的校验规则。':'Configuration uses the same validation as the interface.','字段使用与界面相同的校验规则。应用前可检查和修改；非法配置不会覆盖当前值。':'All fields share the interface validation rules. Review before applying; invalid configuration never overwrites current settings.',
 '导出配置':'Export profiles','新增导出模板':'New export template','＋ 添加配置':'+ Add profile','恢复内置配置':'Restore built-in profiles','配置名称':'Profile name','输出后缀':'Output extension','导出主题':'Export theme','允许 YAML 覆盖排版':'Allow YAML layout overrides','纸张尺寸（A4、A3、Letter）':'Paper size (A4, A3, Letter)','边距（如 20mm）':'Margins (for example 20mm)','一级标题前分页':'Page break before level-one headings','页首 HTML':'Header HTML','页尾 HTML':'Footer HTML','作者':'Author','额外 HTML':'Extra HTML','head 附加内容':'Additional head content','body 附加内容':'Additional body content','保留大纲侧栏':'Retain outline sidebar','图片宽度（像素）':'Image width (pixels)','图片质量（1–100）':'Image quality (1–100)','正文字号（像素）':'Body font size (pixels)','样式参考文件路径':'Reference style document','目标格式 / 方言':'Target format / dialect','转换模板路径':'Converter template path','转换器可执行文件':'Converter executable','转换参数（JSON 数组）':'Converter arguments (JSON array)','导出后打开文件':'Open exported file','导出后打开目录':'Open export folder','成功后运行程序':'Run program after success','后置程序参数（JSON 数组）':'Post-action arguments (JSON array)','删除':'Delete','使用此配置导出':'Export using this profile','选择格式':'Choose format','没有配置，请从模板添加。':'No profiles. Add one from a template.',
 'PDF（文档渲染）':'PDF (document renderer)','PDF（LaTeX / Pandoc）':'PDF (LaTeX / Pandoc)','HTML（带样式）':'HTML (with styles)','HTML（无样式）':'HTML (without styles)','图片':'Image','Markdown（其他方言）':'Markdown (other dialect)','Native（Pandoc）':'Native (Pandoc)','Pandoc 转换':'Pandoc conversion','自定义转换':'Custom converter',
 '跟随系统':'Follow system','跟随系统时，中文使用简体中文，其他语言使用英语；手动选择立即生效。':'Follow the system: Chinese uses Simplified Chinese; other languages use English. Manual selections apply immediately.',
 '新建空白文档':'New blank document','恢复上次会话':'Restore previous session','打开':'Open','忽略':'Ignore','插入正文':'Insert into document','转换导入':'Convert and import','无特殊操作':'No special action','复制到资源目录':'Copy to assets folder','上传图片':'Upload image','PicGo-Core（命令行）':'PicGo-Core (command line)','PicGo（应用）':'PicGo (application)','自定义':'Custom','ATX（# 标题）':'ATX (# heading)','Setext（下划线标题）':'Setext (underlined heading)','递增编号：1、2、3':'Increment: 1, 2, 3','固定编号：1、1、1':'Repeat: 1, 1, 1','输入时转换':'Convert during input','渲染时转换':'Convert during rendering','经典窗口':'Classic window','一体式窗口':'Integrated window','简体中文':'Simplified Chinese','SVG 图形':'SVG graphic','LaTeX 原文':'LaTeX source','Unix（LF）':'Unix (LF)','Windows（CRLF）':'Windows (CRLF)',
 '草稿恢复需要桌面版。':'Draft recovery requires the desktop application.','没有可恢复的草稿。':'No recovery drafts.','本地恢复草稿':'Local recovery drafts','恢复副本':'Restore a copy','删除草稿':'Delete draft','关于 OpenTypora':'About OpenTypora','本地 Markdown 查看与编辑器。即时编辑、源码模式、导航和导出围绕同一份原文工作。':'A local Markdown reader and editor. Live editing, source mode, navigation and export share one source document.','网页模式 · 未连接桌面服务':'Web mode · Desktop service unavailable','正在读取版本信息…':'Reading version information…',
 '自动写入已有路径；未命名文档仍需首次保存。恢复草稿与自动覆盖分别控制。':'Automatically writes existing files. Untitled documents still require a first save. Recovery drafts are controlled separately.','保存恢复副本，不覆盖原文件。':'Save recovery copies without overwriting the original file.','关闭后停止记录新历史；已有历史可单独清除。':'Stops adding new history. Existing history can be cleared separately.','仅作为新文件的默认值；已打开文件继续保留原换行。':'Default for new files only; opened files preserve their line endings.','保存时生效；换行规则不会由主题或模式切换修改。':'Applied on save. Theme and mode changes never alter line endings.','auto 为自动；可填 en-US、zh-CN 等语言标记。':'Use auto, or a language tag such as en-US or zh-CN.','支持 ${filename} 变量，目录相对文档路径。':'Supports the ${filename} variable; the folder is relative to the document.','仅在用户插入或上传动作中执行，打开文档不会自动上传。':'Runs only for insertion or upload actions; opening a document never uploads images.','JSON 字符串数组；通过参数传递文件路径，避免 shell 拼接。':'JSON string array. File paths are passed as arguments.','默认关闭；没有接收端时不会发送，不包含正文。':'Off by default. No data is sent without a receiver; document text is excluded.','为已注册命令设置键位，冲突时必须先修正。':'Bind registered commands; resolve conflicts before applying.','只作用于正文，界面菜单与设置仍使用应用样式。':'Applies only to the document; menus and settings keep application styles.','留空时选择输出路径。':'Leave blank to select an output path.','留空时自动检测。':'Leave blank for automatic detection.','依赖公式渲染器提供的 Physics 宏支持。':'Requires Physics macro support from the math renderer.',
 '↑ ↓ 选择 · Enter 打开 · Esc 取消 ':'↑ ↓ select · Enter open · Esc cancel ', ' · 正在索引':' · Indexing','开始使用 OpenTypora':'Getting started with OpenTypora','Markdown 参考':'Markdown reference','转换器与导出':'Converters and export','自定义主题':'Custom themes','图片与上传':'Images and upload','恢复与版本控制':'Recovery and version control','版本说明':'Release notes','鸣谢':'Credits','隐私说明':'Privacy',
 '从模板创建独立配置。参数支持 $':'Create independent profiles from templates. Arguments support $','；依赖缺失由导出诊断报告。':'; missing dependencies are reported by export diagnostics.'
};
export function translateUi(text:string,language:string):string{
 if(language!=='en')return text;const trimmed=text.trim();if(EN[trimmed])return text.replace(trimmed,EN[trimmed]);
 if(/^重置/.test(text))return `Reset ${translateUi(text.slice(2),language)}`;
 if(/^\d+ 个标题$/.test(text))return text.replace('个标题','headings');
 if(/^\d+ 处匹配$/.test(text))return text.replace('处匹配','matches');
 if(/^搜索“.*”$/.test(text))return `Search: ${text.slice(3,-1)}`;
 if(/^选中 \d+ 词 · /.test(text))return text.replace('选中','Selected').replace('词','words');
 if(/词$/.test(text))return text.replace(/词$/,'words');
 if(/ 个 UTF-16 单元$/.test(text))return text.replace('个 UTF-16 单元','UTF-16 units');
 return text;
}
/** Translate a React UI tree without modifying user documents, input values, code, or the editor. */
export function localizeUi(node:ReactNode,language:string):ReactNode{
 if(language!=='en')return node;
 if(typeof node==='string')return translateUi(node,language);
 if(!isValidElement(node))return Array.isArray(node)?Children.map(node,child=>localizeUi(child,language)):node;
 const element=node as ReactElement<Record<string,unknown>>,props=element.props;
 if(props['data-user-content']||typeof props.className==='string'&&/\b(workspace-document|document-title|tree-node|outline-entry|file-search-results)\b/.test(props.className)||element.type==='pre'||element.type==='code')return element;
 const translated:Record<string,unknown>={};for(const key of ['title','placeholder','aria-label'])if(typeof props[key]==='string')translated[key]=translateUi(props[key] as string,language);
 if(props.children!==undefined)translated.children=Children.map(props.children as ReactNode,child=>localizeUi(child,language));
 return cloneElement(element,translated);
}
