import type { SettingsKey } from '../shared/settings';
export const SETTING_LABELS:Record<string,string>={
 'file.startup':'启动时打开','file.outlineFold':'允许折叠大纲','file.extension':'默认文件后缀','file.autoSave':'自动保存原文件','file.saveOnSwitch':'切换文档时保存上一文件','file.recovery':'自动保存恢复草稿','file.history':'记录文件和文件夹历史','file.dropFolder':'拖入文件夹','file.dropMarkdown':'拖入 Markdown 文件','file.dropImport':'拖入可导入文件',
 'editor.indent':'默认缩进空格数','editor.alignIndent':'对齐缩进','editor.matchBrackets':'自动匹配括号与引号','editor.matchMarkdown':'自动匹配 Markdown 标记','editor.emoji':'自动完成表情名称','editor.showActiveSource':'显示当前块 Markdown 源码','editor.copyMarkdown':'纯文本复制时使用 Markdown 源码','editor.copyWholeLine':'无选区时复制或剪切整行','editor.lineEnding':'新文件默认换行','editor.finalNewline':'保存时在文末添加换行','editor.spellLanguage':'拼写检查语言','editor.typewriterCenter':'打字机模式始终居中',
 'image.strategy':'插入图片时的操作','image.folder':'图片资源目录','image.applyLocal':'对本地图片应用策略','image.applyRemote':'对网络图片应用策略','image.yamlUpload':'允许 YAML 指定自动上传','image.relative':'优先使用相对路径','image.prefixDot':'相对路径添加 ./','image.escapeUrl':'插入时转义图片 URL','image.uploader':'图片上传服务','image.uploadExecutable':'上传工具可执行文件','image.uploadArgs':'上传命令参数','image.uploadEndpoint':'图片上传服务地址',
 'markdown.strict':'严格 Markdown 语法','markdown.headingStyle':'标题标记风格','markdown.unorderedMarker':'无序列表标记','markdown.orderedMarker':'有序列表编号','markdown.autoLink':'自动识别链接','markdown.inlineMath':'启用行内数学公式','markdown.sub':'启用下标','markdown.sup':'启用上标','markdown.highlight':'启用高亮','markdown.alerts':'启用 GFM 警告框','markdown.diagrams':'启用流程图、序列图和 Mermaid','markdown.smartMode':'智能标点转换时机','markdown.smartQuotes':'使用智能引号','markdown.smartDashes':'使用智能破折号','markdown.unicodePunctuation':'解析 Unicode 标点',
 'code.lineNumbers':'显示代码块行号','code.wrap':'代码块自动换行','code.shiftTab':'Shift+Tab 自动调整缩进','code.indent':'代码块缩进空格数','code.defaultLanguage':'默认代码语言','math.latexDelimiters':'识别 LaTeX 公式分隔符','math.fenced':'识别数学代码围栏','math.newline':'公式中支持换行命令','math.physics':'启用 Physics 宏','math.numbering':'公式自动编号','math.htmlRepresentation':'无样式 HTML 中的公式格式',
 'text.firstIndent':'正文首行缩进','text.showBr':'显示 HTML br 换行','text.preserveSpaces':'编辑时保留连续空格','text.preserveBreaks':'编辑时保留单换行符','export.preserveSpaces':'导出时保留连续空格','export.preserveBreaks':'导出时保留单换行符','export.directory':'默认导出目录','export.pandocPath':'Pandoc 可执行文件路径','export.openFolder':'导出后默认打开目录',
 'appearance.windowStyle':'窗口样式','appearance.fontSize':'自定义正文字号','appearance.autoFont':'使用主题自动字号','appearance.zoom':'界面缩放百分比','appearance.ctrlWheel':'Ctrl+滚轮缩放','appearance.statusBar':'显示状态栏','appearance.readingSpeed':'阅读速度（词/分钟）','appearance.theme':'正文主题','appearance.darkTheme':'深色模式主题','appearance.independentDark':'独立设置深色主题','appearance.customCss':'自定义主题 CSS',
 'general.language':'界面语言','general.autoUpdate':'自动检查更新','general.developmentUpdates':'接收开发版本更新','general.debug':'启用诊断模式','general.telemetry':'发送匿名使用数据','general.telemetryEndpoint':'匿名使用数据接收端地址','general.serviceSource':'发行更新服务地址','general.shortcuts':'自定义快捷键绑定','export.profiles':'导出配置模板','export.selectedProfile':'当前导出配置'
};
export const CHOICE_LABELS:Record<string,string>={new:'新建空白文档',last:'恢复上次会话',open:'打开',ignore:'忽略',insert:'插入正文',import:'转换导入',none:'无特殊操作',copy:'复制到资源目录',upload:'上传图片','picgo-core':'PicGo-Core（命令行）',picgo:'PicGo（应用）',piclist:'PicList',custom:'自定义',atx:'ATX（# 标题）',setext:'Setext（下划线标题）',increment:'递增编号：1、2、3',one:'固定编号：1、1、1',input:'输入时转换',render:'渲染时转换',classic:'经典窗口',integrated:'一体式窗口',github:'Github',newsprint:'Newsprint',night:'Night',pixyll:'Pixyll',whitey:'Whitey','zh-CN':'简体中文',en:'English',svg:'SVG 图形',mathml:'MathML',source:'LaTeX 原文',LF:'Unix（LF）',CRLF:'Windows（CRLF）'};
export const SETTING_HELP:Partial<Record<SettingsKey,string>>={
 'file.autoSave':'自动写入已有路径；未命名文档仍需首次保存。恢复草稿与自动覆盖分别控制。','file.recovery':'保存恢复副本，不覆盖原文件。','file.history':'关闭后停止记录新历史；已有历史可单独清除。',
 'editor.lineEnding':'仅作为新文件的默认值；已打开文件继续保留原换行。','editor.finalNewline':'保存时生效；换行规则不会由主题或模式切换修改。','editor.spellLanguage':'auto 为自动；可填 en-US、zh-CN 等语言标记。','image.folder':'支持 ${filename} 变量，目录相对文档路径。','image.yamlUpload':'仅在用户插入或上传动作中执行，打开文档不会自动上传。','image.uploadArgs':'JSON 字符串数组；通过参数传递文件路径，避免 shell 拼接。','general.telemetry':'默认关闭；没有接收端时不会发送，不包含正文。','general.shortcuts':'为已注册命令设置键位，冲突时必须先修正。','appearance.customCss':'只作用于正文，界面菜单与设置仍使用应用样式。','export.directory':'留空时选择输出路径。','export.pandocPath':'留空时自动检测。','math.physics':'依赖公式渲染器提供的 Physics 宏支持。'
};
