// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot} from 'react-dom/client';
import {describe,it,expect,vi} from 'vitest';
import {FileTreeNavigation,OutlineNavigation} from './VirtualNavigation';
(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
describe('large accessible navigation',()=>{
 it('renders a bounded directory window and opens the last item with keyboard navigation',async()=>{const container=document.createElement('div');document.body.append(container);const root=createRoot(container),onOpen=vi.fn();const entries=Array.from({length:10000},(_,index)=>({path:`C:/test/note-${index}.md`,name:`note-${index}.md`,directory:false,modifiedAt:0,size:0}));await act(()=>root.render(createElement(FileTreeNavigation,{entries,cache:{},expanded:new Set<string>(),selectedPath:null,onToggle:vi.fn(),onOpen})));expect(container.querySelectorAll('[role=treeitem]').length).toBeLessThan(50);const tree=container.querySelector('[role=tree]')!;await act(()=>{tree.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));});await act(()=>{tree.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));});expect(onOpen).toHaveBeenCalledWith('C:/test/note-9999.md');expect(container.querySelectorAll('[role=treeitem]').length).toBeLessThan(50);await act(()=>root.unmount());container.remove();});
 it('folds descendants without changing outline source positions',async()=>{const container=document.createElement('div');document.body.append(container);const root=createRoot(container),onNavigate=vi.fn();const items=[{id:'p',title:'Parent',level:1,from:0,to:8,parent:null},{id:'c',title:'Child',level:2,from:10,to:20,parent:'p'},{id:'s',title:'Sibling',level:1,from:30,to:40,parent:null}];await act(()=>root.render(createElement(OutlineNavigation,{items,folded:new Set(['p']),allowFold:true,onFold:vi.fn(),onNavigate})));expect(container.querySelectorAll('[role=treeitem]').length).toBe(2);const tree=container.querySelector('[role=tree]')!;await act(()=>{tree.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}));});await act(()=>{tree.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));});expect(onNavigate).toHaveBeenCalledWith(30);await act(()=>root.unmount());container.remove();});
});
