import {useEffect,useLayoutEffect,useMemo,useRef,useState,type KeyboardEvent} from 'react';
import type {DirectoryEntry,DesktopBridge} from '../shared/contracts';
import {isMarkdown,type OutlineItem} from './model';
import {useUiLanguage} from './i18n';
import {virtualRange,FILE_SUMMARY_ROW_HEIGHT,NAVIGATION_ROW_HEIGHT} from './virtual-list';
import {FileSummary} from './FileSummary';
function useRows(total:number,rowHeight:number){
 const ref=useRef<HTMLDivElement>(null),[scroll,setScroll]=useState(0),[height,setHeight]=useState(500),[active,setActive]=useState(0);const range=virtualRange(total,scroll,height,rowHeight);
 useLayoutEffect(()=>{const measure=()=>setHeight(ref.current?.clientHeight||500);measure();if(typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(measure);if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const move=(index:number)=>{const next=Math.max(0,Math.min(total-1,index));setActive(next);const element=ref.current;if(element&&(next*rowHeight<element.scrollTop||next*rowHeight+rowHeight>element.scrollTop+height))element.scrollTop=Math.max(0,next*rowHeight-height/2);if(element)setScroll(element.scrollTop);};
 useLayoutEffect(()=>{setActive(index=>Math.max(0,Math.min(total-1,index)));const element=ref.current;if(element){element.scrollTop=Math.min(element.scrollTop,Math.max(0,total*rowHeight-height));setScroll(element.scrollTop);}},[total,rowHeight,height]);
 return {ref,range,height,active,move,onScroll:()=>setScroll(ref.current?.scrollTop??0)};
}
export function OutlineNavigation({items,currentId,folded,allowFold,onFold,onNavigate}:{items:OutlineItem[];currentId?:string;folded:Set<string>;allowFold:boolean;onFold:(id:string)=>void;onNavigate:(position:number)=>void}){
 const language=useUiLanguage(),children=useMemo(()=>new Set(items.map(item=>item.parent).filter(Boolean)),[items]);
 const visible=useMemo(()=>{let hiddenLevel:number|null=null;return items.filter(item=>{if(hiddenLevel!==null&&item.level>hiddenLevel)return false;hiddenLevel=folded.has(item.id)&&allowFold?item.level:null;return true;});},[items,folded,allowFold]);
 const rows=useRows(visible.length,NAVIGATION_ROW_HEIGHT);useEffect(()=>{const index=visible.findIndex(item=>item.id===currentId);if(index>=0)rows.move(index);},[currentId,visible]);
 const keydown=(event:KeyboardEvent)=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();rows.move(rows.active+(event.key==='ArrowDown'?1:-1));}else if(event.key==='Home'||event.key==='End'){event.preventDefault();rows.move(event.key==='Home'?0:visible.length-1);}else if(event.key==='Enter'){event.preventDefault();if(visible[rows.active])onNavigate(visible[rows.active].from);}else if(event.key==='ArrowLeft'||event.key==='ArrowRight'){const item=visible[rows.active];if(item&&allowFold&&children.has(item.id)&&folded.has(item.id)===(event.key==='ArrowRight')){event.preventDefault();onFold(item.id);}}};
 return <div ref={rows.ref} className="outline-list virtual-navigation" role="tree" tabIndex={0} aria-label={language==='en'?'Document outline':'文档大纲'} aria-activedescendant={visible[rows.active]?.id} onScroll={rows.onScroll} onKeyDown={keydown}><div style={{height:visible.length*NAVIGATION_ROW_HEIGHT,position:'relative'}}>{visible.slice(rows.range.start,rows.range.end).map((item,offset)=><div id={item.id} data-active={rows.active===rows.range.start+offset} role="treeitem" aria-level={item.level} aria-selected={item.id===currentId} aria-expanded={children.has(item.id)?!folded.has(item.id):undefined} className={`outline-entry ${currentId===item.id?'selected':''}`} key={item.id} style={{position:'absolute',top:(rows.range.start+offset)*NAVIGATION_ROW_HEIGHT,left:0,right:0,height:NAVIGATION_ROW_HEIGHT,paddingLeft:12+(item.level-1)*13}}>{allowFold&&children.has(item.id)?<button tabIndex={-1} aria-label={`${language==='en'?(folded.has(item.id)?'Expand':'Collapse'):(folded.has(item.id)?'展开':'折叠')} ${item.title}`} className="outline-chevron" onClick={()=>onFold(item.id)}>{folded.has(item.id)?'▸':'▾'}</button>:<span className="outline-dot"/>}<button tabIndex={-1} title={item.title} onClick={()=>onNavigate(item.from)}>{item.title}</button></div>)}</div></div>;
}
interface TreeRow {entry:DirectoryEntry;depth:number;loading?:boolean}
export function FileTreeNavigation({entries,cache,expanded,selectedPath,onToggle,onOpen}:{entries:DirectoryEntry[];cache:Record<string,DirectoryEntry[]>;expanded:Set<string>;selectedPath:string|null;onToggle:(path:string)=>void;onOpen:(path:string)=>void}){
 const language=useUiLanguage();const flat=useMemo(()=>{const result:TreeRow[]=[];const visit=(values:DirectoryEntry[],depth:number)=>{for(const entry of values){if(!entry.directory&&!isMarkdown(entry.path))continue;result.push({entry,depth});if(entry.directory&&expanded.has(entry.path)){if(cache[entry.path])visit(cache[entry.path],depth+1);else result.push({entry:{...entry,path:entry.path+'::loading',name:language==='en'?'Reading…':'正在读取…'},depth:depth+1,loading:true});}}};visit(entries,0);return result;},[entries,cache,expanded,language]);
 const rows=useRows(flat.length,NAVIGATION_ROW_HEIGHT),open=(row:TreeRow)=>{if(!row.loading){if(row.entry.directory)onToggle(row.entry.path);else onOpen(row.entry.path);}};
 const keydown=(event:KeyboardEvent)=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();rows.move(rows.active+(event.key==='ArrowDown'?1:-1));}else if(event.key==='Home'||event.key==='End'){event.preventDefault();rows.move(event.key==='Home'?0:flat.length-1);}else if(event.key==='Enter'){event.preventDefault();if(flat[rows.active])open(flat[rows.active]);}else if(event.key==='ArrowLeft'||event.key==='ArrowRight'){const row=flat[rows.active];if(row?.entry.directory&&!row.loading&&expanded.has(row.entry.path)===(event.key==='ArrowLeft')){event.preventDefault();onToggle(row.entry.path);}}};
 return <div ref={rows.ref} className="virtual-file-tree virtual-navigation" role="tree" tabIndex={0} aria-activedescendant={`file-tree-row-${rows.active}`} aria-label={language==='en'?'File tree':'文件树'} onScroll={rows.onScroll} onKeyDown={keydown}><div style={{height:flat.length*NAVIGATION_ROW_HEIGHT,position:'relative'}}>{flat.slice(rows.range.start,rows.range.end).map((row,offset)=><button id={`file-tree-row-${rows.range.start+offset}`} data-active={rows.active===rows.range.start+offset} key={row.entry.path} className={`tree-entry ${selectedPath===row.entry.path?'selected':''}`} style={{position:'absolute',top:(rows.range.start+offset)*NAVIGATION_ROW_HEIGHT,left:0,right:0,height:NAVIGATION_ROW_HEIGHT,paddingLeft:14+row.depth*14}} role="treeitem" aria-level={row.depth+1} aria-selected={selectedPath===row.entry.path} aria-expanded={row.entry.directory&&!row.loading?expanded.has(row.entry.path):undefined} tabIndex={-1} title={row.entry.path} disabled={row.loading} onClick={()=>{rows.move(rows.range.start+offset);open(row);}}><span className="tree-chevron">{row.entry.directory?(expanded.has(row.entry.path)?'▾':'▸'):''}</span><span className={`file-symbol ${row.entry.directory?'folder':''}`}>{row.entry.directory?'▱':'M'}</span><span>{row.entry.name}</span></button>)}</div></div>;
}
export function FileListNavigation({entries,root,bridge,selectedPath,onOpen}:{entries:DirectoryEntry[];root:string;bridge?:DesktopBridge;selectedPath:string|null;onOpen:(path:string)=>void}){
 const language=useUiLanguage(),rows=useRows(entries.length,FILE_SUMMARY_ROW_HEIGHT);
 const keydown=(event:KeyboardEvent)=>{if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();rows.move(rows.active+(event.key==='ArrowDown'?1:-1));}else if(event.key==='Home'||event.key==='End'){event.preventDefault();rows.move(event.key==='Home'?0:entries.length-1);}else if(event.key==='Enter'&&entries[rows.active]){event.preventDefault();onOpen(entries[rows.active].path);}};
 return <div ref={rows.ref} className="virtual-file-list virtual-navigation" role="listbox" tabIndex={0} aria-label={language==='en'?'Document list':'文档列表'} aria-activedescendant={`summary-row-${rows.active}`} onScroll={rows.onScroll} onKeyDown={keydown}><div style={{height:entries.length*FILE_SUMMARY_ROW_HEIGHT,position:'relative'}}>{entries.slice(rows.range.start,rows.range.end).map((file,offset)=><div className="virtual-summary-row" data-active={rows.active===rows.range.start+offset} id={`summary-row-${rows.range.start+offset}`} role="option" aria-selected={selectedPath===file.path} key={file.path} style={{position:'absolute',top:(rows.range.start+offset)*FILE_SUMMARY_ROW_HEIGHT,left:0,right:0,height:FILE_SUMMARY_ROW_HEIGHT}}><FileSummary file={file} root={root} bridge={bridge} selected={selectedPath===file.path} tabIndex={-1} onOpen={()=>{rows.move(rows.range.start+offset);onOpen(file.path);}}/></div>)}</div></div>;
}
