// @vitest-environment jsdom
import {afterEach,describe,it,expect,vi} from 'vitest';
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {DocumentStore,createDocument} from '../core/document';
import {CommandRegistry} from '../core/commands';
import {COMMANDS} from '../shared/command-catalog';
import {SettingsStore} from '../shared/settings';
import {WorkspaceShell,WORKSPACE_COMMAND_IDS} from './WorkspaceShell';
import {DEFAULT_EXPORT_PROFILES} from './export-profiles';
import type {DesktopBridge} from '../shared/contracts';
import {SEARCH_TIMEOUT_MS} from './search-task';
(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let root:Root|undefined,container:HTMLDivElement;
afterEach(async()=>{if(root)await act(()=>root!.unmount());root=undefined;container?.remove();localStorage.clear();vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();});
async function mount(text='# Heading\nhello HELLO\n',bridge?:DesktopBridge){
 const store=new DocumentStore(createDocument(text)),settingsStore=new SettingsStore(),registry=new CommandRegistry(COMMANDS),notify=vi.fn(),navigate=vi.fn(),context={document:store,notify};
 settingsStore.set('export.profiles',JSON.stringify(DEFAULT_EXPORT_PROFILES));
 container=document.createElement('div');document.body.append(container);root=createRoot(container);
 const onCommand=(id:string,arg?:unknown)=>{void registry.execute(id,context,arg);};
 await act(async()=>{root!.render(createElement(WorkspaceShell,{store,settingsStore,registry,context,bridge,editor:createElement('textarea',{'aria-label':'test editor',defaultValue:text}),message:'',onCommand,onNavigate:navigate}));});
 return {store,settingsStore,registry,context,navigate};
}
function input(label:string){return container.querySelector<HTMLInputElement>(`input[aria-label="${label}"]`)!;}
async function enter(element:HTMLInputElement,value:string){await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(element,value);element.dispatchEvent(new Event('input',{bubbles:true}));});}
describe('workspace integration',()=>{
 it('updates outline parsing on strict-mode changes without editing source or version',async()=>{const text='😀 intro\r\n\r\n###Loose\r\n';const {store,settingsStore}=await mount(text);expect(container.querySelector('.outline-entry')).toBeNull();await act(()=>settingsStore.set('markdown.strict',false));expect(container.querySelector('.outline-entry')?.textContent).toContain('Loose');expect(store.getSnapshot().text).toBe(text);expect(store.getSnapshot().version).toBe(0);await act(()=>settingsStore.set('markdown.strict',true));expect(container.querySelector('.outline-entry')).toBeNull();});
 it('registers exactly the owned commands and unregisters on close',async()=>{const {registry}=await mount();expect(new Set(registry.implementedIds())).toEqual(new Set(WORKSPACE_COMMAND_IDS));await act(()=>root!.unmount());root=undefined;expect(registry.implementedIds()).toEqual([]);});
 it('opens every catalog submenu beside its parent and hides unopened commands',async()=>{const {store}=await mount();const initial=store.getSnapshot();const groups=[...new Set(COMMANDS.map(item=>item.menu).filter(menu=>menu.includes('/')))];for(const group of groups){const [name,label]=group.split('/');const rootButton=[...container.querySelectorAll<HTMLButtonElement>('nav button[aria-haspopup=menu]')].find(button=>button.textContent===name)!;if(rootButton.getAttribute('aria-expanded')!=='true')await act(()=>rootButton.click());const trigger=container.querySelector<HTMLButtonElement>(`[data-menu-key="${group}"]`)!;expect(trigger.getAttribute('aria-expanded')).toBe('false');const command=COMMANDS.find(item=>item.menu===group)!;expect(container.querySelector(`[data-menu-key="${command.id}"]`)).toBeNull();await act(()=>trigger.click());const panel=container.querySelector(`[role=menu][aria-label="${label}"]`)!;expect(panel.classList.contains('workspace-submenu-panel')).toBe(true);expect(trigger.getAttribute('aria-expanded')).toBe('true');expect(panel.querySelector(`[data-menu-key="${command.id}"]`)).toBeTruthy();await act(()=>trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));await act(()=>rootButton.click());}expect(store.getSnapshot().text).toBe(initial.text);expect(store.getSnapshot().version).toBe(initial.version);});
 it('keeps exports in a separate submenu and dispatches the selected profile',async()=>{const {registry}=await mount();const exported=vi.fn();await act(()=>{registry.register('file.export',(_context,arg)=>{exported(arg);});});const file=[...container.querySelectorAll<HTMLButtonElement>('nav button')].find(button=>button.textContent==='文件')!;await act(()=>file.click());expect(container.querySelector('.export-menu-item')).toBeNull();const trigger=container.querySelector<HTMLButtonElement>('[data-menu-key="file.export"]')!;expect(trigger.getAttribute('aria-haspopup')).toBe('menu');expect(trigger.getAttribute('aria-expanded')).toBe('false');await act(()=>trigger.click());const panel=container.querySelector('[role=menu][aria-label="导出格式"]')!;expect(panel.querySelectorAll('.export-menu-item')).toHaveLength(DEFAULT_EXPORT_PROFILES.length);expect(panel.parentElement).toBe(container.querySelector('.workspace-menu-root:has(.active)'));const target=panel.querySelector<HTMLButtonElement>('[data-menu-key="export:builtin-html"]')!;await act(()=>target.click());expect(exported).toHaveBeenCalledWith(DEFAULT_EXPORT_PROFILES.find(profile=>profile.id==='builtin-html'));expect(container.querySelector('.workspace-dropdown')).toBeNull();});
 it('navigates only the active menu and returns to the parent with Left or Escape',async()=>{const {registry}=await mount();await act(()=>{for(const command of COMMANDS.filter(command=>command.menu==='编辑/选择'))registry.register(command.id,()=>{});});const edit=[...container.querySelectorAll<HTMLButtonElement>('nav button')].find(button=>button.textContent==='编辑')!;await act(()=>edit.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true})));const rootPanel=container.querySelector<HTMLElement>('[data-menu-depth="0"]')!;expect(document.activeElement).toBe(rootPanel.querySelector('button:not(:disabled)'));const trigger=container.querySelector<HTMLButtonElement>('[data-menu-key="编辑/选择"]')!;trigger.focus();await act(()=>trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true})));const child=container.querySelector<HTMLElement>('[data-menu-depth="1"]')!;expect(document.activeElement).toBe(child.querySelector('button:not(:disabled)'));await act(()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true})));expect((document.activeElement as HTMLElement).dataset.menuKey).toBe('selection.lineEnd');await act(()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true})));expect(document.activeElement).toBe(trigger);expect(container.querySelector('[data-menu-depth="1"]')).toBeNull();await act(()=>trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(document.activeElement).toBe(edit);expect(container.querySelector('.workspace-dropdown')).toBeNull();});
 it('switches hover submenus without keeping sibling panels open',async()=>{await mount();await act(()=>[...container.querySelectorAll<HTMLButtonElement>('nav button')].find(button=>button.textContent==='编辑')!.click());const selection=container.querySelector<HTMLButtonElement>('[data-menu-key="编辑/选择"]')!;const range=container.querySelector<HTMLButtonElement>('[data-menu-key="编辑/范围"]')!;await act(()=>selection.dispatchEvent(new MouseEvent('pointerover',{bubbles:true})));expect(selection.getAttribute('aria-expanded')).toBe('true');await act(()=>range.dispatchEvent(new MouseEvent('pointerover',{bubbles:true})));expect(selection.getAttribute('aria-expanded')).toBe('false');expect(range.getAttribute('aria-expanded')).toBe('true');expect(container.querySelector('[role=menu][aria-label="选择"]')).toBeNull();expect(container.querySelector('[role=menu][aria-label="范围"]')).toBeTruthy();await act(()=>document.body.dispatchEvent(new MouseEvent('pointerdown',{bubbles:true})));expect(container.querySelector('.workspace-dropdown')).toBeNull();});
 it('keeps a hovered root open when it is clicked and focuses an already expanded submenu',async()=>{const {registry}=await mount();await act(()=>{registry.register('file.export',()=>{});});const file=[...container.querySelectorAll<HTMLButtonElement>('.workspace-menu-root>button')].find(button=>button.textContent==='文件')!;const edit=[...container.querySelectorAll<HTMLButtonElement>('.workspace-menu-root>button')].find(button=>button.textContent==='编辑')!;await act(()=>edit.click());await act(()=>file.dispatchEvent(new MouseEvent('pointerover',{bubbles:true})));await act(()=>file.click());expect(file.getAttribute('aria-expanded')).toBe('true');const trigger=container.querySelector<HTMLButtonElement>('[data-menu-key="file.export"]')!;await act(()=>trigger.click());trigger.focus();await act(()=>trigger.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true})));expect((document.activeElement as HTMLElement).dataset.menuKey).toBe('export:builtin-pdf');});
 it('keeps source and version unchanged for themes, outline and statistics',async()=>{const {store,registry,context,settingsStore}=await mount();const initial=store.getSnapshot();await act(()=>registry.execute('theme.night',context));expect(settingsStore.getSnapshot()['appearance.theme']).toBe('night');await act(()=>registry.execute('view.statistics',context));expect(container.querySelector('[role=dialog]')?.getAttribute('aria-label')).toBe('字数统计');expect(store.getSnapshot().text).toBe(initial.text);expect(store.getSnapshot().version).toBe(initial.version);});
 it('rejects invalid regex and makes replacement one undo step',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);const {registry,context,store}=await mount('hello hello');await act(()=>registry.execute('search.replace',context));await enter(input('文内查找'),'hello');await enter(input('替换为'),'world');expect(registry.isEnabled('search.replaceAll',context)).toBe(true);await act(()=>registry.execute('search.replaceAll',context));expect(store.getSnapshot().text).toBe('world world');store.undo();expect(store.getSnapshot().text).toBe('hello hello');await act(async()=>{container.querySelector<HTMLButtonElement>('[aria-label="正则表达式"]')!.click();});await enter(input('文内查找'),'[');expect(container.querySelector('[role=alert]')?.textContent).toContain('正则无效');expect(registry.isEnabled('search.replaceAll',context)).toBe(false);});
 it('uses actual command availability in menus',async()=>{await mount();await act(async()=>{[...container.querySelectorAll<HTMLButtonElement>('nav button')].find(button=>button.textContent==='文件')!.click();});const newWindow=[...container.querySelectorAll<HTMLButtonElement>('[role=menuitem]')].find(button=>button.textContent?.includes('新建窗口'));expect(newWindow?.disabled).toBe(true);});
 it('uses all schema settings with Chinese labels and validates advanced input atomically',async()=>{const {registry,context,settingsStore}=await mount();await act(()=>registry.execute('file.preferences',context));await enter(input('搜索设置'),'缩放');expect(container.textContent).toContain('界面缩放百分比');await act(async()=>{[...container.querySelectorAll('button')].find(button=>button.textContent==='高级配置')!.click();});const editor=container.querySelector<HTMLTextAreaElement>('[aria-label="高级配置 JSON"]')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value')!.set!.call(editor,'{"appearance.zoom":120,"unknown":true}');editor.dispatchEvent(new Event('input',{bubbles:true}));[...container.querySelectorAll('button')].find(button=>button.textContent==='校验并应用')!.click();});expect(settingsStore.getSnapshot()['appearance.zoom']).toBe(100);expect(container.querySelector('[role=alert]')?.textContent).toContain('未知设置');});
 it('keeps search text outside the source and disables readonly replacement',async()=>{const {registry,context,store}=await mount('cat cat');store.patchMetadata({readonly:true});await act(()=>registry.execute('search.replace',context));await enter(input('文内查找'),'cat');await enter(input('替换为'),'dog');expect(registry.isEnabled('search.replaceAll',context)).toBe(false);expect(store.getSnapshot().text).toBe('cat cat');});
 it('translates core menus, settings and help without translating user source or headings',async()=>{const {registry,context,settingsStore,store}=await mount('# 主题\n\n文件');await act(async()=>{settingsStore.set('general.language','en');});expect([...container.querySelectorAll('nav button')].some(button=>button.textContent==='File')).toBe(true);expect(container.querySelector('.outline-entry')?.textContent).toContain('主题');expect(store.getSnapshot().text).toBe('# 主题\n\n文件');await act(()=>registry.execute('file.preferences',context));expect(container.querySelector('[role=dialog]')?.getAttribute('aria-label')).toBe('Preferences');expect(container.textContent).toContain('On startup');await act(async()=>{container.querySelector<HTMLButtonElement>('[aria-label="Close dialog"]')!.click();});await act(()=>registry.execute('app.markdownHelp',context));expect(container.querySelector('[role=dialog]')?.getAttribute('aria-label')).toBe('Markdown reference');expect(container.textContent).toContain('Unknown or incomplete syntax remains');expect(store.getSnapshot().version).toBe(0);});
 it('terminates unresponsive regex workers and preserves editable UI',async()=>{const instances:{terminate:ReturnType<typeof vi.fn>}[]=[];class StuckWorker{onmessage:unknown;onerror:unknown;terminate=vi.fn();postMessage=vi.fn();constructor(){instances.push(this);}}vi.stubGlobal('Worker',StuckWorker);vi.useFakeTimers();const {registry,context}=await mount('aaaaaaaaaaaaaaaa');await act(()=>registry.execute('search.find',context));await enter(input('文内查找'),'a');await act(async()=>{container.querySelector<HTMLButtonElement>('[aria-label="正则表达式"]')!.click();});await act(async()=>{vi.advanceTimersByTime(SEARCH_TIMEOUT_MS+1);});expect(instances.some(instance=>instance.terminate.mock.calls.length>0)).toBe(true);expect(container.querySelector('[role=alert]')?.textContent).toContain('超过时限');await act(()=>registry.execute('theme.night',context));expect(container.querySelector('.theme-night')).toBeTruthy();});
 it('starts at the first match, preserves its selection and keeps focus in search',async()=>{const {registry,context,store,navigate}=await mount('hello hello');await act(()=>registry.execute('search.find',context));await enter(input('文内查找'),'hello');await act(()=>registry.execute('search.next',context));expect(navigate).toHaveBeenLastCalledWith(0);expect(store.getSnapshot().selection).toEqual({anchor:0,head:5});expect(document.activeElement).toBe(input('文内查找'));await act(()=>registry.execute('search.next',context));expect(navigate).toHaveBeenLastCalledWith(6);expect(store.getSnapshot().selection).toEqual({anchor:6,head:11});});
 it('opens a recent folder as the navigation root and preserves a translated-looking folder name',async()=>{const listDirectory=vi.fn().mockResolvedValue({ok:true,value:[]});const bridge={systemAction:vi.fn().mockResolvedValue({ok:true,value:[{path:'C:/notes/文件',kind:'folder',openedAt:10}]}),listDirectory,onFileChanged:()=>()=>{}} as unknown as DesktopBridge;const {registry,context,store,settingsStore}=await mount('# 文件',bridge);const open=vi.fn();registry.register('file.open',(_context,arg)=>{open(arg);});await act(()=>settingsStore.set('general.language','en'));await act(()=>registry.execute('file.recent',context));expect(container.querySelector('.quick-results strong')?.textContent).toBe('文件');await act(()=>container.querySelector<HTMLButtonElement>('.quick-results button')!.click());expect(store.getSnapshot().rootDirectory).toBe('C:/notes/文件');expect(open).not.toHaveBeenCalled();expect(container.querySelector('.root-directory')?.textContent).toContain('文件');expect(listDirectory).toHaveBeenCalledWith('C:/notes/文件');expect(store.getSnapshot().text).toBe('# 文件');});
 it('rejects a regex replacement computed for an older source version',async()=>{vi.spyOn(window,'confirm').mockReturnValue(true);const instances:{onmessage:((event:MessageEvent)=>void)|null;postMessage:ReturnType<typeof vi.fn>}[]=[];class ManualWorker{onmessage:((event:MessageEvent)=>void)|null=null;onerror:unknown;terminate=vi.fn();postMessage=vi.fn();constructor(){instances.push(this);}}vi.stubGlobal('Worker',ManualWorker);const {registry,context,store}=await mount('hello');await act(()=>registry.execute('search.replace',context));await enter(input('文内查找'),'hello');await enter(input('替换为'),'world');await act(()=>container.querySelector<HTMLButtonElement>('[aria-label="正则表达式"]')!.click());await act(()=>instances[0].onmessage?.({data:{matches:[{from:0,to:5,text:'hello'}],error:null,truncated:false}} as MessageEvent));let result:Promise<unknown>|undefined;await act(()=>{result=registry.execute('search.replaceAll',context);});const replacementWorker=instances.find(instance=>instance.postMessage.mock.calls[0]?.[0]?.kind==='replace');expect(replacementWorker).toBeTruthy();await act(()=>store.replaceText('user edit','input'));await act(async()=>{replacementWorker!.onmessage?.({data:{ok:true,value:[{from:0,to:5,insert:'world'}]}} as MessageEvent);await result;});expect(store.getSnapshot().text).toBe('user edit');expect(context.notify).toHaveBeenCalledWith('文档已变化，请重新检查匹配后替换。');});
});
