import type { CommandDefinition } from '../core/commands';
const command = (id: string, label: string, menu: string, shortcut?: string, modifiesDocument = false): CommandDefinition => ({ id, label, menu, shortcut, modifiesDocument });
const group = (menu: string, prefix: string, items: [string, string, string?, boolean?][]) => items.map(([id, label, shortcut, modifies]) => command(`${prefix}.${id}`, label, menu, shortcut, modifies));
export const COMMANDS: readonly CommandDefinition[] = [
  ...group('文件', 'file', [
    ['new', '新建', 'Ctrl+N'], ['newWindow', '新建窗口', 'Ctrl+Shift+N'], ['open', '打开', 'Ctrl+O'], ['openFolder', '打开文件夹'], ['quickOpen', '快速打开', 'Ctrl+P'], ['recent', '最近使用'],
    ['save', '保存', 'Ctrl+S'], ['saveAs', '另存为', 'Ctrl+Shift+S'], ['saveAll', '保存所有文件'], ['move', '移动到'], ['properties', '文件属性'], ['reveal', '打开文件位置'], ['revealInSidebar', '在侧边栏显示'], ['delete', '删除文件'], ['import', '导入'], ['export', '导出'], ['print', '打印', 'Alt+Shift+P'], ['preferences', '偏好设置', 'Ctrl+,'], ['close', '关闭', 'Ctrl+W']
  ]),
  ...group('编辑', 'edit', [['undo','撤销','Ctrl+Z',true],['redo','重做','Ctrl+Y',true],['cut','剪切','Ctrl+X',true],['copy','复制','Ctrl+C'],['copyImage','拷贝图片'],['paste','粘贴','Ctrl+V',true],['copyPlain','复制为纯文本'],['copyMarkdown','复制为 Markdown','Ctrl+Shift+C'],['copyHTML','复制为 HTML 代码'],['copySimplified','复制并简化格式'],['pastePlain','粘贴为纯文本','Ctrl+Shift+V',true]]),
  ...group('编辑/选择','selection',[['all','全选','Ctrl+A'],['block','选择段落或块','Ctrl+Alt+P'],['lineOrSentence','选择当前行或句','Ctrl+L'],['formatted','选择当前格式文本','Ctrl+E'],['word','选择当前词','Ctrl+D'],['documentStart','跳转到文首','Ctrl+Home'],['selection','跳转到选区','Ctrl+J'],['documentEnd','跳转到文末','Ctrl+End'],['lineStart','跳转到行首','Home'],['lineEnd','跳转到行尾','End']]),
  ...group('编辑/范围','range',[['moveLineUp','上移该行','Alt+ArrowUp',true],['moveLineDown','下移该行','Alt+ArrowDown',true],['delete','删除',undefined,true],['deleteBlock','删除块','Ctrl+Alt+Shift+P',true],['deleteLineOrSentence','删除当前行或句','Ctrl+Alt+Shift+L',true],['deleteFormatted','删除格式文本','Ctrl+Alt+Shift+E',true],['deleteWord','删除当前词','Ctrl+Shift+D',true]]),
  ...group('编辑/文本','text',[['smartPunctuation','智能标点'],['quotes','智能引号'],['dashes','智能破折号'],['unicode','Unicode 标点'],['LF','Unix LF',undefined,true],['CRLF','Windows CRLF',undefined,true],['finalNewline','文末添加空行'],['firstIndent','首行缩进'],['br','显示 br 换行'],['softBreak','保留单换行符'],['spelling','拼写检查'],['emoji','表情与符号']]),
  ...Array.from({ length: 6 }, (_, index) => command(`paragraph.heading${index+1}`, `${index+1}级标题`, '段落', `Ctrl+${index+1}`, true)),
  ...group('段落','paragraph',[['plain','段落','Ctrl+0',true],['promote','提升标题级别','Ctrl+=',true],['demote','降低标题级别','Ctrl+-',true],['quote','引用','Ctrl+Shift+Q',true],['ordered','有序列表','Ctrl+Shift+[',true],['unordered','无序列表','Ctrl+Shift+]',true],['task','任务列表','Ctrl+Shift+X',true],['taskState','切换任务状态',undefined,true],['indent','增加缩进','Ctrl+]',true],['outdent','减少缩进','Ctrl+[',true],['insertBefore','在上方插入段落',undefined,true],['insertAfter','在下方插入段落',undefined,true],['reference','链接引用',undefined,true],['footnote','脚注',undefined,true],['hr','水平分割线',undefined,true],['toc','内容目录',undefined,true],['yaml','YAML 元数据',undefined,true]]),
  ...group('段落/表格','table',[['create','插入表格',undefined,true],['rowBefore','上方插行',undefined,true],['rowAfter','下方插行','Ctrl+Enter',true],['columnBefore','左侧插列',undefined,true],['columnAfter','右侧插列',undefined,true],['moveRowUp','上移行',undefined,true],['moveRowDown','下移行',undefined,true],['moveColumnLeft','左移列',undefined,true],['moveColumnRight','右移列',undefined,true],['deleteRow','删除行','Ctrl+Shift+Backspace',true],['deleteColumn','删除列',undefined,true],['copy','复制表格'],['formatSource','格式化表格源码',undefined,true],['delete','删除表格',undefined,true],['alignment','列对齐',undefined,true]]),
  ...group('段落/代码','code',[['create','代码块','Ctrl+Shift+K',true],['language','代码语言',undefined,true],['copy','复制代码内容'],['indentSelection','调整选区缩进',undefined,true],['indentBlock','调整代码块缩进',undefined,true]]),
  ...group('段落/公式','math',[['create','公式块','Ctrl+Shift+M',true],['refreshAll','刷新所有公式'],['settings','公式设置']]),
  ...group('段落/警告框','alert',[['note','提醒内容',undefined,true],['tip','建议内容',undefined,true],['important','重要内容',undefined,true],['warning','警告内容',undefined,true],['caution','注意内容',undefined,true]]),
  ...group('格式','format',[['bold','粗体','Ctrl+B',true],['italic','斜体','Ctrl+I',true],['underline','下划线','Ctrl+U',true],['code','行内代码','Ctrl+Shift+`',true],['strike','删除线','Alt+Shift+5',true],['comment','注释',undefined,true],['link','超链接','Ctrl+K',true],['linkActions','链接操作'],['clear','清除样式','Ctrl+\\',true],['highlight','高亮',undefined,true],['sub','下标',undefined,true],['sup','上标',undefined,true]]),
  ...group('格式/图像','image',[['insert','插入图片','Ctrl+Shift+I',true],['insertLocal','插入本地图片',undefined,true],['reveal','打开图片位置'],['copy','拷贝图片'],['scale','缩放图片',undefined,true],['convertSyntax','转换图片语法',undefined,true],['deleteFile','删除图片文件'],['copyTo','复制图片到'],['moveOrRename','移动或重命名图片'],['upload','上传图片'],['copyAll','复制所有图片'],['moveAll','移动所有图片'],['uploadAll','上传所有本地图片'],['reloadAll','重新加载图片'],['insertStrategy','插入图片策略'],['root','设置图片根目录'],['settings','全局图像设置']]),
  ...group('视图','view',[['sidebar','侧边栏','Ctrl+Shift+L'],['outline','大纲','Ctrl+Shift+1'],['fileList','文档列表','Ctrl+Shift+2'],['fileTree','文件树','Ctrl+Shift+3'],['sidebarSearch','跨文件搜索','Ctrl+Shift+F'],['source','源码模式','Ctrl+/'],['focus','专注模式','F8'],['typewriter','打字机模式','F9'],['statusBar','状态栏'],['statistics','字数统计'],['fullscreen','全屏','F11'],['alwaysOnTop','总在最前'],['actualSize','实际大小','Ctrl+Shift+9'],['zoomIn','放大','Ctrl+Shift+='],['zoomOut','缩小','Ctrl+Shift+-'],['switchWindow','切换窗口','Ctrl+Tab'],['devtools','开发者工具','Shift+F12']]),
  ...group('编辑/搜索','search',[['find','查找','Ctrl+F'],['next','下一个','F3'],['previous','上一个','Shift+F3'],['replace','替换','Ctrl+H'],['replaceAll','替换全部',undefined,true]]),
  ...group('主题','theme',[['github','Github'],['newsprint','Newsprint'],['night','Night'],['pixyll','Pixyll'],['whitey','Whitey'],['custom','加载自定义主题'],['folder','打开主题目录'],['discover','获取主题']]),
  ...group('帮助','app',[['quickStart','快速开始'],['markdownHelp','Markdown 参考'],['pandocHelp','转换器帮助'],['themeHelp','自定义主题'],['imageHelp','图像帮助'],['recoveryHelp','恢复与版本控制'],['changelog','版本说明'],['credits','鸣谢'],['privacy','隐私说明'],['feedback','反馈'],['site','项目主页'],['update','检查更新'],['license','发行许可'],['about','关于'],['advanced','高级配置'],['reset','重置高级配置'],['windowsNewItem','资源管理器集成']])
];
export function matchesShortcut(event: KeyboardEvent, shortcut: string): boolean {
  const parts = shortcut.toLowerCase().split('+'), key = parts.pop()!;
  return event.ctrlKey === parts.includes('ctrl') && event.shiftKey === parts.includes('shift') && event.altKey === parts.includes('alt') && !event.metaKey && event.key.toLowerCase() === key;
}
