import {useCallback,useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {DocumentStore,createDocument} from './core/document';
import {CommandRegistry} from './core/commands';
import {imageReferences,imageAt} from './core/formatting';
import {COMMANDS,matchesShortcut} from './shared/command-catalog';
import {SettingsStore,type SettingsKey} from './shared/settings';
import type {AssetResult,ExportProfile,Result} from './shared/contracts';
import type {EditorHandle} from './shared/components';
import {desktop} from './platform/desktop';
import {SessionCoordinator} from './platform/session';
import {MarkdownEditor,EDITOR_COMMAND_IDS,canExecuteEditorCommand} from './editor/MarkdownEditor';
import {WorkspaceShell} from './ui/WorkspaceShell';
import {DEFAULT_EXPORT_PROFILES,getSelectedExportProfile} from './ui/export-profiles';
import {renderMarkdown,hydrateDiagrams} from './render/markdown';
import {Dialog} from './ui/Dialog';
const store=new DocumentStore(createDocument()),settingsStore=new SettingsStore();
interface Prompt {title:string;message:string;choices:{id:string;label:string}[];input?:string;resolve:(value:string|null)=>void}
function valueOf<T>(result:Result<T>):T{if(!result.ok)throw Object.assign(new Error(result.error.message),result.error);return result.value;}
function imageUrl(path:string,documentPath:string|null){const settings=settingsStore.getSnapshot();let url=path;if(settings['image.relative']&&documentPath){const file=path.replace(/\\/g,'/').split('/'),base=documentPath.replace(/\\/g,'/').split('/').slice(0,-1);if(file[0]?.toLowerCase()===base[0]?.toLowerCase()){let same=0;while(same<file.length&&same<base.length&&file[same].toLowerCase()===base[same].toLowerCase())same++;url=[...base.slice(same).map(()=> '..'),...file.slice(same)].join('/');if(settings['image.prefixDot']&&!url.startsWith('.'))url=`./${url}`;}}if(settings['image.escapeUrl'])url=url.split('/').map(part=>encodeURIComponent(part)).join('/').replace(/^([a-z])%3A/i,'$1:');return url.replace(/\\/g,'/');}
export function App(){
  const document=useSyncExternalStore(store.subscribe,store.getSnapshot),settings=useSyncExternalStore(settingsStore.subscribe,settingsStore.getSnapshot);
  const registry=useMemo(()=>new CommandRegistry(COMMANDS),[]),context=useMemo(()=>({document:store,notify:(message:string)=>setMessage(message)}),[]);
  const editor=useRef<EditorHandle>(null),command=useRef<(id:string,argument?:unknown)=>void>(()=>{});
  const [message,setMessage]=useState(''),[sourceMode,setSourceMode]=useState(false),[focusMode,setFocusMode]=useState(false),[typewriterMode,setTypewriterMode]=useState(false),[editorGeneration,setEditorGeneration]=useState(0);
  const [prompt,setPrompt]=useState<Prompt|null>(null),[input,setInput]=useState('');const promptQueue=useRef(Promise.resolve<unknown>(undefined));
  const ask=useCallback((title:string,message:string,choices:Prompt['choices'],initial?:string)=>{const pending=promptQueue.current.then(()=>new Promise<string|null>(resolve=>{setInput(initial??'');setPrompt({title,message,choices,input:initial,resolve});}));promptQueue.current=pending;return pending;},[]);
  const answer=(value:string|null)=>{prompt?.resolve(value);setPrompt(null);};
  const coordinator=useMemo(()=>desktop?new SessionCoordinator(store,desktop,{notify:context.notify,leave:async()=>(await ask('保存修改','当前文档有未保存的修改。',[{id:'save',label:'保存'},{id:'discard',label:'丢弃修改'},{id:'cancel',label:'取消'}])??'cancel') as 'save'|'discard'|'cancel',conflict:async()=>(await ask('磁盘文件已改变','文件已被其他程序修改。',[{id:'overwrite',label:'覆盖磁盘文件'},{id:'saveAs',label:'另存为'},{id:'cancel',label:'取消'}])??'cancel') as 'overwrite'|'saveAs'|'cancel'}):null,[ask,context]);
  const run=useCallback((id:string,argument?:unknown)=>{void registry.execute(id,context,argument).then(result=>{if(!result.ok)context.notify(result.error.message+(result.error.detail?`：${result.error.detail}`:''));});},[registry,context]);command.current=run;
  const saveWithAssets=useCallback(async(as=false)=>{
    if(!desktop||!coordinator)return;const previous=store.getSnapshot();await coordinator.save(as);const current=store.getSnapshot();
    if(current.documentId!==previous.documentId||!current.path||current.path===previous.path||settingsStore.getSnapshot()['image.strategy']!=='copy')return;
    const refs=imageReferences(current.text).filter(item=>!/^(?:https?:|data:)/i.test(item.url));const paths:string[]=[];const oldUrls=new Map<string,string>();
    for(const ref of refs){const result=valueOf(await desktop.systemAction('assets.resolve',{url:ref.url,documentPath:previous.path}));if(result&&typeof result==='object'&&'path'in result&&typeof result.path==='string'){paths.push(result.path);oldUrls.set(ref.url,result.path);}}
    if(!paths.length)return;const results=valueOf(await desktop.systemAction('assets.materialize',{documentPath:current.path,paths:[...new Set(paths)]})) as (AssetResult&{sourcePath:string})[];
    const urls=new Map(results.filter(item=>!item.error).map(item=>[item.sourcePath,item.url]));const snapshot=store.getSnapshot();if(snapshot.documentId!==current.documentId)return;
    const changes=imageReferences(snapshot.text).flatMap(ref=>{const next=urls.get(oldUrls.get(ref.url)??'');return next&&next!==ref.url?[{from:ref.urlFrom,to:ref.urlTo,insert:next}]:[];});
    const distinct=[...new Map(changes.map(change=>[change.from,change])).values()];if(distinct.length){store.apply({transactionId:crypto.randomUUID(),documentId:snapshot.documentId,baseVersion:snapshot.version,changes:distinct,origin:'asset'});await coordinator.save();}const failures=results.filter(item=>item.error);if(failures.length)context.notify(`部分资源未迁移：${failures.map(item=>item.error).join('；')}`);
  },[coordinator,context]);
  useEffect(()=>{
    const disposers:(()=>void)[]=[];const register=(id:string,handler:(arg?:unknown)=>unknown,enabled?:()=>boolean)=>disposers.push(registry.register(id,async(_context,arg)=>{await handler(arg);},enabled));
    const system=async(action:string,options?:Record<string,unknown>)=>{if(!desktop)throw new Error('此功能需要桌面版');return valueOf(await desktop.systemAction(action,options));};
    const toggle=(key:SettingsKey)=>settingsStore.set(key,!settingsStore.getSnapshot()[key]);
    const show=async(title:string,value:unknown)=>{await ask(title,typeof value==='string'?value:JSON.stringify(value,null,2),[{id:'ok',label:'关闭'}]);};
    const requirePath=()=>{const path=store.getSnapshot().path;if(!path)throw new Error('请先保存当前文档');return path;};
    for(const id of EDITOR_COMMAND_IDS)register(id,async(arg)=>{if(!await editor.current?.execute(id,arg))throw new Error('当前光标位置不可执行此操作');},()=>canExecuteEditorCommand(store,id));
    register('file.new',async()=>{if(coordinator)await coordinator.newDocument();else if(!store.getSnapshot().dirty||await ask('新建文档','丢弃未保存修改？',[{id:'discard',label:'丢弃'},{id:'cancel',label:'取消'}])==='discard')store.replaceSession(createDocument());});
    register('file.open',arg=>coordinator?.open(typeof arg==='string'?arg:undefined));
    register('file.newWindow',async()=>{if(desktop)valueOf(await desktop.windowAction('new'));});
    register('file.save',()=>saveWithAssets());register('file.saveAs',()=>saveWithAssets(true));register('file.saveAll',async()=>{await saveWithAssets();await system('windows.saveAll');});
    register('file.openFolder',async()=>{if(!desktop)return;const root=valueOf(await desktop.chooseFolder());if(root)store.patchMetadata({rootDirectory:root});});
    register('file.close',async()=>{if(desktop)valueOf(await desktop.saveSettings(settingsStore.getSnapshot()));await coordinator?.close();});
    register('file.import',arg=>coordinator?.importFile(typeof arg==='string'?arg:undefined));
    register('file.move',async()=>{if(!desktop)return;const from=requirePath(),to=await ask('移动文件','输入新文件的完整路径',[{id:'submit',label:'移动'},{id:'cancel',label:'取消'}],from);if(!to||to==='cancel')return;if(store.getSnapshot().dirty){await saveWithAssets();if(store.getSnapshot().dirty)return;}const path=valueOf(await desktop.moveFile(from,to));store.patchMetadata({path});});
    register('file.delete',async()=>{if(!desktop)return;const snapshot=store.getSnapshot(),path=requirePath();if(await ask('删除文件',`将 ${path} 移入回收站。`,[{id:'delete',label:'移入回收站'},{id:'cancel',label:'取消'}])!=='delete')return;valueOf(await desktop.trashFile(path));store.replaceSession({...snapshot,path:null,diskFingerprint:null,readonly:false,dirty:true});context.notify('文件已移入回收站，当前内容可另存为');});
    register('file.properties',async()=>show('文件属性',await system('file.properties',{path:requirePath()})));register('file.reveal',async()=>{if(desktop)valueOf(await desktop.reveal(requirePath()));});
    register('file.print',async()=>{const snapshot=store.getSnapshot(),options=settingsStore.getSnapshot();const container=window.document.createElement('div');container.innerHTML=renderMarkdown(snapshot.text,options,{path:snapshot.path});window.document.body.append(container);try{await hydrateDiagrams(container,options);await system('print.snapshot',{snapshot:{documentId:snapshot.documentId,version:snapshot.version,text:snapshot.text,path:snapshot.path,html:container.innerHTML,title:snapshot.path?.split(/[\\/]/).pop()??'未命名',profile:DEFAULT_EXPORT_PROFILES.find(item=>item.format==='pdf')!}});}finally{container.remove();}});
    register('file.export',async arg=>{if(!desktop)return;const snapshot=store.getSnapshot(),currentSettings=settingsStore.getSnapshot();const profile=(arg as ExportProfile|undefined)??getSelectedExportProfile(currentSettings);if(!profile)throw new Error('请先创建导出配置');const container=window.document.createElement('div');container.className='opentypora-export';container.style.cssText='position:fixed;left:-10000px;width:860px';container.innerHTML=renderMarkdown(snapshot.text,currentSettings,{path:snapshot.path});window.document.body.append(container);try{await hydrateDiagrams(container,currentSettings);const style=Array.from(window.document.styleSheets).flatMap(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText);}catch{return[];}}).join('\n');const result=valueOf(await desktop.export({documentId:snapshot.documentId,version:snapshot.version,text:snapshot.text,path:snapshot.path,html:container.innerHTML,title:snapshot.path?.split(/[\\/]/).pop()?.replace(/\.[^.]+$/,'')??'未命名',profile:{...profile,options:{...profile.options,pandocPath:currentSettings['export.pandocPath'],themeCss:style,resourceDir:snapshot.rootDirectory??'',preserveSpaces:currentSettings['export.preserveSpaces'],preserveBreaks:currentSettings['export.preserveBreaks']}}}));if(result)context.notify(`已导出 ${result.path}${result.warnings.length?'；'+result.warnings.join('；'):''}${result.postActionError?'；后续动作失败：'+result.postActionError:''}`);}finally{container.remove();}});
    register('view.source',()=>setSourceMode(value=>!value));register('view.focus',()=>setFocusMode(value=>!value));register('view.typewriter',()=>setTypewriterMode(value=>!value));
    for(const [id,action] of [['view.fullscreen','fullscreen'],['view.alwaysOnTop','alwaysOnTop'],['view.devtools','devtools']] as const)register(id,async()=>{if(desktop)valueOf(await desktop.windowAction(action));});register('view.switchWindow',()=>system('windows.next'));
    for(const [id,key] of Object.entries({'text.quotes':'markdown.smartQuotes','text.dashes':'markdown.smartDashes','text.unicode':'markdown.unicodePunctuation','text.finalNewline':'editor.finalNewline','text.firstIndent':'text.firstIndent','text.br':'text.showBr','text.softBreak':'text.preserveBreaks','text.emoji':'editor.emoji'}))register(id,()=>toggle(key as SettingsKey));
    register('text.smartPunctuation',()=>{const on=!settingsStore.getSnapshot()['markdown.smartQuotes'];for(const key of ['markdown.smartQuotes','markdown.smartDashes','markdown.unicodePunctuation'] as const)settingsStore.set(key,on);});
    register('text.spelling',async()=>{const language=await ask('拼写检查','输入语言标识，auto 使用系统语言，off 关闭。',[{id:'submit',label:'应用'},{id:'cancel',label:'取消'}],settingsStore.getSnapshot()['editor.spellLanguage']);if(language&&language!=='cancel')settingsStore.set('editor.spellLanguage',language);});
    register('math.refreshAll',()=>setEditorGeneration(value=>value+1));register('math.settings',()=>command.current('file.preferences','Markdown'));register('image.settings',()=>command.current('file.preferences','图像'));
    register('image.insertStrategy',async()=>{const strategy=await ask('图片插入策略','选择插入本地图片时的处理方式',[{id:'none',label:'保留原路径'},{id:'copy',label:'复制到资源目录'},{id:'upload',label:'上传'}]);if(strategy)settingsStore.set('image.strategy',strategy);});
    register('image.root',async()=>{if(!desktop)return;const path=valueOf(await desktop.chooseFolder());if(!path)return;const snapshot=store.getSnapshot(),quoted=JSON.stringify(path.replace(/\\/g,'/'));const text=/^---\r?\n/.test(snapshot.text)?snapshot.text.replace(/^(---\r?\n)/,`$1typora-root-url: ${quoted}\n`):`---\ntypora-root-url: ${quoted}\n---\n\n${snapshot.text}`;store.replaceText(text,'command');});
    register('image.insertLocal',async()=>{if(!desktop)return;const asset=valueOf(await desktop.insertImage(store.getSnapshot().path,settingsStore.getSnapshot()['image.strategy']));if(asset)await editor.current?.execute('image.insert',{url:asset.url,alt:asset.path.split(/[\\/]/).pop()??'图片'});});register('image.reloadAll',()=>setEditorGeneration(value=>value+1));
    const resolveImages=async(all:boolean)=>{const snapshot=store.getSnapshot();const refs=all?imageReferences(snapshot.text):[imageAt(snapshot.text,snapshot.selection.head)].filter((item):item is NonNullable<typeof item>=>!!item);const resolved:{ref:typeof refs[number];path:string}[]=[];for(const ref of refs){if(/^(?:https?:|data:)/i.test(ref.url))continue;const result=await system('assets.resolve',{url:ref.url,documentPath:snapshot.path});if(result&&typeof result==='object'&&'path'in result&&typeof result.path==='string')resolved.push({ref,path:result.path});}if(!resolved.length)throw new Error('当前没有可处理的本地图片');return{snapshot,resolved};};
    register('image.reveal',async()=>{const {resolved}=await resolveImages(false);if(desktop)valueOf(await desktop.reveal(resolved[0].path));});
    for(const id of ['image.copy','edit.copyImage'])register(id,async()=>{const {resolved}=await resolveImages(false);await system('clipboard.image',{path:resolved[0].path});});
    for(const id of ['image.copyTo','image.moveOrRename','image.deleteFile','image.copyAll','image.moveAll','image.upload','image.uploadAll'])register(id,async()=>{if(!desktop)return;const all=id.endsWith('All'),{snapshot,resolved}=await resolveImages(all);const mapping=new Map<string,string>();
      if(id.includes('upload')){const values=valueOf(await desktop.upload(resolved.map((item,index)=>({id:String(index),path:item.path})),settingsStore.getSnapshot()));values.forEach(item=>{if(item.url)mapping.set(resolved[Number(item.id)].ref.url,item.url);});const errors=values.filter(item=>item.error);if(errors.length)context.notify(errors.map(item=>item.error).join('；'));}
      else {const operation=id.includes('delete')?'delete':id.includes('copy')?'copy':id.includes('Rename')?'rename':'move';let destination:string|undefined;if(operation==='delete'){if(await ask('删除图片文件','所有引用此图片的文档都会失去图片文件。',[{id:'delete',label:'移入回收站'},{id:'cancel',label:'取消'}])!=='delete')return;}else if(operation==='rename'){const value=await ask('移动或重命名图片','输入目标文件完整路径',[{id:'submit',label:'应用'},{id:'cancel',label:'取消'}],resolved[0].path);if(!value||value==='cancel')return;destination=value;}else{destination=valueOf(await desktop.chooseFolder())??undefined;if(!destination)return;}const values=valueOf(await desktop.manageAssets(operation,resolved.map(item=>item.path),destination));values.forEach((item,index)=>{if(!item.error&&operation!=='delete')mapping.set(resolved[index].ref.url,imageUrl(item.path,snapshot.path));});const errors=values.filter(item=>item.error);if(errors.length)context.notify(errors.map(item=>item.error).join('；'));}
      const current=store.getSnapshot();if(current.documentId!==snapshot.documentId)return;const changes=imageReferences(current.text).flatMap(ref=>{const url=mapping.get(ref.url);return url?[{from:ref.urlFrom,to:ref.urlTo,insert:url}]:[];});const unique=[...new Map(changes.map(change=>[change.from,change])).values()];if(unique.length)store.apply({transactionId:crypto.randomUUID(),documentId:current.documentId,baseVersion:current.version,changes:unique,origin:'asset'});setEditorGeneration(value=>value+1);
    });
    register('app.site',async()=>{if(desktop)valueOf(await desktop.openExternal('https://github.com/Cjy-CN/OpenTypora'));});register('app.feedback',async()=>{if(desktop)valueOf(await desktop.openExternal('https://github.com/Cjy-CN/OpenTypora/issues'));});
    register('app.windowsNewItem',async()=>{const action=await ask('资源管理器集成','管理当前用户的 Markdown 新建菜单。',[{id:'add',label:'添加新建菜单'},{id:'remove',label:'移除新建菜单'},{id:'cancel',label:'取消'}]);if(action&&action!=='cancel'){await system(`shellNew.${action}`);context.notify('资源管理器新建菜单已更新');}});register('app.update',async()=>show('检查更新',await system('updates.check')));
    const dispose=desktop?.onCommand(id=>command.current(id));return()=>{disposers.forEach(fn=>fn());dispose?.();};
  },[registry,context,ask,coordinator,saveWithAssets]);
  useEffect(()=>{let ready=false,cancelled=false;let timer:ReturnType<typeof setTimeout>;const persist=()=>{if(!ready)return;clearTimeout(timer);timer=setTimeout(()=>{void desktop?.saveSettings(settingsStore.getSnapshot()).then(result=>{if(!result.ok)context.notify(result.error.message);});},300);};const dispose=settingsStore.subscribe(persist);void(async()=>{const result=await desktop?.loadSettings();if(cancelled)return;if(result?.ok){const rejected=settingsStore.load(result.value);if(rejected.length)context.notify(`忽略无效设置：${rejected.join('、')}`);}else if(result)context.notify(result.error.message);if(!settingsStore.getSnapshot()['export.profiles']||settingsStore.getSnapshot()['export.profiles']==='[]')settingsStore.set('export.profiles',JSON.stringify(DEFAULT_EXPORT_PROFILES));ready=true;persist();if(!desktop)return;const drafts=await desktop.listRecovery();if(cancelled||!drafts.ok||!drafts.value.length)return;const choice=await ask('恢复草稿','检测到尚未保存的草稿。',drafts.value.slice(0,8).map(draft=>({id:draft.id,label:`恢复 ${draft.session.path?.split(/[\\/]/).pop()??'未命名'}（${new Date(draft.savedAt).toLocaleString()}）`})).concat([{id:'skip',label:'稍后恢复'}]));const draft=drafts.value.find(item=>item.id===choice);if(draft)store.replaceSession(draft.session);})();return()=>{cancelled=true;clearTimeout(timer);dispose();};},[ask,context]);
  useEffect(()=>{window.document.title=`${document.path?.split(/[\\/]/).pop()??'未命名'}${document.dirty?' •':''} — OpenTypora`;},[document.path,document.dirty]);
  useEffect(()=>{if(!desktop||!document.dirty||document.composing||!settings['file.recovery'])return;const timer=setTimeout(()=>{void desktop!.writeRecovery({id:document.recoveryId,session:document,savedAt:Date.now()}).then(result=>{if(!result.ok)context.notify(result.error.message);});},1000);return()=>clearTimeout(timer);},[document,settings,context]);
  useEffect(()=>{if(!settings['file.autoSave']||!document.path||!document.dirty||document.composing||document.readonly||document.saveState!=='idle')return;const timer=setTimeout(()=>void saveWithAssets(),1500);return()=>clearTimeout(timer);},[document,settings,saveWithAssets]);
  useEffect(()=>{const dispose=desktop?.onFileChanged(path=>{const current=store.getSnapshot();if(current.path?.toLowerCase()!==path.toLowerCase())return;void(async()=>{const opened=await desktop!.readFile(path);if(!opened.ok){context.notify(opened.error.message);return;}if(store.getSnapshot().documentId!==current.documentId||opened.value.fingerprint.hash===current.diskFingerprint?.hash)return;if(store.getSnapshot().dirty){store.markConflict();context.notify('磁盘内容已改变，请在保存时处理冲突');}else store.load(opened.value);})();});return dispose;},[context]);
  useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.defaultPrevented||event.isComposing||prompt)return;const target=event.target as HTMLElement;if(target.closest('.workspace-dialog,.editor-dialog'))return;if((target.tagName==='INPUT'||target.tagName==='TEXTAREA')&&!target.closest('.cm-editor'))return;let custom:Record<string,string>={};try{custom=JSON.parse(settingsStore.getSnapshot()['general.shortcuts']);}catch{}const item=COMMANDS.find(item=>matchesShortcut(event,custom[item.id]??item.shortcut??''));if(item&&registry.isEnabled(item.id,context)){event.preventDefault();run(item.id);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[registry,context,run,prompt]);
  useEffect(()=>{const listener=(event:MouseEvent)=>{if(event.defaultPrevented||(event.target as Element).closest(".cm-editor"))return;const anchor=(event.target as Element).closest<HTMLAnchorElement>('a[href]');if(!anchor)return;const url=anchor.getAttribute('href')??'';if(url.startsWith('#'))return;event.preventDefault();if(/^(https?:|mailto:)/i.test(url))void desktop?.openExternal(url);else if(/\.(md|markdown)(?:#.*)?$/i.test(url)){void desktop?.systemAction('assets.resolve',{url:url.split('#')[0],documentPath:store.getSnapshot().path}).then(result=>{if(result.ok&&result.value&&typeof result.value==='object'&&'path'in result.value)run('file.open',result.value.path);});}};window.addEventListener('click',listener);return()=>window.removeEventListener('click',listener);},[run]);
  return <><div onDragOver={event=>{if(event.dataTransfer.types.includes('Files'))event.preventDefault();}} onDrop={event=>{if(!desktop?.pathForFile||!event.dataTransfer.files.length)return;event.preventDefault();event.stopPropagation();const file=event.dataTransfer.files[0],path=desktop.pathForFile(file);if(!path)return;if(/\.(png|jpe?g|gif|webp|svg|bmp)$/i.test(path)){void desktop.systemAction('assets.stage',{path,documentPath:store.getSnapshot().path,strategy:settingsStore.getSnapshot()['image.strategy']}).then(result=>{if(result.ok&&result.value&&typeof result.value==='object'&&'url'in result.value)run('image.insert',{url:result.value.url,alt:file.name});else if(!result.ok)context.notify(result.error.message);});}else run(/\.(md|markdown|txt|mdx|rmd|qmd)$/i.test(path)?'file.open':'file.import',path);}}>
    <WorkspaceShell store={store} settingsStore={settingsStore} registry={registry} context={context} bridge={desktop} message={message} viewModes={{source:sourceMode,focus:focusMode,typewriter:typewriterMode}} onCommand={run} onNavigate={position=>editor.current?.scrollTo(position)} editor={<MarkdownEditor key={editorGeneration} ref={editor} store={store} settings={settings} sourceMode={sourceMode} focusMode={focusMode} typewriterMode={typewriterMode} bridge={desktop} onCommand={run}/>} />
  </div>{prompt&&<Dialog title={prompt.title} onClose={()=>answer(null)}><p className="app-prompt-message">{prompt.message}</p>{prompt.input!==undefined&&<input autoFocus aria-label={prompt.title} value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')answer(input);}}/>}<div className="app-prompt-actions">{prompt.choices.map(choice=><button key={choice.id} onClick={()=>answer(choice.id==='submit'?input:choice.id)}>{choice.label}</button>)}</div></Dialog>}</>;
}
