import {useCallback,useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react';
import {DocumentStore,createDocument} from './core/document';
import {CommandRegistry} from './core/commands';
import {imageReferences,imageAt} from './core/formatting';
import {COMMANDS,matchesShortcut} from './shared/command-catalog';
import {SettingsStore,type SettingsKey} from './shared/settings';
import type {AssetResult,ExportProfile,Result} from './shared/contracts';
import type {EditorHandle} from './shared/components';
import {desktop} from './platform/desktop';
import {refreshExternalFile} from './platform/file-refresh';
import {SessionCoordinator} from './platform/session';
import {planAssetRelocation,imageDestination,replaceImageDestination,resolveLocalImagePath} from './platform/asset-relocation';
import {MarkdownEditor,EDITOR_COMMAND_IDS,canExecuteEditorCommand} from './editor/MarkdownEditor';
import {WorkspaceShell} from './ui/WorkspaceShell';
import {DEFAULT_EXPORT_PROFILES,getSelectedExportProfile} from './ui/export-profiles';
import {renderMarkdown,hydrateDiagrams} from './render/markdown';
import {Dialog} from './ui/Dialog';
import {UpdateDialog} from './ui/UpdateDialog';
import {preferredNewline} from './core/formatting';
const store=new DocumentStore(createDocument()),settingsStore=new SettingsStore();
interface Prompt {title:string;message:string;choices:{id:string;label:string}[];input?:string;resolve:(value:string|null)=>void}
function valueOf<T>(result:Result<T>):T{if(!result.ok)throw Object.assign(new Error(result.error.message),result.error);return result.value;}
export function App(){
  const document=useSyncExternalStore(store.subscribe,store.getSnapshot),settings=useSyncExternalStore(settingsStore.subscribe,settingsStore.getSnapshot);
  const registry=useMemo(()=>new CommandRegistry(COMMANDS),[]),context=useMemo(()=>({document:store,notify:(message:string)=>setMessage(message)}),[]);
  const closing=useRef(false),settingsReady=useRef(false);
  const editor=useRef<EditorHandle>(null),command=useRef<(id:string,argument?:unknown)=>void>(()=>{});
  const [updateOpen,setUpdateOpen]=useState(false);
  const [message,setMessage]=useState(''),[sourceMode,setSourceMode]=useState(false),[focusMode,setFocusMode]=useState(false),[typewriterMode,setTypewriterMode]=useState(false),[editorGeneration,setEditorGeneration]=useState(0);
  const [prompt,setPrompt]=useState<Prompt|null>(null),[input,setInput]=useState('');const promptQueue=useRef(Promise.resolve<unknown>(undefined));
  const ask=useCallback((title:string,message:string,choices:Prompt['choices'],initial?:string)=>{const pending=promptQueue.current.then(()=>new Promise<string|null>(resolve=>{setInput(initial??'');setPrompt({title,message,choices,input:initial,resolve});}));promptQueue.current=pending;return pending;},[]);
  const answer=(value:string|null)=>{prompt?.resolve(value);setPrompt(null);};
  useEffect(()=>{editor.current?.focus();},[]);
  useEffect(()=>{const path=new URLSearchParams(window.location.search).get('document');if(path&&desktop)queueMicrotask(()=>command.current('file.open',path));},[]);
  const coordinator=useMemo(()=>desktop?new SessionCoordinator(store,desktop,{notify:context.notify,relocateAssets:async(previous,saved)=>{const plan=await planAssetRelocation(previous,saved.path,settingsStore.getSnapshot(),desktop!);const current=store.getSnapshot();if(current.documentId!==previous.documentId||current.version!==previous.version)throw new Error('DOCUMENT_CHANGED：资源处理期间文档已改变，请重试');return plan.changes.length?store.apply({transactionId:crypto.randomUUID(),documentId:previous.documentId,baseVersion:previous.version,changes:plan.changes,origin:'asset'}):false;},saveOnSwitch:()=>settingsStore.getSnapshot()['file.saveOnSwitch'],prepareSave:()=>{const snapshot=store.getSnapshot();if(snapshot.text&&settingsStore.getSnapshot()['editor.finalNewline']&&!/[\r\n]$/.test(snapshot.text))store.replaceText(snapshot.text+preferredNewline(snapshot.text,settingsStore.getSnapshot()['editor.lineEnding']),'command',snapshot.selection);},leave:async()=>(await ask('保存修改','当前文档有未保存的修改。',[{id:'save',label:'保存'},{id:'discard',label:'丢弃修改'},{id:'cancel',label:'取消'}])??'cancel') as 'save'|'discard'|'cancel',conflict:async()=>(await ask('磁盘文件已改变','文件已被其他程序修改。',[{id:'overwrite',label:'覆盖磁盘文件'},{id:'saveAs',label:'另存为'},{id:'cancel',label:'取消'}])??'cancel') as 'overwrite'|'saveAs'|'cancel'}):null,[ask,context]);
  const run=useCallback((id:string,argument?:unknown)=>{void registry.execute(id,context,argument).then(result=>{if(!result.ok)context.notify(result.error.message+(result.error.detail?`：${result.error.detail}`:''));});},[registry,context]);command.current=run;
  const saveWithAssets=useCallback((as=false)=>coordinator?.save(as),[coordinator]);
  useEffect(()=>{
    const disposers:(()=>void)[]=[];const register=(id:string,handler:(arg?:unknown)=>unknown,enabled?:()=>boolean)=>disposers.push(registry.register(id,async(_context,arg)=>{await handler(arg);},enabled));
    const system=async(action:string,options?:Record<string,unknown>)=>{if(!desktop)throw new Error('此功能需要桌面版');return valueOf(await desktop.systemAction(action,options));};
    const toggle=(key:SettingsKey)=>settingsStore.set(key,!settingsStore.getSnapshot()[key]);
    const show=async(title:string,value:unknown)=>{await ask(title,typeof value==='string'?value:JSON.stringify(value,null,2),[{id:'ok',label:'关闭'}]);};
    const requirePath=()=>{const path=store.getSnapshot().path;if(!path)throw new Error('请先保存当前文档');return path;};
    for(const id of EDITOR_COMMAND_IDS)register(id,async(arg)=>{if(!await editor.current?.execute(id,arg))throw new Error('当前光标位置不可执行此操作');},()=>canExecuteEditorCommand(store,id));
    register('file.new',async()=>{if(coordinator)await coordinator.newDocument();else if(!store.getSnapshot().dirty||await ask('新建文档','丢弃未保存修改？',[{id:'discard',label:'丢弃'},{id:'cancel',label:'取消'}])==='discard')store.replaceSession(createDocument());});
    register('file.open',async arg=>{if(await coordinator?.open(typeof arg==='string'?arg:undefined)){const snapshot=store.getSnapshot(),yaml=/^---(?:\r\n|\n)([\s\S]*?)(?:\r\n|\n)(?:---|\.\.\.)(?:\r\n|\n)/.exec(snapshot.text);if(yaml){const position=yaml[0].length+(snapshot.text.slice(yaml[0].length).match(/^\s*/)?.[0].length??0);const heading=snapshot.text.slice(position).match(/^#{1,6}\s+/)?.[0].length??0;store.setSelection({anchor:position+heading,head:position+heading});}}});
    register('file.newWindow',async()=>{if(desktop)valueOf(await desktop.windowAction('new'));});
    register('file.save',()=>saveWithAssets());register('file.saveAs',()=>saveWithAssets(true));register('file.saveAll',async()=>{await saveWithAssets();await system('windows.saveAll');});
    register('file.openFolder',async arg=>{if(!desktop)return;const root=typeof arg==='string'?valueOf(await desktop.systemAction('folder.open',{path:arg})) as string:valueOf(await desktop.chooseFolder());if(root)store.patchMetadata({rootDirectory:root});});
    register('file.close',async()=>{if(closing.current)return;closing.current=true;try{await coordinator?.close();}finally{closing.current=false;}});
    register('file.import',arg=>coordinator?.importFile(typeof arg==='string'?arg:undefined));
    register('file.move',async()=>{const from=requirePath(),to=await ask('移动文件','输入新文件的完整路径',[{id:'submit',label:'移动'},{id:'cancel',label:'取消'}],from);if(to&&to!=='cancel')await coordinator?.move(to);});
    register('file.delete',async()=>{if(!desktop)return;const snapshot=store.getSnapshot(),path=requirePath();if(await ask('删除文件',`将 ${path} 移入回收站。`,[{id:'delete',label:'移入回收站'},{id:'cancel',label:'取消'}])!=='delete')return;if(store.getSnapshot().documentId!==snapshot.documentId||store.getSnapshot().version!==snapshot.version)return;valueOf(await desktop.trashFile(path));if(store.getSnapshot().documentId!==snapshot.documentId||store.getSnapshot().version!==snapshot.version)return;store.replaceSession({...snapshot,path:null,diskFingerprint:null,readonly:false,dirty:true});context.notify('文件已移入回收站，当前内容可另存为');});
    register('file.properties',async()=>show('文件属性',await system('file.properties',{path:requirePath()})));register('file.reveal',async()=>{if(desktop)valueOf(await desktop.reveal(requirePath()));});
    register('file.print',async()=>{const snapshot=store.getSnapshot(),options=settingsStore.getSnapshot();const container=window.document.createElement('div');container.className='opentypora-export';container.style.cssText='position:fixed;left:-10000px;width:860px';container.innerHTML=renderMarkdown(snapshot.text,{...options,'math.htmlRepresentation':'svg'},{path:snapshot.path});window.document.body.append(container);try{await hydrateDiagrams(container,options);await system('print.snapshot',{snapshot:{documentId:snapshot.documentId,version:snapshot.version,text:snapshot.text,path:snapshot.path,html:container.innerHTML,title:snapshot.path?.split(/[\\/]/).pop()??'未命名',profile:{...DEFAULT_EXPORT_PROFILES.find(item=>item.format==='pdf')!,options:{themeCss:Array.from(window.document.styleSheets).flatMap(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText);}catch{return[];}}).join('\n'),preserveSpaces:options['text.preserveSpaces'],preserveBreaks:options['text.preserveBreaks']}}}});}finally{container.remove();}});
    register('file.export',async arg=>{if(!desktop)return;const snapshot=store.getSnapshot(),currentSettings=settingsStore.getSnapshot();const profile=(arg as ExportProfile|undefined)??getSelectedExportProfile(currentSettings);if(!profile)throw new Error('请先创建导出配置');const container=window.document.createElement('div');container.className='opentypora-export';container.style.cssText='position:fixed;left:-10000px;width:860px';container.innerHTML=renderMarkdown(snapshot.text,{...currentSettings,'text.preserveBreaks':currentSettings['export.preserveBreaks'],'text.preserveSpaces':currentSettings['export.preserveSpaces'],'math.htmlRepresentation':profile.format==='html-plain'?currentSettings['math.htmlRepresentation']:'svg'},{path:snapshot.path});window.document.body.append(container);try{await hydrateDiagrams(container,currentSettings);const style=Array.from(window.document.styleSheets).flatMap(sheet=>{try{return Array.from(sheet.cssRules).map(rule=>rule.cssText);}catch{return[];}}).join('\n');const result=valueOf(await desktop.export({documentId:snapshot.documentId,version:snapshot.version,text:snapshot.text,path:snapshot.path,html:container.innerHTML,title:snapshot.path?.split(/[\\/]/).pop()?.replace(/\.[^.]+$/,'')??'未命名',profile:{...profile,options:{...profile.options,pandocPath:currentSettings['export.pandocPath'],themeCss:style,resourceDir:snapshot.rootDirectory??'',preserveSpaces:currentSettings['export.preserveSpaces'],preserveBreaks:currentSettings['export.preserveBreaks']}}}));if(result)context.notify(`已导出 ${result.path}${result.warnings.length?'；'+result.warnings.join('；'):''}${result.postActionError?'；后续动作失败：'+result.postActionError:''}`);}finally{container.remove();}});
    register('view.source',()=>setSourceMode(value=>!value));register('view.focus',()=>setFocusMode(value=>!value));register('view.typewriter',()=>setTypewriterMode(value=>!value));
    for(const [id,action] of [['view.fullscreen','fullscreen'],['view.alwaysOnTop','alwaysOnTop'],['view.devtools','devtools']] as const)register(id,async()=>{if(desktop)valueOf(await desktop.windowAction(action));});register('view.switchWindow',()=>system('windows.next'));
    for(const [id,key] of Object.entries({'text.quotes':'markdown.smartQuotes','text.dashes':'markdown.smartDashes','text.unicode':'markdown.unicodePunctuation','text.finalNewline':'editor.finalNewline','text.firstIndent':'text.firstIndent','text.br':'text.showBr','text.softBreak':'text.preserveBreaks','text.emoji':'editor.emoji'}))register(id,()=>toggle(key as SettingsKey));
    register('text.smartPunctuation',()=>{const on=!settingsStore.getSnapshot()['markdown.smartQuotes'];for(const key of ['markdown.smartQuotes','markdown.smartDashes','markdown.unicodePunctuation'] as const)settingsStore.set(key,on);});
    register('text.spelling',async()=>{const language=await ask('拼写检查','输入语言标识，auto 使用系统语言，off 关闭。',[{id:'submit',label:'应用'},{id:'cancel',label:'取消'}],settingsStore.getSnapshot()['editor.spellLanguage']);if(language&&language!=='cancel')settingsStore.set('editor.spellLanguage',language);});
    register('math.refreshAll',()=>setEditorGeneration(value=>value+1));register('math.settings',()=>command.current('file.preferences','Markdown'));register('image.settings',()=>command.current('file.preferences','图像'));
    register('image.insertStrategy',async()=>{const strategy=await ask('图片插入策略','选择插入本地图片时的处理方式',[{id:'none',label:'保留原路径'},{id:'copy',label:'复制到资源目录'},{id:'upload',label:'上传'}]);if(strategy)settingsStore.set('image.strategy',strategy);});
    register('image.root',async()=>{if(!desktop)return;const path=valueOf(await desktop.chooseFolder());if(!path)return;const snapshot=store.getSnapshot(),quoted=JSON.stringify(path.replace(/\\/g,'/'));const text=/^---\r?\n/.test(snapshot.text)?snapshot.text.replace(/^(---\r?\n)/,`$1typora-root-url: ${quoted}\n`):`---\ntypora-root-url: ${quoted}\n---\n\n${snapshot.text}`;store.replaceText(text,'command');});
    register('image.insertLocal',async()=>{if(!desktop)return;const snapshot=store.getSnapshot(),chosen=valueOf(await desktop.insertImage(snapshot.path,'none'));if(!chosen)return;const asset=valueOf(await desktop.systemAction('assets.stage',{path:chosen.path,documentPath:snapshot.path,documentText:snapshot.text,strategy:settingsStore.getSnapshot()['image.strategy']})) as AssetResult;const current=store.getSnapshot();if(current.documentId!==snapshot.documentId||current.version!==snapshot.version||current.selection.anchor!==snapshot.selection.anchor||current.selection.head!==snapshot.selection.head)throw new Error('DOCUMENT_CHANGED：插入图片期间文档或选区已改变，请重试');await editor.current?.execute('image.insert',{url:asset.url,alt:asset.path.split(/[\\/]/).pop()??'图片'});});register('image.reloadAll',()=>setEditorGeneration(value=>value+1));
    const resolveImages=async(all:boolean)=>{const snapshot=store.getSnapshot();const refs=all?imageReferences(snapshot.text):[imageAt(snapshot.text,snapshot.selection.head)].filter((item):item is NonNullable<typeof item>=>!!item);const resolved:{ref:typeof refs[number];path:string}[]=[];for(const ref of refs){if(/^(?:https?:|data:)/i.test(ref.url))continue;const result=await system('assets.resolve',{url:resolveLocalImagePath(ref.url,snapshot.path,snapshot.text)??ref.url,documentPath:snapshot.path});if(result&&typeof result==='object'&&'path'in result&&typeof result.path==='string')resolved.push({ref,path:result.path});}if(!resolved.length)throw new Error('当前没有可处理的本地图片');return{snapshot,resolved};};
    register('image.reveal',async()=>{const {resolved}=await resolveImages(false);if(desktop)valueOf(await desktop.reveal(resolved[0].path));});
    for(const id of ['image.copy','edit.copyImage'])register(id,async()=>{const {resolved}=await resolveImages(false);await system('clipboard.image',{path:resolved[0].path});});
    for(const id of ['image.copyTo','image.moveOrRename','image.deleteFile','image.copyAll','image.moveAll','image.upload','image.uploadAll'])register(id,async()=>{if(!desktop)return;const all=id.endsWith('All'),{snapshot,resolved}=await resolveImages(all);const mapping=new Map<string,string>();
      if(id.includes('upload')){const values=valueOf(await desktop.upload(resolved.map((item,index)=>({id:String(index),path:item.path})),settingsStore.getSnapshot()));values.forEach(item=>{if(item.url)mapping.set(resolved[Number(item.id)].ref.url,item.url);});const errors=values.filter(item=>item.error);if(errors.length)context.notify(errors.map(item=>item.error).join('；'));}
      else {const operation=id.includes('delete')?'delete':id.includes('copy')?'copy':id.includes('Rename')?'rename':'move';let destination:string|undefined;if(operation==='delete'){if(await ask('删除图片文件','所有引用此图片的文档都会失去图片文件。',[{id:'delete',label:'移入回收站'},{id:'cancel',label:'取消'}])!=='delete')return;}else if(operation==='rename'){const value=await ask('移动或重命名图片','输入目标文件完整路径',[{id:'submit',label:'应用'},{id:'cancel',label:'取消'}],resolved[0].path);if(!value||value==='cancel')return;destination=value;}else{destination=valueOf(await desktop.chooseFolder())??undefined;if(!destination)return;}const paths=[...new Set(resolved.map(item=>item.path))];const values=valueOf(await desktop.manageAssets(operation,paths,destination));values.forEach((item,index)=>{if(!item.error&&operation!=='delete')resolved.filter(original=>original.path===paths[index]).forEach(original=>mapping.set(original.ref.url,imageDestination(item.path,snapshot.path,settingsStore.getSnapshot(),snapshot.text)));});const errors=values.filter(item=>item.error);if(errors.length)context.notify(errors.map(item=>item.error).join('；'));}
      const current=store.getSnapshot();if(current.documentId!==snapshot.documentId||current.version!==snapshot.version)throw new Error('DOCUMENT_CHANGED：图片处理期间文档已改变，原文未回写');const changes=imageReferences(current.text).flatMap(ref=>{const url=mapping.get(ref.url);return url?[replaceImageDestination(current.text,ref,url)]:[];});const unique=[...new Map(changes.map(change=>[change.from,change])).values()];if(unique.length)store.apply({transactionId:crypto.randomUUID(),documentId:current.documentId,baseVersion:current.version,changes:unique,origin:'asset'});setEditorGeneration(value=>value+1);
    });
    register('app.site',async()=>{if(desktop)valueOf(await desktop.openExternal('https://github.com/Cjy-CN/OpenTypora'));});register('app.feedback',async()=>{if(desktop)valueOf(await desktop.openExternal('https://github.com/Cjy-CN/OpenTypora/issues'));});
    register('app.windowsNewItem',async()=>{const action=await ask('资源管理器集成','管理当前用户的 Markdown 新建菜单。',[{id:'add',label:'添加新建菜单'},{id:'remove',label:'移除新建菜单'},{id:'cancel',label:'取消'}]);if(action&&action!=='cancel'){await system(`shellNew.${action}`);context.notify('资源管理器新建菜单已更新');}});register('app.update',()=>setUpdateOpen(true));
    const dispose=desktop?.onCommand(id=>{if(id==='spellcheck.context'){window.dispatchEvent(new Event('opentypora:spellcheck-context'));}else if(id==='app.reloadSettings'){void desktop!.loadSettings().then(result=>{if(result.ok)settingsStore.load(result.value);else context.notify(result.error.message);});}else command.current(id);});return()=>{disposers.forEach(fn=>fn());dispose?.();};
  },[registry,context,ask,coordinator,saveWithAssets]);
  useEffect(()=>{let ready=false,cancelled=false;let timer:ReturnType<typeof setTimeout>;const persist=()=>{if(!ready)return;clearTimeout(timer);timer=setTimeout(()=>{void desktop?.saveSettings(settingsStore.getSnapshot()).then(result=>{if(!result.ok)context.notify(result.error.message);});},300);};const dispose=settingsStore.subscribe(persist);void(async()=>{const result=await desktop?.loadSettings();if(cancelled)return;if(result?.ok){const rejected=settingsStore.load(result.value);if(rejected.length)context.notify(`忽略无效设置：${rejected.join('、')}`);}else if(result){context.notify(result.error.message+'；自动写入配置已停止，请在高级配置中备份并恢复后重启');}if(!settingsStore.getSnapshot()['export.profiles']||settingsStore.getSnapshot()['export.profiles']==='[]')settingsStore.set('export.profiles',JSON.stringify(DEFAULT_EXPORT_PROFILES));ready=!result||result.ok;settingsReady.current=ready;persist();if(!desktop)return;if(settingsStore.getSnapshot()['file.startup']==='last'&&!new URLSearchParams(window.location.search).has('document')){const history=await desktop.systemAction('history.list');if(history.ok&&Array.isArray(history.value)){const file=history.value.find((item:any)=>item.kind==='file'),folder=history.value.find((item:any)=>item.kind==='folder');if(file)await registry.execute('file.open',context,file.path);if(folder&&!store.getSnapshot().path)command.current('file.openFolder',folder.path);}}const drafts=await desktop.listRecovery();if(cancelled||!drafts.ok||!drafts.value.length)return;const choice=await ask('恢复草稿','检测到尚未保存的草稿。',drafts.value.slice(0,8).map(draft=>({id:draft.id,label:`恢复 ${draft.session.path?.split(/[\\/]/).pop()??'未命名'}（${new Date(draft.savedAt).toLocaleString()}）`})).concat([{id:'skip',label:'稍后恢复'}]));const draft=drafts.value.find(item=>item.id===choice);if(draft)store.replaceSession(draft.session);})();return()=>{cancelled=true;clearTimeout(timer);dispose();};},[ask,context]);
  useEffect(()=>{if(!desktop)return;void desktop.systemAction('spellcheck.configure',{language:settings['editor.spellLanguage']}).then(result=>{if(!result.ok)context.notify(result.error.message+(result.error.detail?'：'+result.error.detail:''));});},[settings['editor.spellLanguage'],context]);
  useEffect(()=>{if(!desktop||!settingsReady.current)return;void desktop.systemAction('debug.configure',{enabled:settings['general.debug']}).then(result=>{if(!result.ok)context.notify(result.error.message);});},[settings['general.debug'],context]);
  useEffect(()=>{if(!desktop||!settingsReady.current||!settings['general.autoUpdate'])return;let cancelled=false;void desktop.systemAction('updates.check').then(result=>{if(cancelled)return;if(!result.ok)context.notify(result.error.message);else if((result.value as {available?:boolean})?.available)setUpdateOpen(true);});return()=>{cancelled=true;};},[settings['general.autoUpdate'],context]);
  useEffect(()=>{window.document.title=`${document.path?.split(/[\\/]/).pop()??'未命名'}${document.dirty?' •':''} — OpenTypora`;},[document.path,document.dirty]);
  useEffect(()=>{if(!desktop||!document.dirty||document.composing||!settings['file.recovery'])return;const timer=setTimeout(()=>{void desktop!.writeRecovery({id:document.recoveryId,session:document,savedAt:Date.now()}).then(result=>{if(!result.ok)context.notify(result.error.message);});},1000);return()=>clearTimeout(timer);},[document,settings,context]);
  useEffect(()=>{if(!settings['file.autoSave']||!document.path||!document.dirty||document.composing||document.readonly||document.saveState!=='idle')return;const timer=setTimeout(()=>void saveWithAssets(),1500);return()=>clearTimeout(timer);},[document,settings,saveWithAssets]);
  useEffect(()=>desktop?.onFileChanged(path=>{void refreshExternalFile(store,desktop!,path,context.notify);}),[context]);
  useEffect(()=>{const listener=(event:KeyboardEvent)=>{if(event.defaultPrevented||event.isComposing||prompt)return;const target=event.target as HTMLElement;if(target.closest('.workspace-dialog,.editor-dialog'))return;if((target.tagName==='INPUT'||target.tagName==='TEXTAREA')&&!target.closest('.cm-editor'))return;let custom:Record<string,string>={};try{custom=JSON.parse(settingsStore.getSnapshot()['general.shortcuts']);}catch{}const item=COMMANDS.find(item=>matchesShortcut(event,custom[item.id]??item.shortcut??''));if(item&&registry.isEnabled(item.id,context)){event.preventDefault();run(item.id);}};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[registry,context,run,prompt]);
  useEffect(()=>{const listener=(event:MouseEvent)=>{if(event.defaultPrevented||(event.target as Element).closest(".cm-editor"))return;const anchor=(event.target as Element).closest<HTMLAnchorElement>('a[href]');if(!anchor)return;const url=anchor.getAttribute('href')??'';if(url.startsWith('#'))return;event.preventDefault();if(/^(https?:|mailto:)/i.test(url))void desktop?.openExternal(url);else if(/\.(md|markdown)(?:#.*)?$/i.test(url)){void desktop?.systemAction('assets.resolve',{url:url.split('#')[0],documentPath:store.getSnapshot().path}).then(result=>{if(result.ok&&result.value&&typeof result.value==='object'&&'path'in result.value)run('file.open',result.value.path);});}};window.addEventListener('click',listener);return()=>window.removeEventListener('click',listener);},[run]);
  return <><div onDragOver={event=>{if(event.dataTransfer.types.includes('Files'))event.preventDefault();}} onDropCapture={event=>{if(!desktop?.pathForFile||!event.dataTransfer.files.length)return;event.preventDefault();event.stopPropagation();const file=event.dataTransfer.files[0],path=desktop.pathForFile(file);if(!path)return;void(async()=>{try{const metadata=valueOf(await desktop!.systemAction('file.stat',{path})) as {isDirectory:boolean};const options=settingsStore.getSnapshot();if(metadata.isDirectory){if(options['file.dropFolder']==='open')run('file.openFolder',path);return;}if(/\.(png|jpe?g|gif|webp|svg|bmp|avif)$/i.test(path)){const current=store.getSnapshot(),asset=valueOf(await desktop!.systemAction('assets.stage',{path,documentPath:current.path,documentText:current.text,strategy:options['image.strategy']})) as AssetResult;if(store.getSnapshot().documentId!==current.documentId||store.getSnapshot().version!==current.version)throw new Error('DOCUMENT_CHANGED：插入图片期间文档已改变，请重试');run('image.insert',{url:asset.url,alt:file.name});}else if(/\.(md|markdown|txt|mdx|rmd|qmd)$/i.test(path)){if(options['file.dropMarkdown']==='open')run('file.open',path);else{const current=store.getSnapshot(),opened=valueOf(await desktop!.readFile(path));if(store.getSnapshot().documentId!==current.documentId||store.getSnapshot().version!==current.version)throw new Error('DOCUMENT_CHANGED：读取期间文档已改变，请重试');store.apply({transactionId:crypto.randomUUID(),documentId:current.documentId,baseVersion:current.version,changes:[{from:Math.min(current.selection.anchor,current.selection.head),to:Math.max(current.selection.anchor,current.selection.head),insert:opened.text}],origin:'command'});}}else if(options['file.dropImport']==='import')run('file.import',path);}catch(error){context.notify(error instanceof Error?error.message:String(error));}})();}}>
    <WorkspaceShell store={store} settingsStore={settingsStore} registry={registry} context={context} bridge={desktop} message={message} viewModes={{source:sourceMode,focus:focusMode,typewriter:typewriterMode}} onCommand={run} onNavigate={position=>editor.current?.scrollTo(position)} editor={<MarkdownEditor key={editorGeneration} ref={editor} store={store} settings={settings} sourceMode={sourceMode} focusMode={focusMode} typewriterMode={typewriterMode} bridge={desktop} onCommand={run}/>} />
  </div>{updateOpen&&<UpdateDialog bridge={desktop} onClose={()=>setUpdateOpen(false)}/ >}{prompt&&<Dialog title={prompt.title} onClose={()=>answer(null)}><p className="app-prompt-message">{prompt.message}</p>{prompt.input!==undefined&&<input autoFocus aria-label={prompt.title} value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')answer(input);}}/>}<div className="app-prompt-actions">{prompt.choices.map(choice=><button key={choice.id} onClick={()=>answer(choice.id==='submit'?input:choice.id)}>{choice.label}</button>)}</div></Dialog>}</>;
}
