import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createServer, type Server, type IncomingMessage, type ServerResponse } from 'node:http';
import MarkdownIt from 'markdown-it';
import { decodeFile, readFile, saveFile } from './files';
import { Storage } from './storage';
import { authorizeDirectory, resolveAsset, resolveAuthorizedAsset } from './access';
import { assetUrl, manageAssets, uniqueAsset, uploadItems } from './assets';
import { searchFiles } from './search';
import { runCommand } from './process';
import { effectiveOptions, exportHtml, ExportService, type RenderService } from './export';
import { SystemService } from './system';
import { preferredSpellcheckLanguages } from './spellcheck';
import type { ExportFormat, ExportSnapshot, RecoveryDraft } from '../../src/shared/contracts';
let directory:string;const servers:Server[]=[];
beforeEach(async()=>{directory=await fs.mkdtemp(join(tmpdir(),'opentypora-services-'));});
afterEach(async()=>{for(const server of servers.splice(0))await new Promise<void>(resolve=>server.close(()=>resolve()));await fs.rm(directory,{recursive:true,force:true});});
const snapshot=(format:ExportFormat='html',extension='html'):ExportSnapshot=>({documentId:'doc-test',version:8,text:'# 中文标题\n\n**bold**\n\n|A|B|\n|-|-|\n|1|2|\n',path:null,html:'<h1 id="title">中文标题</h1><p><strong>bold</strong></p>',title:'测试标题',profile:{id:'profile',name:format,format,extension,options:{},args:[],openFile:false,openFolder:false}});
const noRender:RenderService={pdf:async()=>{throw new Error('此测试不调用浏览器渲染');},image:async()=>{throw new Error('此测试不调用浏览器渲染');}};
async function localServer(handler:(request:IncomingMessage,response:ServerResponse)=>void):Promise<string>{const server=createServer(handler);servers.push(server);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();return`http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`;}
describe('文件、恢复与资源实际磁盘行为',()=>{
  it('文件stat只返回真实路径和元数据，目录/二进制不读取正文',async()=>{const path=join(directory,'binary.dat'),bytes=Buffer.from([0x81,0x40,0xff,0x00]);await fs.writeFile(path,bytes);const service=new SystemService(new Storage(directory),{version:'1.0.0',platform:process.platform,executable:process.execPath,userData:directory,openPath:async()=>'',openExternal:async()=>undefined});const metadata=await service.action('file.stat',{path});expect(metadata).toEqual({path:await fs.realpath(path),isDirectory:false,isFile:true,size:4,modifiedAt:(await fs.stat(path)).mtimeMs,readonly:false});expect(await service.action('file.stat',{path:directory})).toMatchObject({path:await fs.realpath(directory),isDirectory:true,isFile:false});await expect(readFile(path)).rejects.toMatchObject({code:'ENCODING_REQUIRED'});expect(await fs.readFile(path)).toEqual(bytes);await expect(service.action('file.stat',{path:'../relative'})).rejects.toMatchObject({code:'INVALID_PATH'});await expect(service.action('file.stat',{path:join(directory,'missing')})).rejects.toMatchObject({code:'ENOENT'});});
  it.each(['utf-8','utf16-le','utf16-be','gb18030'])('无损保持 %s 编码与混合换行',async encoding=>{const path=join(directory,'中文 空格.md');const text='# 中 😀\r\n\nA  B\n';const saved=await saveFile({path,text,encoding,bom:encoding!=='gb18030',version:1,expectedFingerprint:null});const opened=await readFile(path,encoding);expect(opened.text).toBe(text);expect(opened.fingerprint.hash).toBe(saved.fingerprint.hash);});
  it('无法识别编码不给出乱码成功',()=>{expect(()=>decodeFile(Buffer.from([0x81,0x40]))).toThrow(/选择.*编码/);});
  it('有损编码拒绝保存且原文件字节保持',async()=>{const path=join(directory,'test.md');await fs.writeFile(path,'original');await expect(saveFile({path,text:'中文',encoding:'ascii',bom:false,version:1,expectedFingerprint:null})).rejects.toMatchObject({code:'ENCODING_LOSS'});expect(await fs.readFile(path,'utf8')).toBe('original');});
  it('并发同指纹保存只接受第一个并清理临时文件',async()=>{const path=join(directory,'test.md');const initial=await saveFile({path,text:'initial',encoding:'utf-8',bom:false,version:0,expectedFingerprint:null});const requests=['one','two'].map((text,index)=>saveFile({path,text,encoding:'utf-8',bom:false,version:index+1,expectedFingerprint:initial.fingerprint}));const outcomes=await Promise.allSettled(requests);expect(outcomes.map(item=>item.status)).toEqual(['fulfilled','rejected']);expect(await fs.readFile(path,'utf8')).toBe('one');expect(await fs.readdir(directory)).toEqual(['test.md']);});
  it('不允许相对路径与草稿目录穿越',async()=>{await expect(readFile('../secret.md')).rejects.toMatchObject({code:'INVALID_PATH'});await expect(new Storage(directory).deleteRecovery('../secret')).rejects.toMatchObject({code:'INVALID_ID'});});
  it('配置实际落盘校验、备份与历史开关',async()=>{const storage=new Storage(directory);await storage.saveSettings({'file.history':false});await storage.remember(join(directory,'x.md'));expect(await storage.history()).toEqual([]);await expect(storage.saveSettings({'appearance.zoom':900})).rejects.toMatchObject({code:'SETTING_RANGE'});expect(await storage.loadSettings()).toEqual({'file.history':false});const backup=await storage.backup('settings');expect(JSON.parse(await fs.readFile(backup!,'utf8'))).toEqual({'file.history':false});});
  it('恢复草稿拒绝迟到版本，删除只删目标草稿',async()=>{const storage=new Storage(directory);const draft={id:'recovery-test',savedAt:Date.now(),session:{documentId:'doc-test',recoveryId:'recovery-test',version:3,text:'最新'}} as RecoveryDraft;await storage.writeRecovery(draft);await storage.writeRecovery({...draft,savedAt:draft.savedAt-1,session:{...draft.session,version:2,text:'旧正文'}});expect((await storage.listRecovery())[0].session.text).toBe('最新');await storage.deleteRecovery(draft.id);expect(await storage.listRecovery()).toEqual([]);});
  it('资源同内容去重、不同内容不覆盖、批量单项失败可查询',async()=>{const source=join(directory,'image.png'),destination=join(directory,'images');await fs.writeFile(source,'first');const first=await uniqueAsset(source,destination);expect(await uniqueAsset(source,destination)).toBe(first);await fs.writeFile(source,'second');const second=await uniqueAsset(source,destination);expect(second).not.toBe(first);expect(await fs.readFile(first,'utf8')).toBe('first');const result=await manageAssets('copy',[source,join(directory,'missing.png')],join(directory,'copy'),async()=>undefined);expect(result[0].error).toBeUndefined();expect(result[1].error).toBeTruthy();});
  it('只允许授权真实路径，协议编码/相对中文路径正确解析',async()=>{const folder=join(directory,'opened'),outside=join(directory,'outside.png');await fs.mkdir(folder);const path=join(folder,'空 格#.png');await fs.writeFile(path,'image');await fs.writeFile(outside,'secret');await authorizeDirectory(folder);const value=await resolveAsset('空%20格%23.png',join(folder,'doc.md'));expect(value.path).toBe(await fs.realpath(path));expect(await resolveAuthorizedAsset(value.url)).toBe(await fs.realpath(path));expect(await resolveAuthorizedAsset(outside)).toBeUndefined();expect(await resolveAuthorizedAsset(join(folder,'..','outside.png'))).toBeUndefined();expect(assetUrl(path,join(folder,'doc.md'),{'image.relative':true,'image.prefixDot':true,'image.escapeUrl':true})).toBe('./%E7%A9%BA%20%E6%A0%BC%23.png');});
  it('图片URL通过尖括号Markdown目的地保持空格和括号资源有效',async()=>{const path=join(directory,'空 格未配对).png'),documentPath=join(directory,'doc.md');await fs.writeFile(path,'image');await authorizeDirectory(directory);const parser=new MarkdownIt();for(const settings of [{'image.relative':true,'image.escapeUrl':false},{'image.relative':true,'image.escapeUrl':true}]){const value=assetUrl(path,documentPath,settings),tokens=parser.parseInline(`![image](<${value}>)`,{});const image=tokens[0].children?.find(token=>token.type==='image');expect(image).toBeDefined();expect((await resolveAsset(image!.attrGet('src')!,documentPath)).path).toBe(await fs.realpath(path));}expect((await resolveAsset(assetUrl(path,documentPath,{}),documentPath)).path).toBe(await fs.realpath(path));const raw=assetUrl(path,documentPath,{'image.relative':true,'image.escapeUrl':false});expect(parser.renderInline(`![image](${raw})`)).not.toContain('<img');});
});
describe('系统偏好到真实拼写词典语言代码映射',()=>{
  it('优先精确匹配，支持基础语言回退、区域偏好及去重',()=>{const available=['en-US','en-GB','de','fr','pt-BR','pt-PT'];expect(preferredSpellcheckLanguages(['fr-FR','en_GB','de-DE','fr','zh-CN'],available)).toEqual(['fr','en-GB','de']);expect(preferredSpellcheckLanguages(['en','pt-PT'],available)).toEqual(['en-US','pt-PT']);});
  it('没有系统匹配时只使用可用en-US，缺词典保留无可用结果',()=>{expect(preferredSpellcheckLanguages(['zh-CN'],['fr','en-US'])).toEqual(['en-US']);expect(preferredSpellcheckLanguages(['zh-CN'],['fr'])).toEqual([]);expect(preferredSpellcheckLanguages([],[])).toEqual([]);});
});
describe('搜索、外部程序与上传实际协议',()=>{
  it('跨文件Unicode全词、行号与UTF-16偏移正确',async()=>{await fs.mkdir(join(directory,'child'));await fs.writeFile(join(directory,'中文.md'),'😀\nAlpha alphaBeta\nALPHA\n');await fs.writeFile(join(directory,'child','second.md'),'Alpha');const matches=await searchFiles(directory,'alpha',{regex:false,caseSensitive:false,wholeWord:true});expect(matches).toHaveLength(3);const match=matches.find(item=>item.line===2)!;expect(match.from).toBe(3);expect(match.to).toBe(8);});
  it('无效正则和取消有明确失败',async()=>{await expect(searchFiles(directory,'[',{regex:true,caseSensitive:false,wholeWord:false})).rejects.toMatchObject({code:'INVALID_REGEX'});const controller=new AbortController();controller.abort();await expect(searchFiles(directory,'x',{regex:false,caseSensitive:false,wholeWord:false},controller.signal)).rejects.toMatchObject({code:'CANCELLED'});});
  it('有效正则在工作线程搜索，灾难性回溯超时不阻塞主线程',async()=>{const path=join(directory,'regex.md');await fs.writeFile(path,'alpha\nbeta\n');expect((await searchFiles(directory,'^b.*',{regex:true,caseSensitive:false,wholeWord:false}))[0].line).toBe(2);await fs.writeFile(path,'a'.repeat(200)+'!');let responsive=false;const task=searchFiles(directory,'(a+)+$',{regex:true,caseSensitive:false,wholeWord:false});setTimeout(()=>{responsive=true;},50);await expect(task).rejects.toMatchObject({code:'SEARCH_PARTIAL'});expect(responsive).toBe(true);},5000);
  it('shell字符作为原始参数、非零返回码与超时真实捕获',async()=>{const argument='中文 空格 & $(danger) `literal`';const output=await runCommand(process.execPath,['-e','process.stdout.write(process.argv[1])',argument]);expect(output.stdout).toBe(argument);await expect(runCommand(process.execPath,['-e','console.error("failed");process.exit(7)'])).rejects.toMatchObject({code:'COMMAND_FAILED'});await expect(runCommand(process.execPath,['-e','setTimeout(()=>{},5000)'],{timeout:50})).rejects.toMatchObject({code:'COMMAND_TIMEOUT'});});
  it('npm Windows shim转为真实Node CLI，不执行批处理文本',async()=>{const folder=join(directory,'node_modules','picgo','bin');await fs.mkdir(folder,{recursive:true});await fs.writeFile(join(folder,'picgo.cjs'),'process.stdout.write(process.argv.at(-1));');const shim=join(directory,'picgo.cmd');await fs.writeFile(shim,'@echo off\nset "_prog=node.exe"\n"%_prog%" "%dp0%\\node_modules\\picgo\\bin\\picgo.cjs" %*\n');const argument='中文 & $(literal)';expect((await runCommand(shim,[argument])).stdout).toBe(argument);const unsafe=join(directory,'custom.cmd');await fs.writeFile(unsafe,'@echo off\n echo simulated');await expect(runCommand(unsafe,[])).rejects.toMatchObject({code:'EXECUTABLE_REQUIRED'});});
  it.each(['picgo','piclist'])('%s HTTP适配真实连接和部分失败',async uploader=>{const path=join(directory,'image.png');await fs.writeFile(path,'image');let received:string[]=[];const endpoint=await localServer((request,response)=>{let data='';request.on('data',chunk=>data+=chunk);request.on('end',()=>{received=JSON.parse(data).list;response.setHeader('Content-Type','application/json');response.end(JSON.stringify({success:true,result:['https://images.example.com/image.png']}));});});const result=await uploadItems([{id:'one',path},{id:'missing',path:join(directory,'missing.png')}],{'image.uploader':uploader,'image.uploadEndpoint':`${endpoint}/upload`});expect(received).toEqual([path]);expect(result[0]).toEqual({id:'one',url:'https://images.example.com/image.png'});expect(result[1].error).toBeTruthy();});
  it('Core与自定义上传通过真实子进程解析结果，缺工具保留失败项',async()=>{const path=join(directory,'image.png');await fs.writeFile(path,'image');const fixture=join(directory,'upload fixture.cjs');await fs.writeFile(fixture,'process.stdout.write(JSON.stringify({urls:["https://images.example.com/"+encodeURIComponent(process.argv.at(-1))]}));');for(const uploader of ['picgo-core','custom']){const result=await uploadItems([{id:'one',path}],{'image.uploader':uploader,'image.uploadExecutable':process.execPath,'image.uploadArgs':JSON.stringify([fixture])});expect(result[0].url).toContain('https://images.example.com/');}const missing=await uploadItems([{id:'one',path}],{'image.uploader':'custom','image.uploadExecutable':join(directory,'missing.exe')});expect(missing[0].error).toContain('找不到程序');});
});
describe('冻结快照、导出安全与实际转换',()=>{
  it('YAML只覆盖排版白名单，无法指定程序或后置命令',()=>{const value=snapshot();value.profile.options={yamlOverride:true,executable:'user-config'};value.text='---\nexport:\n  pageSize: A5\n  executable: malicious.exe\n  afterCommand: rm\n---\n';expect(effectiveOptions(value)).toMatchObject({pageSize:'A5',executable:'user-config'});expect(effectiveOptions(value).afterCommand).toBeUndefined();});
  it('HTML内嵌授权本地图片、保留SVG、禁用活动脚本',async()=>{const path=join(directory,'图.png');await fs.writeFile(path,Buffer.from([137,80,78,71]));await authorizeDirectory(directory);const value=snapshot();value.path=join(directory,'doc.md');value.html='<h1 id="heading">标题</h1><img src="图.png"><svg viewBox="0 0 20 20"><path d="M0 0"/></svg><script>process.exit()</script><p onclick="danger()">safe</p>';const warnings:string[]=[];const html=await exportHtml(value,{retainOutline:true},warnings);expect(html).toContain('data:image/png;base64,');expect(html).toContain('<svg');expect(html).toContain('href="#heading"');expect(html).not.toContain('<script');expect(html).not.toContain('onclick');expect(warnings).toEqual([]);});
  it('远程图片实际下载内嵌，HTTP失败保留地址并报告离线风险',async()=>{const endpoint=await localServer((request,response)=>{if(request.url==='/image'){response.setHeader('Content-Type','image/png');response.end(Buffer.from([137,80,78,71]));}else{response.statusCode=404;response.end();}});const value=snapshot();value.html=`<img src="${endpoint}/image"><img src="${endpoint}/missing">`;const warnings:string[]=[];const html=await exportHtml(value,{},warnings);expect(html).toContain('data:image/png;base64,');expect(html).toContain(`${endpoint}/missing`);expect(warnings).toHaveLength(1);expect(warnings[0]).toContain('HTTP 404');});
  it('自定义转换真实执行、冻结快照且原文件保持',async()=>{const fixture=join(directory,'converter.cjs');await fs.writeFile(fixture,'const fs=require("fs");setTimeout(()=>fs.copyFileSync(process.argv[2],process.argv[3]),50);');const service=new ExportService(directory,noRender),value=snapshot('custom','txt'),output=join(directory,'out.txt');value.profile.options={executable:process.execPath};value.profile.args=[fixture,'${input}','${output}'];const task=service.export(value,output,{});value.text='late modification';await task;expect(await fs.readFile(output,'utf8')).toContain('# 中文标题');expect(await fs.readdir(directory)).not.toContain('input.md');});
  it('缺转换器及转换失败不覆盖原输出、不留下半成品',async()=>{const service=new ExportService(directory,noRender),output=join(directory,'result.docx');await fs.writeFile(output,'original');await expect(service.export(snapshot('docx','docx'),output,{'export.pandocPath':join(directory,'absent.exe')})).rejects.toMatchObject({code:'DEPENDENCY_MISSING'});expect(await fs.readFile(output,'utf8')).toBe('original');expect(await fs.readdir(join(directory,'exports'))).toEqual([]);});
  const pandoc=process.env.OPENTYPORA_TEST_PANDOC;
  it.runIf(!!pandoc).each(Object.entries({docx:'docx',odt:'odt',rtf:'rtf',epub:'epub',latex:'tex',mediawiki:'wiki',rst:'rst',textile:'textile',opml:'opml',markdown:'md',native:'native'}))('真实Pandoc %s导出和再次读取验证',async(format,extension)=>{const service=new ExportService(directory,noRender),value=snapshot(format as ExportFormat,extension),output=join(directory,`实际输出.${extension}`);await service.export(value,output,{'export.pandocPath':pandoc});const bytes=await fs.readFile(output);expect(bytes.length).toBeGreaterThan(20);if(['docx','odt','epub'].includes(format))expect(bytes.subarray(0,2).toString()).toBe('PK');if(format==='rtf')expect(bytes.toString()).toContain('{\\rtf');if(format==='opml')expect(bytes.toString()).toContain('<opml');if(format!=='native'){const imported=await service.import(output,{'export.pandocPath':pandoc});expect(imported.text).toContain('中文标题');}else{const result=await runCommand(pandoc!,['--from','native','--to','markdown',output]);expect(result.stdout).toContain('中文标题');}expect(bytes).toEqual(await fs.readFile(output));},30_000);
  it.runIf(!!pandoc)('真实Pandoc通用格式及LaTeX PDF缺TeX诊断',async()=>{const service=new ExportService(directory,noRender),value=snapshot('pandoc','json');value.profile.options={outputFormat:'json'};await service.export(value,join(directory,'out.json'),{'export.pandocPath':pandoc});const json=JSON.parse(await fs.readFile(join(directory,'out.json'),'utf8'));expect(json['pandoc-api-version']).toBeTruthy();const pdf=snapshot('pdf-latex','pdf');await expect(service.export(pdf,join(directory,'out.pdf'),{'export.pandocPath':pandoc})).rejects.toThrow(/xelatex|pdf-engine/);},30_000);
});
describe('更新系统真实HTTP与诊断',()=>{
  it('遥测显式开关和端点生效，只发送固定非正文字段',async()=>{let payload:Record<string,unknown>={};const endpoint=await localServer((request,response)=>{let data='';request.on('data',chunk=>data+=chunk);request.on('end',()=>{payload=JSON.parse(data);response.end('ok');});});const storage=new Storage(directory),service=new SystemService(storage,{version:'1.0.0',platform:'win32',executable:process.execPath,userData:directory,openPath:async()=>'',openExternal:async()=>undefined});await expect(service.action('telemetry.send',{event:'app.open'})).rejects.toMatchObject({code:'TELEMETRY_DISABLED'});await storage.saveSettings({'general.telemetry':true,'general.telemetryEndpoint':`${endpoint}/events`});expect(await service.action('telemetry.status')).toMatchObject({enabled:true,endpointConfigured:true});await service.action('telemetry.send',{event:'app.open',text:'不应发送的正文',path:'私有路径',token:'凭据'});expect(payload).toEqual({event:'app.open',version:'1.0.0',platform:'win32'});await expect(service.action('telemetry.send',{event:'arbitrary'})).rejects.toMatchObject({code:'INVALID_TELEMETRY_EVENT'});});
  it('版本检测、真实下载校验、安装打开调用与失败状态',async()=>{let endpoint='';const binary=Buffer.from('test-only-update-binary');endpoint=await localServer((request,response)=>{if(request.url==='/release'){response.setHeader('Content-Type','application/json');response.end(JSON.stringify({tag_name:'v2.0.0',prerelease:false,assets:[{name:'OpenTypora.exe',browser_download_url:`${endpoint}/OpenTypora.exe`,size:binary.length}]}));}else response.end(binary);});const storage=new Storage(directory);await storage.saveSettings({'general.serviceSource':`${endpoint}/release`});let opened='';const service=new SystemService(storage,{version:'1.0.0',platform:'win32',executable:process.execPath,userData:directory,openPath:async path=>{opened=path;return'';},openExternal:async()=>undefined});expect(await service.checkUpdates()).toMatchObject({available:true,version:'2.0.0'});const downloaded=await service.downloadUpdate({url:`${endpoint}/OpenTypora.exe`}) as {path:string};expect(await fs.readFile(downloaded.path)).toEqual(binary);await service.installUpdate();expect(opened).toBe(downloaded.path);await expect(service.action('arbitrary.execute')).rejects.toMatchObject({code:'INVALID_SYSTEM_ACTION'});});
});
